### ISSUE TITLE
Travis CI: MySQL is not available

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1509] opened 2017-05-16 20:35 UTC
My system information:
* Operating system type: Travis CI
* BLT version: 8.x.dev (8.9.x)

When I run this command:
```
blt setup:drupal:install
```

I get the following output:
```
MySQL is not available
```

And I expected this to happen:

Drupal installation

Note that this was fixed by swapping out the default alias in project.yml.

```
drush:
  aliases:
    remote: <project>.test
    local:<project>.local
    ci: self
    default_alias: '${drush.aliases.local}'
  default_alias: self
```

**Comment by mikemadison13** [comment] 2017-05-16 20:51
as part of the above fix, the builds are now hanging at this step:

```
install-alias
BLT can automatically create a Bash alias to make it easier to run BLT tasks.
This alias may be created in .bash_profile or .bashrc depending on your system architecture.
 Install alias? (y/n) 
```

My hunch is that the build doesn't have permission to do this (or shouldn't do it)?

**Comment by grasmash** [comment] 2017-05-17 01:29
The second issue is a duplicate of #1502

**Closed** 2017-05-17 04:09 UTC
Labels: bug, in progress
