### ISSUE TITLE
Remove cache-rebuild prior to updb

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#3001] opened 2018-08-07 02:22 UTC
My system information:
* Operating system type: Acquia Cloud Enterprise
* Operating system version: Ubuntu Xenial
* BLT version: 9.1.0

This is happening on a Drupal 8.5.6 upgrade (from Drupal 8.4.x). The Cloud hooks is triggering BLT to do the following commands.

When I run this command:
```
/mnt/users/[SITE]/uat.shell /var/www/html/[SITE].uat/hooks/common/post-code-deploy/post-code-deploy.sh [SITE] uat upgrade-build upgrade-build [SITE]@svn-[SERVER].prod.hosting.acquia.com:[SITE].git git < /dev/null (as [SITE].uat@staging-[SERVER]})
```

I get the following output:
```
<< [2018-07-31 07:44:36] Starting hook: post-code-deploy
<< [2018-07-31 07:44:39] Executing: /mnt/users/[SITE]/uat.shell /var/www/html/[SITE].uat/hooks/common/post-code-deploy/post-code-deploy.sh [SITE] uat upgrade-build upgrade-build [SITE]@svn-24511.prod.hosting.acquia.com:[SITE].git git < /dev/null (as [SITE].uat@staging-[SERVER]})
<<
<< site="$1"
<< target_env="$2"
<< source_branch="$3"
<< deployed_tag="$4"
<< repo_url="$5"
<< repo_type="$6"
<<
<< # Prep for BLT commands.
<< repo_root="/var/www/html/$site.$target_env"
<< export PATH=$repo_root/vendor/bin:$PATH
<< cd $repo_root
<<
<< blt artifact:ac-hooks:post-code-deploy $site $target_env $source_branch $deployed_tag $repo_url $repo_type --environment=$target_env -v --yes --no-interaction
<< Running updates for environment: uat
<< > artifact:update:drupal:all-sites
<< Deploying updates to default...
<< > drupal:config:import
<< [info] Skipped pre-config-import target hook. No hook is defined.
<< [Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/[SITE].uat/vendor/bin/drush @self cc drush --no-interaction -v --ansi in /var/www/html/[SITE].uat/docroot
<<  [info] Executing: mysql --defaults-file=/mnt/tmp/[SITE]/drush_9FpFzX --database=[SITE] --host=staging-[SERVER] --port=3306 --silent  < /mnt/tmp/[SITE]/drush_g92QaF
<<  [info] Executing: mysql --defaults-file=/mnt/tmp/[SITE]/drush_FVPnry --database=[SITE] --host=staging-[SERVER] --port=3306 --silent  < /mnt/tmp/[SITE]/drush_pyUv0f
<<  [success] 'drush' cache was cleared.
<< [Acquia\Blt\Robo\Tasks\DrushTask] Done in 0.522s
<< [Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/[SITE].uat/vendor/bin/drush @self cache-rebuild --no-interaction -v --ansi in /var/www/html/[SITE].uat/docroot
<<  [error]  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'revision.revision_default' in 'field list': SELECT revision.revision_id AS revision_id, revision.langcode AS langcode, revision.revision_user AS revision_user, revision.revision_created AS revision_created, revision.revision_log AS revision_log, revision.revision_default AS revision_default, base.id AS id, base.type AS type, base.uuid AS uuid, CASE base.revision_id WHEN revision.revision_id THEN 1 ELSE 0 END AS isDefaultRevision
<< FROM
<< {block_content} base
<< INNER JOIN {block_content_revision} revision ON revision.revision_id = base.revision_id
<< WHERE base.id IN (:db_condition_placeholder_0); Array
<< (
<<     [:db_condition_placeholder_0] => 4
<< )
<<
<< [Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 3.633s
<< [error]  Failed to import configuration!
<< [error]  Command `drupal:config:import ` exited with code 1.
<< Slack webhook url not found. To enable Slack notifications, set slack.webhook-url.
<< [error]  Command `artifact:update:drupal:all-sites ` exited with code 1.
<< 4.018s total time elapsed.
<< [2018-07-31 07:44:43] Finished hook: post-code-deploy
<<
<< [2018-07-31 07:44:43] DEBUG: <- listSitegroupWebhooks({:request=><Aq::Hosting::Type::ListSitegroupWebhooksRequest sitegroup_name:"[SITE]">})
<< [2018-07-31 07:44:43] DEBUG: -> <Aq::Hosting::Type::ListSitegroupWebhooksResponse sitegroup_webhooks:[]>
<< [2018-07-31 07:44:43] Sending webhook hook: 'post-code-deploy' revision: ''!
<< [2018-07-31 07:44:43] WARN: Command returned exit code 1: /mnt/users/[SITE]...
```

And I expected this to happen:

The update to Drupal 8.5.6 to work.

**Comment by seanhamlin** [comment] 2018-08-07 02:27
Also worth mentioning that https://www.drupal.org/node/2826466 (the original comment as to why this was introduced) has been fixed in the features module for a while now.

**Comment by lcatlett** [comment] 2018-08-07 11:01
@seanhamlin is this a multisite? It seems odd that the site name is default and 2 different drush cache directories are created at `/mnt/tmp/[SITE]/drush_g92QaF` and  `/mnt/tmp/[SITE]/drush_FVPnry.`

Even if this is not a multisite, it may be that it is `drush cc drush` that is causing issues since it is run explicitly at the beginning of the deploy process and then updb clears the drush cache again

**Comment by ba66e77** [comment] 2018-08-08 23:29
@seanhamlin this feels pretty edge-casey. If I'm reading your output right, somewhere in the jump from 8.5.4 to 8.5.6 the structure of the `block_content_revision` table was updated and when the `cr` ran before `updb` you had new code and old structure and the query failed. Is that right?

Can you outline steps to consistently reproduce the observed issue?

**Comment by ba66e77** [comment] 2018-08-30 18:58
It's been three weeks with no update and the issue doesn't seem to be manifesting anywhere else (at least not that has been reported), so I'm going to close this out. Happy to reopen if someone can help me see how to reproduce the issue.

**Closed by ba66e77** 2018-08-30 18:58 UTC
Labels: Prioritized, drush, in progress, multisite

**Comment by seanhamlin** [comment] 2018-09-02 09:09
Hey all, sorry about the lack of response. This was ACE, no multisite. And we managed to avoid the issue at release time by manually patching the codebase with the patch file from my PR. I suspect we can now remove this patch now (as the release to PROD is complete).

If no-one else is experiencing this weirdness on the 8.5.x upgrade, then I guess this can be closed. Thanks all for looking into this. Gotta love minor version bumps in Drupal.
