### ISSUE TITLE
Deploy script attempts to delete every file on my local machine due to corrupted vendor directory

### ISSUE THREAD

**Issue by alexsoble** [acquia/blt#3784] opened 2019-07-31 15:54 UTC
**Describe the bug**

When I run the `blt artifact:deploy` script locally in verbose mode, I see debug output showing that the script is attempting (unsuccessfully) to delete every file on my computer. 

Command:

```
blt artifact:deploy --commit-msg "Deploy config to dev and staging." --branch "master" --no-interaction --verbose
```

Small slice of the output (output logs show an attempted `delete_file` operation on every file on my computer): 

```
rsync: delete_file: unlink "/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.2.4/System.Runtime.dll" failed: Permission denied (13)
rsync: delete_file: unlink "/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.2.4/System.Runtime.Serialization.dll" failed: Permission denied (13)
rsync: delete_file: unlink "/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.2.4/System.Runtime.Serialization.Xml.dll" failed: Permission denied (13)
... 
```

**To Reproduce**

Steps to reproduce the behavior, ideally starting from a fresh install of BLT:

1. Run `composer create-project acquia/blt-project --no-interaction`.
2. Remove the `vendor/acquia/blt/config` folder. Both myself and my colleague have found ourselves missing this folder locally; another process may be removing it. (More to debug there; separate issue.)
3. Run `blt artifact:deploy --commit-msg "Deploy config to dev and staging." --branch "master" --no-interaction --verbose`.
4. See output.

**Expected behavior**

A deploy script should never attempt to delete every file on a user's local machine under any circumstances, no matter what kind of configuration is present or missing. 

I traced this issue to the following line of code in the BLT project: https://github.com/acquia/blt/blob/37cd5adfad7adf0096410554c24372d9e3b596e5/src/Robo/Commands/Deploy/DeployCommand.php#L438

Because my local setup was missing a `vendor/acquia/blt/config/build.yml` file, the value for `$dest` was null, so that argument evaluated to `/`, resulting in the following command:

```
rsync -a --no-g --delete ... '/local/directory/' '/' --filter 'protect /.git/
```

The rsync documentation describes the --delete option as: "delete extraneous files from dest dirs." Since on my local machine dest was evaluated to `/`, this operation evaluated to rsync's version of:

```
rm -rf /
```

It is important to validate arguments passed to `rm -rf` to prevent unintended and potentially disastrous consequences like this one. My local computer was not bricked because in this case rsync did not have the proper permissions to delete files.

I also found a second, unrelated instance of scripting calling `rm -rf` without error handling or validation on the arguments here:

https://github.com/acquia/blt/blob/cc0551dc3ecb5e586538c9a11b602006df83603c/scripts/pipelines/build_artifact#L16

Validation of arguments passed to `rm -rf` and error handling should be implemented in both instances to make these scripts safe.

**Comment by mikemadison13** [comment] 2019-07-31 15:56
So, this is a massive problem:

```
Remove the vendor/acquia/blt/config folder. Both myself and my colleague have found ourselves missing this folder locally; another process may be removing it. (More to debug there; separate issue.)
```

This is essentially breaking ALL of BLT by doing this. BLT puts all of its default config here. If you want to change anything in here, you can move it into your blt.yml. But any issues you are having here stem from the fact that you deleted the stock blt config. Please don't do that :)

**Comment by alexsoble** [comment] 2019-07-31 16:02
Hi @mikemadison13, thanks for the response. 

My expected behavior from the BLT program in this scenario would be an error message describing the missing config.

A script attempting to delete every single file on my local machine does not seem like reasonable or safe behavior, even with missing config.

**Comment by LindsayYoung** [comment] 2019-07-31 16:04
Yes, we did not purposefully delete the config folder. We don't have vendor files checked into source control. For some reason they did not get installed by composer install or some other process deleted them. This happened on two separate machines. 

Again we are still debugging and will keep you informed if we learn more.

**Comment by mikemadison13** [comment] 2019-07-31 16:05
it seems like a reasonable enhancement for BLT to throw some sort of fatal if that file is missing.

i have had multiple occasions on restrictive networks where composer has gotten borked and things "go missing" (although never this). usually flushing the composer cache fixes the issue.

**Comment by alexsoble** [comment] 2019-07-31 16:14
@mikemadison13 Throwing a fatal error and exiting would be an excellent improvement and far preferable to `rm -rf /`. Additionally, validating the arguments passed to `rm -rf ${args}` would be an excellent enhancement as well. Thanks.

**Comment by mikemadison13** [comment] 2019-07-31 16:15
@danepowell it seems like a relatively low level of effort to have some sort of check when Robo bootstraps that the config file is there prior to "doing" anything. what do you think?

**Comment by danepowell** [comment] 2019-07-31 16:57
If people are going to hack on dependencies like this (or to give them the benefit of the doubt, if Compsoer / Git spontaneously corrupts files like this), there's only so much we can reasonably do about that. That's a serious problem with your practices and/or Git and/or Composer, not a problem with BLT.

I don't think it makes sense to add validation for the deploy directory because who's to say what's valid and what's not. `/` is _probably_ never valid, but just about any other subdirectory might be and we can't check all of the potentially dangerous ones (`/etc`, `/boot`, etc).

I agree that it would make sense to throw an exception if we can't load the default config. That sounds like an upstream bug with consolidation/config, not BLT. I'll look into it.

**Comment by LindsayYoung** [comment] 2019-07-31 17:54
Can I have confirmation that there is going to be some sanity checks added to deployment? Checking for the file or variable would work for me. 

For background on our dev practices, We use Composer to manage installs [Acquia docs](https://docs.acquia.com/resource/composer/) also suggest using Composer- if you have a better practice to implement, please tell us. 

If @mikemadison13, @alexsoble and I have all experienced install issues with composer, it is probably a better bet to not assume Composer is stable.  I have never seen a package manager that installs half a package without throwing an error in any other code ecosystems I have worked in.  We can file a ticket upstream, but I wouldn't completely rely on that. 

I understand that in the abstract this doesn't seem like a likely bug, but since it has happened on two different occasions with two computers, and the results could have been horrible; our team is taking this seriously. 

Thank you.

**Comment by mikemadison13** [comment] 2019-07-31 17:56
to be clear, i've only ever had issues with composer garbling an install on a _local_ install, and only with a restrictive network or faulty network connection. it's never been "because composer is unstable" and it's never happened during deployments / continuous integration.

**Comment by LindsayYoung** [comment] 2019-07-31 18:03
Thanks for the clarification @mikemadison13!

**Comment by danepowell** [comment] 2019-08-01 19:14
> Can I have confirmation that there is going to be some sanity checks added to deployment?

Like I mentioned above, I'm going to look into why there's not an exception thrown if the default configuration isn't present, since that would be the expected behavior in this scenario. It's an exceptionally rare failure mode (this is the first I've ever heard of anything remotely like it happening), but nonetheless one that could be guarded against.

**Closed** 2019-08-07 16:52 UTC
Labels: Enhancement
