### ISSUE TITLE
.gitignore customizations overridden during BLT upgrade

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#915] opened 2017-01-05 16:03 UTC
My system information:
* Operating system type: macOS
* Operating system version: 10.12.2
* BLT version: 8.6.6

When I run this command:
```
composer update acquia/blt --with-dependencies
```

I get the following:

  - All my additions to `.gitignore` are removed.

And I expected this to happen:

  - My additions (e.g. theme-related paths and files) should remain.

I have two .gitignore additions that I need to make sure developers don't accidentally commit theme-related things to our repo:

```
prepros.cfg
docroot/themes/custom/project_theme/css/*
```

Is there a different way we should manage `.gitignore` customizations for the project? Or is it a bug that BLT is overwriting these changes?

**Comment by bobbygryzynger** [comment] 2017-01-05 16:10
I can confirm I'm seeing this issue as far back a version `8.6.3`.

**Comment by grasmash** [comment] 2017-01-06 04:11
This is a great question. 

We need BLT to be able to update your .gitignore, because it periodically will add, remove, or move a file that needs to be ignored. I think there are 3 possible options:

1. Don't overwrite .gitignore and rely on devs to manually apply required updated.
2. Overwrite .gitignore automatically and require devs to manually revert undesired removals (current state)
3. Find a way to selectively update the .gitignore file. I'm not sure how feasible this is given that .gitignore does not contain structured data.

I'm open to suggestions for #3.

**Comment by dpagini** [comment] 2017-01-06 15:14
Spit-balling a little here... what if projects could add a `blt/files/gitignore-additions.txt` file (or where-ever, configurable in project.yml) for custom additions? This file would then be tacked onto the end of the `template/.gitignore` file from BLT.

I see two problems with this approach... 
1. You are going to have your custom entries in two places committed to your repo, and that makes me dislike this solution.
1. You would have to run a command after adding your additions to the text file to have it update the .gitignore file.

Alternatively, is there anyway `template/.gitignore` could add a section like the below, and then when it copies new changes in, parse this section and below, and preserve it on updates?
```
# Custom BLT .gitignore entries below this line only
# ************************************************** 
```

**Comment by grasmash** [comment] 2017-01-09 15:33
@dpagini One issue with that approach is that users would be unable to *remove* or override a default provided by BLT.

**Comment by dpagini** [comment] 2017-01-09 16:22
Given these in `.gitignore`:
```
# Ignore build artifacts
/deploy
bin/*
tmp
reports
```
If I wanted the _reports/_ folder... as long as the customization come later in the list, couldn't I do...
```
# Ignore build artifacts
/deploy
bin/*
tmp
reports
# ------------
!reports
```

That seems to work locally for me.

**Comment by geerlingguy** [comment] 2017-01-16 16:08
I just noticed `.gitattributes` is also reverted—I had to add `.woff` (in addition to `.woff2`) to make sure font files were treated like binaries correctly.

**Comment by grasmash** [comment] 2017-02-17 16:56
I'm removing the bug label. This works as design. It'd be nice to design it better. I think @dpagini's approach may work.

**Comment by dgpalmer** [comment] 2017-03-15 01:00
i am also experiencing this with my blt project

**Comment by mike-potter** [comment] 2017-03-16 15:12
Certainly if the .gitignore, .gitattributes, etc files do not exist (first time install) it is useful to get them as examples.  But during an "update" process I also do not want these files overwritten.  Perhaps if a file exists it can create a "changes" file, like gitignore-changes, gitattribute-changes, etc that might help.

This isn't just an issue with .gitignore.  It's an issue with ANY file that BLT wants to overwrite during the update (like .gitattributes).  Would be good to find a more general solution.

Often other projects use something like "gitignore.example" for stuff like this.

**Comment by grasmash** [comment] 2017-03-17 01:16
@mike-potter are you sure this is happening with `.gitattributes`? If so, that is unintended. Any file listed here should only be copied over if they do not exist: https://github.com/acquia/blt/blob/8.x/scripts/blt/ignore-existing.txt

**Comment by mike-potter** [comment] 2017-03-17 12:24
You are correct about the ignore-existing.txt.  It didn't overwrite .gitattributes when I tried it again.  It's possible I had deleted the previous file and not noticed (since it's in my gitignore).

I think the proposal sounds good.  Certainly cleaning up the main dir would be a nice side-benefit (stuff like drush.wrapper).  

Not sure about "hooks".  Isn't that the folder where I add my own scripts for Acquia web-hooks?  Wouldn't want that in vendor.  

Otherwise the proposal sounds good.

**Comment by dgpalmer** [comment] 2017-03-17 18:06
+1 on what Mike said.

**Comment by bobbygryzynger** [comment] 2017-03-17 18:11
@mike-potter, @grasmash is referring to BLT's own [update hook mechanism](https://github.com/acquia/blt/blob/8.x/src/Update/Updates.php).

**Comment by grasmash** [comment] 2017-03-22 17:25
Requirements:

- [ ] Move as much as possible into the `vendor` dir. I believe we can use "includes" to essentially move the logic for the following files into the `vendor` dir:
    * drush.wrapper
    * drush/drushrc.php
    * drush/policy.drush.inc
- [ ] Follow the "copy if they don't already exist" approach for all remaining files by adding new lines to [ignore-existing.txt](https://github.com/acquia/blt/blob/8.x/scripts/blt/ignore-existing.txt)
- [ ] Use [update hooks](https://github.com/acquia/blt/blob/8.x/src/Update/Updates.php#L38) to non-destructively update other files as needed. E.g., adding or removing specific lines to/from .gitignore.

**Closed** 2017-03-28 19:15 UTC
Labels: enhancement, in progress

**Comment by dpagini** [comment] 2017-03-28 19:35
@grasmash I'm not sure this issue should be closed... I'm having a hard time seeing how #1261 aligns with the original reported issue? Maybe this was closed in error?

**Comment by malikkotob** [comment] 2017-03-28 20:03
@dpagini The work on this one ended up getting split into several PRs as we explored the best route to take with some of the files mentioned above:
https://github.com/acquia/blt/pull/1253
https://github.com/acquia/blt/pull/1256
https://github.com/acquia/blt/pull/1261
https://github.com/acquia/blt/pull/1265

In summary:
- .gitignore was added to the ignore-existing.txt file, should not longer be overwritten on upgrade
- drush/policy.drush.inc was moved into the vendor directory
- A copy of the `drushrc.php` file was moved into the vendor directory, and the `drushrc.php` under `drush` was reduced to a few lines, one of which is a statement to "include" the `drushrc.php` living in the vendor directory
-  `drush/drushrc.php` was added to the ignore-existing.txt file, should no longer be overwritten on upgrade
- `drush.wrapper` remained in its current location, as there are some [complexities with the current drush setup](https://github.com/drush-ops/drush/issues/2699) that should probably be addressed prior to introducing an additional complexity

**Comment by dpagini** [comment] 2017-03-28 20:47
ah, gotcha! thanks @malikkotob! thanks for all your work on it as well!
