### ISSUE TITLE
Twig template code sniffing 

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#661] opened 2016-11-12 22:30 UTC
One feature that I'd like to see added to BLT is a Twig code sniffing utility (if such a thing exists). A quick Google search didn't turn much up, but perhaps there's one out there in the wild?

**Comment by grasmash** [comment] 2016-11-14 14:49
This is a duplicate of https://github.com/acquia/blt/issues/44

**Closed by grasmash** 2016-11-14 14:49 UTC
Labels: duplicate
