### ISSUE TITLE
Stopping 'blt sync' leaves the tmp.target.sql file in place that future runs of 'blt sync' fail on import.

### ISSUE THREAD

**Issue by adamfchs** [acquia/blt#3279] opened 2018-12-05 18:55 UTC
My system information:
* Operating system type: MacOS 
* Operating system version: High Sierra 10.13.6
* BLT version: 9.2.0-alpha3

Output of `blt doctor`:
```
source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Generating autoload files
> blt:init:settings
Hash salt already exists.
> drupal:sync:db
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/mndor/vendor/bin/drush cache-clear drush --no-interaction --ansi &&
/var/www/mndor/vendor/bin/drush sql-drop --no-interaction --ansi &&
/var/www/mndor/vendor/bin/drush sql-sync @mndor.dev @self --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --no-interaction --ansi &&
/var/www/mndor/vendor/bin/drush sql-sanitize --no-interaction --ansi &&
/var/www/mndor/vendor/bin/drush cr --no-interaction --ansi &&
/var/www/mndor/vendor/bin/drush sqlq "TRUNCATE cache_entity" --no-interaction --ansi in /var/www/mndor/docroot
[notice] Missing database table: key_value
[success] 'drush' cache was cleared.
You will destroy data in drupal and replace with data from staging-28950.prod.hosting.acquia.com/mndordev.
[notice] Starting to create database on target.
Creating database drupal. Any existing database will be dropped!

// Do you really want to continue?: yes.

[notice] Starting to dump database on source.
[success] Database dump saved to /home/mndor/drush-backups/mndordev/20181205173642/mndordev_20181205_173642.sql.gz
You will delete files in /tmp/tmp.target.sql.gz and replace with data from mndor.dev@staging-28950.prod.hosting.acquia.com:/home/mndor/drush-backups/mndordev/20181205173642/mndordev_20181205_173642.sql.gz

// Do you want to continue?: yes.

[notice] Copying dump file from source to target.
[notice] Starting to import dump file onto target database.
[error]  Failed to decompress input file.

In SqlCommands.php line 184:

 Query failed.


sql:query [--result-file [RESULT-FILE]] [--file FILE] [--extra EXTRA] [--db-prefix] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<query>]
```

Running
```
rm /tmp/tmp.target.sql /tmp/tmp.target.sql.gz
```
and then
```
blt sync
```
solves, but without having an Acquia Architect guide me through that, there is no way I would have known what the exact issue is or how to solve.

Maybe a documentation update or adding a check for that to sync and a removal if it is there before trying to do the import would be a good idea?

**Comment by lems3** [comment] 2018-12-07 18:41
Same on the Ubuntu Linux subsystem for windows 10.

**Comment by danepowell** [comment] 2019-03-21 20:54
I cannot reproduce this using BLT 9.2.4 and Drush 9.5.2. Can you provide steps to reproduce?

I ran `touch /tmp/tmp.target.sql.gz` followed by `blt sync:refresh` and Drush had no qualms about overwriting the existing /tmp/tmp.target.sql.gz.

If there is a problem here, I suspect it's not with BLT. BLT is simply calling `drush sql:sync --target-file=/tmp/tmp.target.sql.gz`, so maybe Drush needs to overwrite existing target files (and maybe it already does this in newer versions).

**Comment by malikkotob** [comment] 2019-03-22 13:50
@danepowell I _believe_ the key file that was problematic was `/tmp/tmp.target.sql`, and not the zipped version, but I can't recall right now. A quick test might be to run `touch /tmp/tmp.target.sql` before your sync, instead.

**Comment by danepowell** [comment] 2019-03-22 19:35
I think this is better fixed in Drush: https://github.com/drush-ops/drush/pull/4011

**Comment by malikkotob** [comment] 2019-03-22 20:01
Agreed, @danepowell. Thank you for digging into this.

**Comment by danepowell** [comment] 2019-03-22 20:46
This has been fixed upstream in Drush. Note that you'll need a dev version of Drush to actually use the fix right now, BLT isn't going to patch this for you.

**Closed by danepowell** 2019-03-22 20:46 UTC
Labels: question / support
