### ISSUE TITLE
Improve blt alias support for Acquia Cloud

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#2972] opened 2018-07-25 09:44 UTC
In #2896 `blt` alias support for Acquia Cloud was introduced. After playing with it on BLT 9.1.0 I noticed it doesn't exactly work as anticipated:

* Invoking `./vendor/acquia/blt/bin/blt alias` from within the project root doesn't provide the `blt()` function in one go. You have to first run it to create the `~/.bash_profile` file and then run it again to populate it with the function.
* More importantly, you have to source `~/.bash_profile` always upon logging into a server via SSH

It seems one way we could work around that would be through creating OR modifying an already-existing `.bashrc` file and add something like:

```
if [ -f ~/.bash_profile ]; then
  . ~/.bash_profile
fi
```

**Comment by ba66e77** [comment] 2018-07-29 15:05
The [getCliConfigFile method](https://github.com/acquia/blt/blob/d8b0085014962a3ad8a8c04fc6fc0d03606cf051/src/Robo/Inspector/Inspector.php#L485), which the alias command uses, looks for a set of settings files in a given order and returns the first one it finds. If the ~/.bash_profile doesn't exist but ~/.bashrc _does_ then it should write the alias to the ~/.bashrc file. 

Does the .bashrc file you're referring to not live in the user's home dir? If it doesn't live in their home directory, is the user able to write to it (and _should_ we write to it even if we can)?

```
    if (strstr(getenv('SHELL'), 'zsh')) {
      $file = $home_dir . '/.zshrc';
    }
    elseif (file_exists($home_dir . '/.bash_profile')) {
      $file = $home_dir . '/.bash_profile';
    }
    elseif (file_exists($home_dir . '/.bashrc')) {
      $file = $home_dir . '/.bashrc';
    }
    elseif (file_exists($home_dir . '/.profile')) {
      $file = $home_dir . '/.profile';
    }
    elseif (file_exists($home_dir . '/.functions')) {
      $file = $home_dir . '/.functions';
    }
```

**Comment by lcatlett** [comment] 2018-07-29 15:36
the config `.bashrc` is only read from a shell that is interactive and non-login so I think the standard way to work around the issues in this thread is to force a read of .bashrc in .bash_profile (if it exists). You would add something like `[[ -r ~/.bashrc ]] && . ~/.bashrc` to .bash_profile, that way every time there is a login then the alias is also loaded for the interactive prompt. I can put in a PR when I get a moment because should also be invoked via the .shell script on Acquia so that blt runs as the unix user that also "runs" the Cloud Hooks and drush commands on deploy/update and not the ssh user

**Comment by anavarre** [comment] 2018-07-29 20:06
> Does the .bashrc file you're referring to not live in the user's home dir?

To my recollection, `.bashrc` doesn't exist by default on Acquia Cloud. One solution could be to create it if it doesn't.

**Comment by ba66e77** [comment] 2018-07-30 00:46
Ok. So I'm thinking we should update the [installBltAlias()](https://github.com/acquia/blt/blob/d8b0085014962a3ad8a8c04fc6fc0d03606cf051/src/Robo/Commands/Blt/AliasCommand.php#L21) method so that, if it has to create the .bash_profile file, it then goes on to write the alias into it and source the file. That will address the first of the issues @anavarre raised.

After the .bash_profile file is created and the alias written into it, if the file still has to be sourced on every login then i think that's a problem outside the scope of this project.

@lcatlett, I'm afraid I'm not following your note about the .shell script. Can you point me to documentation on that?

**Comment by lcatlett** [comment] 2018-08-05 15:16
I'm not sure that there is extensive public documentation on the env.shell scripts, but you can see their invocation in the Acquia Cloud logs each time a Cloud Hook is executed: 

```
[2018-08-03 21:32:15] Starting hook: post-code-deploy

[2018-08-03 21:32:18] Executing: /mnt/users/sandbox/prod.shell /var/www/html/sandbox.prod/hooks/common/post-code-deploy/post-code-deploy.sh sandbox prod tags/v1.0.0 tags/v1.0.0 sandbox@svn-1246.enterprise-g1.hosting.acquia.com:sandbox.git git < /dev/null (as sandbox.prod@web-1270})
```
Every Acquia web has a .shell in `/mnt/users/[site_group]/[env].shell` that should be run before any script that needs to be contextually aware of the current process environment, particularly if you are running that script from the cli as opposed to cron etc. since there can be multiple user and sites on a single web. 

This is related to resolving the issues mentioned in    https://github.com/acquia/blt/issues/2957#issuecomment-406494502

**Comment by danepowell** [comment] 2019-03-15 19:16
I agree with Barrett's analysis. I'll work on a PR to create `.bash_profile` and source it in a single run. But I can't reproduce Aurelien's second issue of `.bash_profile` not being sourced automatically on SSH logins. When I SSH into my sites with `drush @foo.dev ssh`, it sources `.bash_profile` automatically.

**Closed** 2019-03-15 23:55 UTC
Labels: enhancement
