### ISSUE TITLE
9.x Branch Features Issue w/ Composer

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2509] opened 2018-02-01 18:14 UTC
My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 9 Beta 2

When I run this command:
```
composer update
```

I get the following output:
```
The requested package drupal/features (locked at 3.5.0, required as 3.x-dev#2e82a6ad751fc88f771be5b4e53b98a8c6eb66b5) is satisfiable by drupal/features[3.5.0] but these conflict with your requirements or minimum-stability.
```

And I expected this to happen:
This isn't happening 100% of the time. However if I get into an off state with composer (e.g. failed patch, etc.) and then I try to run again, I hit the above error and have to rm the composer.lock and vendor files to get out of it again.

Is anyone else running into this?

**Comment by grasmash** [comment] 2018-02-02 22:02
Yeah I don't think there's much to be done about this. If your composer update fails midway through and leaves your vendored dirs in a corrupt state, you'll need to `composer run-script nuke` and try again after resolving the root cause.

**Closed by grasmash** 2018-02-02 22:02 UTC
Labels: question / support
