### ISSUE TITLE
Build Issue on Server

### ISSUE THREAD

**Issue by debdatta-sarkar** [acquia/blt#2373] opened 2017-12-13 12:48 UTC
<img width="776" alt="test environment drush error" src="https://user-images.githubusercontent.com/30872298/33939672-08e66938-e032-11e7-9546-2e88ad3be721.png">
On one of the environments whenever I try to deploy the code am getting these errors.

 ``````````````
"ttttt-5555] - |waitForVcsUpdateTask| -> "fail" -> |deployVcsOnUpdateSite| : maximum attempts exceeded; (max attempts: 2)"
 ``````````````
and
 ``````````````
"[ttttt-5555] - Acquia\SfUpdate\DocrootUpdate:4216 - failed to move from state "waitForVcsUpdateTask", defaulting to failed state. Message: Maximum transitions for waitForVcsUpdateTask->*->deployVcsOnUpdateSite has been exceeded."
Before that I see -"[ttttt-5555] - Checking hosting task 10523671; stdClass Object
([id] => 10523671[queue] => code-push[state] => failed[description] => Deploy code to 01testup[created] => 1513081080[started] => 1513081082[completed] => 1513081098[sender] => c69aeece-7c49-4b69-811a-69047ab2896d[result] =>[cookie] =>[logs] => [12:18:02] [12:18:02] Started[12:18:18] [2017-12-12 12:18:06] cxxxxxxxxa.01testup: updating web_servers[ttttt-5555].Updating cxxxxxxxxa.01testup to deploy release/1.0-buildDeploying release/1.0-build on cxxxxxxxxa.01testup[2017-12-12 12:18:10] Starting hook: post-code-deploy[2017-12-12 12:18:11] Executing: /mnt/users/cxxxxxxxxa/01testup.shell /var/www/html/cxxxxxxxxa.01testup/hooks/common/post-code-deploy/post-code-deploy.sh cxxxxxxxxa 01testup release/1.0-build release/1.0-build cxxxxxxxxa@sss-ss.enterprise-g1.hosting.acquia.com:cxxxxxxxxa.git git < /dev/null (as cxxxxxxxxa.01testup@staging-1433})Running updates for environment: 01testup[00;36m [property] Loading /mnt/www/html/cxxxxxxxxa01testup/blt/project.yml[0m[00;32mblt > deploy:update:[0m[00;36m [property] Loading /mnt/www/html/cxxxxxxxxa01testup/blt/project.yml[0m[00;32mblt > deploy:update:site:[0m[00;36m [echo] Deploying upda...testup/vendor/acquia/blt/phing.[0m[01;31m[phingcall] /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/setup.xml:183:8: /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/setup.xml:201:68: Drush exited with code 1[0m[01;31m [foreach] /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/deploy.xml:312:37: Execution of the target buildfile failed. Aborting.[0m[01;31mBUILD FAILED/mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/deploy.xml:307:91: Execution of the target buildfile failed. Aborting.; 5.1955 seconds[0mUpdate errored for site demo.test-cxxxxxxxxa.acsitefactory.com.[2017-12-12 12:18:17] Finished hook: post-code-deploy[2017-12-12 12:18:18] Sending webhook hook: 'post-code-deploy' revision: ''![2017-12-12 12:18:18] WARN: Command returned exit code 1: /mnt/users/cxxxxxxxxa/01testup.shell /var/www/html/cxxxxxxxxa.01testup/hooks/common/post-code-deploy/post-code-deploy.sh cxxxxxxxxa 01testup release/1.0-build release/1.0-build cxxxxxxxxa@sss-ss.enterprise-g1.hosting.acquia.com:cxxxxxxxxa.git git executing hook post-code-deployzlib(finalizer): the stream was freed prematurely.[requestStatus] => 200[retryLog] => Array()[failureState] => 1)"
``````````````
I have tried to revert back to old site back ups but am still facing this issue. I has raised a ticket on Acquia but they said:
Yes, as you can see, the execution of the target buildfile failed (failed wip task log attached):
 ``````````````
DEBUG 2017-12-12T12:18:22+00:00 [1513081102]
[ttttt-5555] - Checking hosting task 10523671; stdClass Object
(
    [id] => 10523671
    [queue] => code-push
    [state] => failed
    [description] => Deploy code to 01testup
    [created] => 1513081080
    [started] => 1513081082
    [completed] => 1513081098
    [sender] => c69aeece-7c49-4b69-811a-69047ab2896d
    [result] => 
    [cookie] => 
    [logs] => [12:18:02] [12:18:02] Started
[12:18:18] [2017-12-12 12:18:06] cxxxxxxxxa.01testup: updating web_servers[ttttt-5555].
Updating cxxxxxxxxa.01testup to deploy release/1.0-build
Deploying release/1.0-build on cxxxxxxxxa.01testup
[2017-12-12 12:18:10] Starting hook: post-code-deploy
[2017-12-12 12:18:11] Executing: /mnt/users/cxxxxxxxxa/01testup.shell /var/www/html/cxxxxxxxxa.01testup/hooks/common/post-code-deploy/post-code-deploy.sh cxxxxxxxxa 01testup release/1.0-build release/1.0-build cxxxxxxxxa@sss-ss.enterprise-g1.hosting.acquia.com:cxxxxxxxxa.git git < /dev/null (as cxxxxxxxxa.01testup@ttttt-5555})
Running updates for environment: 01testup
�[00;36m [property] Loading /mnt/www/html/cxxxxxxxxa01testup/blt/project.yml�[0m
�[00;32mblt > deploy:update:�[0m
�[00;36m [property] Loading /mnt/www/html/cxxxxxxxxa01testup/blt/project.yml�[0m
�[00;32mblt > deploy:update:site:�[0m
�[00;36m     [echo] Deploying upda...testup/vendor/acquia/blt/phing.�[0m
�[01;31m[phingcall] /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/setup.xml:183:8: /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/setup.xml:201:68: Drush exited with code 1�[0m
�[01;31m  [foreach] /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/deploy.xml:312:37: Execution of the target buildfile failed. Aborting.�[0m
�[01;31m
BUILD FAILED/mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/deploy.xml:307:91: Execution of the target buildfile failed. Aborting.
; 5.1955 seconds�[0m
Update errored for site demo.test-cxxxxxxxxa.acsitefactory.com.
[2017-12-12 12:18:17] Finished hook: post-code-deploy
 
[2017-12-12 12:18:18] Sending webhook hook: 'post-code-deploy' revision: ''!
[2017-12-12 12:18:18] WARN: Command returned exit code 1: /mnt/users/cxxxxxxxxa/01testup.shell /var/www/html/cxxxxxxxxa.01testup/hooks/common/post-code-deploy/post-code-deploy.sh cxxxxxxxxa 01testup release/1.0-build release/1.0-build cxxxxxxxxa@sss-ss.enterprise-g1.hosting.acquia.com:cxxxxxxxxa.git git executing hook post-code-deploy
zlib(finalizer): the stream was freed prematurely.
 
    [requestStatus] => 200
    [retryLog] => Array
        (
        )
 
    [failureState] => 1
)
Specifically, /mnt/www/html/cxxxxxxxxa01testup/./vendor/acquia/blt/phing/tasks/deploy.xml, and as a result the post-code-deploy script failed:
WARN: Command returned exit code 1: /mnt/users/cxxxxxxxxa/01testup.shell /var/www/html/cxxxxxxxxa.01testup/hooks/common/post-code-deploy/post-code-deploy.sh cxxxxxxxxa 01testup release/1.0-build release/1.0-build cxxxxxxxxa@sss-ss.enterprise-g1.hosting.acquia.com:cxxxxxxxxa.git git executing hook post-code-deploy
zlib(finalizer): the stream was freed prematurely.
 
    [requestStatus] => 200
    [retryLog] => Array
        (
        )
 
    [failureState] => 1
 ``````````````
 ``````````````
For easier review, I have attached the contents of deploy.xml and below is post-code-deploy.sh:
#!/bin/bash
#
# Cloud Hook: post-code-deploy
#
# The post-code-deploy hook is run whenever you use the Workflow page to
# deploy new code to an environment, either via drag-drop or by selecting
# an existing branch or tag from the Code drop-down list. See
# ../README.md for details.
#
# Usage: post-code-deploy site target-env source-branch deployed-tag repo-url
#                         repo-type
 
site="$1"
target_env="$2"
source_branch="$3"
deployed_tag="$4"
repo_url="$5"
repo_type="$6"
 

  . /var/www/html/$site.$target_env/vendor/acquia/blt/scripts/cloud-hooks/functions.sh
  deploy_updates
  # Send notifications to Slack, if configured. See readme/deploy.md for setup instructions.
  . `dirname $0`/../slack.sh
 ``````````````
Kindly help me with resolving
[task_4216_2017_12_12.log](https://github.com/acquia/blt/files/1555509/task_4216_2017_12_12.log)
 this issue.

**Comment by grasmash** [comment] 2017-12-13 15:50
What BLT version is this?

**Comment by grasmash** [comment] 2017-12-13 16:04
It looks like you're running ACSF and your post-code-deploy cloud hook is failing when executing `deploy:update`.

If I had to guess, I'd say the most likely cause is an issue with your application's configuration.
Unfortunately your log isn't providing enough detail to pinpoint the issue. The first thing I'd try in order to debug this issue would be to attempt to reproduce this issue on your local machine by executing `blt setup:update`.

The other option is to upgrade BLT. Newer versions of BLT are better at reporting the underlying problem. However, your version of BLT looks very out-of-date and the upgrade effort may be significant.

Cloud hooks for ACSF have been recently deprecated and use of them is now discouraged.

@lcatlett @danepowell Can you elaborate on the state of this?

**Comment by danepowell** [comment] 2017-12-13 21:28
I can only confirm that using Cloud Hooks on ACSF is no longer considered best practice, and may cause a lot of problems, especially for subscriptions with large numbers of sites. @lcatlett can comment on the newer preferred ACSF hooks.

The logs seem incomplete, but this looks like exactly the kind of problem that can occur when running cloud hooks on ACSF, because of inconsistencies between the live and update environments.

**Comment by lcatlett** [comment] 2017-12-14 17:14
@debdatta-sarkar it looks like you are running into a few issues. You should first update BLT to the latest release supported on ACSF (8.9.11) which will modify the way BLT deploys to ACSF and runs updates. It appears that you are still using the post-code-deploy and post-code-update Cloud Hooks which are now unsupported and not recommended on ACSF and may result in deploy errors like the one you see since the hooks are being executed on your update environment, which is technically your live sites when ACSF is running its deploy / update tasks. 

For tag deploys you should instead use Factory Hooks which have recently been added to BLT 9.1.x via this PR: https://github.com/acquia/blt/pull/2227. You'll also want to ensure that the scripts executed by Cloud Hooks in your codebase have the recommended updates per https://github.com/acquia/blt/blob/9.1.x/scripts/cloud-hooks/functions.sh and that your post-code-deploy scripts are updated as well: https://github.com/acquia/blt/blob/9.1.x/scripts/cloud-hooks/hooks/common/post-code-deploy/post-code-deploy.sh.

**Comment by AshwinParmar** [comment] 2017-12-15 08:02
Can you please upload whole log file. and Steps have you follow.

**Comment by debdatta-sarkar** [comment] 2017-12-15 10:00
@AshwinParmar : Its the complete log.

The steps executed: Deployment of any tag version on test environment.

**Comment by grasmash** [comment] 2017-12-20 16:26
I'm closing this issue given that clear recommendations have been made for a path forward. Please open new issues if you have trouble implementing a given suggestion.

**Closed by grasmash** 2017-12-20 16:26 UTC
Labels: question / support
