### ISSUE TITLE
BLT Plan for switching to Ubuntu 16.04LTS (Xenial) in Travis?

### ISSUE THREAD

**Issue by ericchenshine** [acquia/blt#1848] opened 2017-07-28 03:58 UTC
As the server OS has been upgraded from Trusty to Xenial in Acquia cloud in the last a couple of months, so we want to line up the OS version in Travis-CI to Xenial as well. It looks like the only way to use Xenial in Travis is by running a docker with Xenial image. We are wondering if BLT has any plan on it?

**Comment by grasmash** [comment] 2017-07-31 16:49
We likely will not upgrade Travis to Xenial until it is provided as a stock distribution. I believe that @geerlingguy has worked on transitioning BLT to use a doctor image for its Travis builds, but that is not on the main roadmap.  However, I would be happy to merge in such a change.

@geerlingguy, where does that work stand?

**Comment by geerlingguy** [comment] 2017-07-31 16:59
I had a bit of it working correctly, but ran into a few blockers during my first go at it.

The most efficient way to maintain it, I think, would be to set up a BLT image on Docker Hub, so that builds could pull that image and run right away. This would prevent us from having to do some of the setup work (so builds would go faster), and we would be able to have a stable and standard test rig to run the site tests on (right now we're kind of at Travis CI's mercy when they make changes to their environment).

If possible, I'd like to pick that back up at some point, I just haven't had the time lately :/

**Comment by grasmash** [comment] 2017-08-03 14:34
Since the only way to implement this at the moment is to build a docker image for BLT, I am going to close this issue as a duplicate of #1366.

**Closed by grasmash** 2017-08-03 14:34 UTC
Labels: enhancement
