### ISSUE TITLE
"tests" commands suppress color output

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1429] opened 2017-04-25 01:34 UTC
Behat and PHPUnit emit red/green colored output that makes errors super easy to spot, even when skimming a long backscroll. Unfortunately, BLT swallows the color codes and reduces their output to undifferentiated white. Can we modify to preserve colored output?

**Comment by grasmash** [comment] 2017-04-25 03:25
I believe this is already fixed in 8.x.

**Comment by grasmash** [comment] 2017-04-25 15:02
Duplicate of #1420

**Closed by grasmash** 2017-04-25 15:02 UTC
Labels: bug, duplicate
