### ISSUE TITLE
Create Docs for installing Lightning with BLT

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#2312] opened 2017-11-28 21:46 UTC
Currently the Acquia docs for installing Lightning (https://docs.acquia.com/lightning/install) do not list instructions on installing it with BLT even though it is the preferred installation method. A BLT docs page needs to be created to that the docs.acquia page can reference so customers know it is the recommended method.

**Comment by danepowell** [comment] 2017-11-29 16:56
This sounds like a dupe of #1131, unless you're proposing that we modify the Lightning docs page? Let me know what you think.

**Closed** 2017-12-05 21:31 UTC
