### ISSUE TITLE
False positive suspected with BLT 9.2.6 and Acquia Pipelines

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#3526] opened 2019-04-08 13:02 UTC
Upon trying to update to BLT 9.2.6, Acquia Pipelines fails with the following:

```
blt deploy:check-dirty --ansi --verbose

[error]  There are uncommitted changes, commit or stash these changes before deploying.
```

Running the same command locally (against the _same_ Git branch) works as expected since the working tree is clean:

```
$ git status
On branch blt-9.2.6
Your branch is ahead of 'origin/master' by 1 commit.
(use "git push" to publish your local commits)
nothing to commit, working tree clean
$ blt deploy:check-dirty --ansi --verbose
0.088s total time elapsed.
```

-----
I understand there's a way to temporarily disable the command with BLT's `blt.yml`'s `disable-targets` but haven't yet found a way to do so reliably.

**Comment by danepowell** [comment] 2019-04-08 15:43
Running the command locally won't have the same effect since there are lots of things in the Pipelines scripts that only run on Pipelines. For instance, if you've applied this PR, it would cause this error: https://github.com/acquia/blt/pull/3525

You'll need to add a `git status` to your Pipelines scripts to figure out what exactly has uncommitted changes. Maybe that's something BLT could do for you in the long-run.

**Comment by danepowell** [comment] 2019-04-09 00:38
This should help you figure out what changed: https://github.com/acquia/blt/pull/3531

**Comment by anavarre** [comment] 2019-04-10 06:03
@danepowell thanks for #3531 - Applied the patch and that's really helpful to understand what's going on, though I can't explain _why_ those files are there.

**Comment by danepowell** [comment] 2019-04-10 17:28
If you still need more support, please post the output of the checkDirty command so we can see what files changed.

**Comment by anavarre** [comment] 2019-04-10 18:14
Sure, here's the output:

```
blt deploy:check-dirty --ansi --verbose

 M docroot/sites/default/settings.php
 M docroot/sites/glossary.acquia.com/settings.php
 M docroot/sites/ls.acquia.com/settings.php
?? docroot/sites/default/settings/default.includes.settings.php
?? docroot/sites/glossary.acquia.com/settings/default.includes.settings.php
?? docroot/sites/ls.acquia.com/settings/default.includes.settings.php
?? docroot/sites/settings/

[error]  There are uncommitted changes, commit or stash these changes before deploying.
```

**Comment by danepowell** [comment] 2019-04-10 18:27
I pinged @anavarre via Slack, it turns out this is most likely a dupe of https://github.com/acquia/blt/issues/3496

BLT's settings includes were not committed to Git and thus being re-written as part of the deploy process.

I'm still like to understand why that is, in case there's a documentation / training / some other gap on our part.

**Comment by wu-edward** [comment] 2019-04-15 17:58
FYI, I ran into a similar issue, but the modified file was the `package-lock.json` in the projects' custom theme, which is a [Cog ](https://github.com/acquia-pso/cog) subtheme.
In `blt.yml`, we have this:
```
command-hooks:
  frontend-reqs:
    dir: '${docroot}/themes/custom/dxp_front'
    command: 'npm run install-tools'
  ...
```
And in the theme's `package.json`, we have this:
```
  "scripts": {
    ...
    "install-tools": "npm install",
    ...
  },
```
`npm install` can clobber `package-lock.json` unpredictably.

Changing the value of `install-tools` to `npm ci` in `package.json` seems to resolve the problem.

**Comment by mikemadison13** [comment] 2019-04-17 23:04
I'm currently hitting this as well after updating to 9.2.6. Unclear what precisely is causing it for me.

**Comment by danepowell** [comment] 2019-04-22 22:56
@wu-edward thanks for the report, and for pointing out `npm ci`, I wasn't aware of that but it definitely sounds like best practice.

NPM is notorious for problems like that and I don't think BLT should ditch the advantages of checking for dirty commits just to accommodate NPM, but maybe we can add that tip to a FAQ in https://github.com/acquia/blt/issues/3564

**Comment by danepowell** [comment] 2019-04-22 22:59
Closing this in favor of https://github.com/acquia/blt/issues/3564 , which should provide some support to folks impacted by this getting turned on for Pipelines.

**Closed by danepowell** 2019-04-22 22:59 UTC
Labels: Support

**Comment by mikemadison13** [comment] 2019-05-02 19:03
just a random note, `npm ci` isn't available in older versions of NPM. i had to upgrade my npm version inside my vm before I could use it!

**Comment by mikemadison13** [comment] 2019-05-09 13:52
another random note here, the check dirty command will _fail_ if the file permissions are out of sync. i am not convinced that we shouldn't ignore file permissions @danepowell when we do this... it took me an hour to figure out that was the problem.
