### ISSUE TITLE
Upgrade BLT to use Drupal 8.4.0

### ISSUE THREAD

**Issue by fiasco** [acquia/blt#2155] opened 2017-10-18 22:14 UTC
My system information:
* Operating system type: Mac OS
* Operating system version: 10.12.6
* BLT version: 8.3

When I run this command:
```
composer require drupal/core:8.4.0
```

I get the following output:
```
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating symfony/class-loader (v3.2.13 => v3.3.10) Loading from cache
Writing lock file
Generating autoload files
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/core 8.4.0 -> satisfiable by drupal/core[8.4.0].
    - Conclusion: remove symfony/config v3.3.10
    - Conclusion: don't install symfony/config v3.3.10
    - drupal/core 8.4.0 requires symfony/dependency-injection ~3.2.8 -> satisfiable by symfony/dependency-injection[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - symfony/dependency-injection 3.2.x-dev conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.10 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.11 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.12 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.13 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.8 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.9 conflicts with symfony/config[v3.3.10].
    - Installation request for symfony/config (locked at v3.3.10) -> satisfiable by symfony/config[v3.3.10].
```

And I expected this to happen:
BLT should be running with 8.4.0 rather than 8.4.0-rc2. It'd be nice if BLT could use a version of symfony that aligned with the used version in Drupal 8.x

Solution is to remove composer.lock file which is less than ideal.

**Comment by grasmash** [comment] 2017-10-18 22:55
BLT does use a version of Symfony that aligns with Drupal 8.4.

The command that you ran will attempt to download Drupal 8.4 while keeping the version of Symfony currently locked for your application. That is specific to your site, not BLT. BLT only defines a minimum compatible version, which is c
aligns with the minimum required version for Drupal 8.4.

You should use the —with-dependencies or —update-with-depdendencies when you execute composer commands so that recursive package depdencies can be resolved.

**Comment by fiasco** [comment] 2017-10-18 23:46
So if I follow the docs here: http://blt.readthedocs.io/en/8.x/readme/creating-new-project/

After I run `composer create-project --no-interaction acquia/blt-project my-project` (which loads 8.9.9) then Drupal 8.4.0-rc2 is installed. Leaving me with the challenge of upgrading to 8.4.0. So per your suggestion, I try using `--update-with-dependencies`

```
$ composer require drupal/core:8.4.0 --update-with-dependencies
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/core 8.4.0 -> satisfiable by drupal/core[8.4.0].
    - Conclusion: remove symfony/config v3.3.10
    - Conclusion: don't install symfony/config v3.3.10
    - drupal/core 8.4.0 requires symfony/dependency-injection ~3.2.8 -> satisfiable by symfony/dependency-injection[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - symfony/dependency-injection 3.2.x-dev conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.10 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.11 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.12 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.13 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.8 conflicts with symfony/config[v3.3.10].
    - symfony/dependency-injection v3.2.9 conflicts with symfony/config[v3.3.10].
    - Installation request for symfony/config (locked at v3.3.10) -> satisfiable by symfony/config[v3.3.10].


Installation failed, reverting ./composer.json to its original content.
```

At this point, I have no custom code, only BLT which is my point - why is BLT making this hard?

**Comment by greylabel** [comment] 2017-10-18 23:53
@kylebrowning Seems like the same thing you were just fighting with?

**Comment by grasmash** [comment] 2017-10-19 01:02
@balsama I think you saw a similar issue with drupal/core (8.4.0-alpha1) being downloaded?

**Comment by grasmash** [comment] 2017-10-19 01:18
`composer require drupal/core:8.4.0 --no-update && composer update behat/behat drupal/core --with-dependencies`

https://github.com/composer/composer/issues/6661

**Comment by grasmash** [comment] 2017-10-19 01:23
@fiasco I can't reproduce the default download of `Drupal 8.4.0-rc2` but I can reproduce a download of Drupal 8.4.0-alpha1. The reason this can't be resolved with a variant of `composer require drupal/core:8.4.0` is composer/composer#6661.

We may be able to workaround that with https://github.com/acquia/blt/pull/2156.

**Comment by fiasco** [comment] 2017-10-19 01:25
I just rechecked my composer.lock file and confirmed `8.4.0-alpha1`

**Comment by kylebrowning** [comment] 2017-10-19 01:26
Yes. I see alpha1 as well.

**Comment by grasmash** [comment] 2017-10-19 01:28
`composer require drupal/core:8.4.0 --no-update && composer update behat/behat drupal/core --with-dependencies` will update in the mean time.

**Comment by balsama** [comment] 2017-10-19 01:32
I think this commit to Drupal (post 8.4.0-alpha1) is at the crux:
https://github.com/drupal/core/commit/298d788c5cc8526a61dc675f059c3cebd2a0e6ac#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Composer will prefer the the newer versions of all those symfony components over a stable core. I've been able to work around it by adding core to my root composer.json file (which I think BLT already does).

If that doesn't work, another possible workaround might be to constrain some symfony component directly. e.g. `symfony/class-loader": "<3.3.0"`.

**Comment by grasmash** [comment] 2017-10-19 01:55
`composer create-project acquia/blt-project:8.x-dev --no-interaction my-project` downloads Drupal 8.4.0.

**Comment by kylebrowning** [comment] 2017-10-19 22:38
So, this didnt seem to work for me.

It downloads drupal/core - 8.4.0 but once it hits the updates, it goes back to alpha1

```- Updating symfony/validator (v3.2.13 => v3.3.6): Loading from cache
  - Updating symfony/process (v3.2.13 => v3.3.6): Loading from cache
  - Updating symfony/dependency-injection (v3.2.13 => v3.3.6): Loading from cache
  - Installing drupal/core (8.4.0-alpha1): Loading from cache
  - Applying patches for drupal/core
```

**Comment by grasmash** [comment] 2017-10-20 16:47
@kylebrowning I cannot reproduce what you're describing,  but I don't quite understand what you mean by "once it hits the updates".

Here's what I ran:
```
$ composer create-project acquia/blt-project:8.x-dev --no-interaction my-project
$ cd my-project
$ composer info drupal/core | grep versions
```

It returned:
```
versions : * 8.4.0
```

**Comment by kylebrowning** [comment] 2017-10-20 16:48
This is an existing BLT project. So I'm not sure if theres a differences between create-project and just plain old `composer update`

**Comment by kylebrowning** [comment] 2017-10-20 16:48
Heres my composer.json

```json
{
    "name": "acquia/blt-project",
    "description": "Project template for Drupal 8 sites built with BLT.",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "acquia/blt": "^8.9.0",
        "cweagans/composer-patches": "^1.6.0",
        "drupal/adminimal_theme": "^1.3",
        "drupal/admin_toolbar": "^1.18",
        "drupal/adminimal_admin_toolbar": "^1.3",
        "drupal/devel": "1.x-dev",
        "drupal/cog": "^1.0.0",
        "drupal/core": "8.4.0",
        "drupal/codesnippet": "^1.6",
        "kylebrowning/codesnippet": "dev-master",
        "drush/drush": "^8.1.8",
        "drupal/google_analytics": "^2.1",
        "drupal/sharethis": "2.x-dev",
        "drupal/services": "dev-4.x",
        "drupal/honeypot": "^1.25",
        "geerlingguy/drupal-vm": "~4.3"
    },
    "config": {
        "platform": {
           "php": "7.0"
        }
    },
    "require-dev": {
        "jakoch/phantomjs-installer": "^2.1.1-p07"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "package",
            "package": {
                "name": "kylebrowning/codesnippet",
                "version": "dev-master",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/kylebrowning/codesnippet.git",
                    "type": "drupal-library"
                },
                "source": {
                    "url": "https://github.com/kylebrowning/codesnippet.git",
                    "type": "git",
                    "reference": "codesnippet"
                }
            }
        }
    ],
    "extra": {
        "blt": {
            "update": true
        },
        "enable-patching": true,
        "patches": {
            "drupal/codesnippet": {
                "updates code snippet highlight styles": "https://www.drupal.org/files/issues/0001-updates-styles-for-issue-2866176.patch"
            },
            "drupal/sharethis": {
                "php7-fix": "https://www.drupal.org/files/issues/error-config-form-2858402-1.patch",
                "nodeid-issue": "https://www.drupal.org/files/issues/2767165-fix-for-preview-3_1.patch",
                "config-form": "https://www.drupal.org/files/issues/2816573-6.patch"
            }
        },
        "installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "docroot/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ],
            "docroot/libraries/{$name}": [
                "type:drupal-library",
                "type:bower-asset",
                "type:npm-asset"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "merge-plugin": {
            "require": [
                "vendor/acquia/blt/composer.required.json",
                "vendor/acquia/blt/composer.suggested.json"
            ],
            "include": [
                "blt/composer.overrides.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": true
        },
        "installer-types": [
            "bower-asset",
            "npm-asset"
        ]
    }
}

```

**Comment by grasmash** [comment] 2017-10-20 16:51
Oh yeah, this probably has to do with your specific applications requirements. I am guessing that your version constraints are causing composer to initially download a 3.3.* version of the Symfony components.

In the case of BLT itself, this had to do with the version of Behat that was included  in `require-dev`.  you should be able to lock down your version constraints a bit more so that doesn't happen.

Are you directly requiring drupal/core:8.4.0?  That should be the simplest way.

Make sure that you define the requirements in your root composer.json file and that you have the wiki merge plug-in configured correctly:

```
    "merge-plugin": {
        "require": [
            "vendor/acquia/blt/composer.required.json",
            "vendor/acquia/blt/composer.suggested.json"
        ],
        "include": [
            "blt/composer.overrides.json"
        ],
        "merge-extra": true,
        "merge-extra-deep": true,
        "merge-scripts": true,
        "replace": false,
        "ignore-duplicates": true
    },
```

**Comment by grasmash** [comment] 2017-10-20 16:51
I am pretty sure that if you update your wiki merge plugin configuration, the issue should resolve itself.

**Comment by kylebrowning** [comment] 2017-10-20 16:52
Roger that, trying.

**Comment by kylebrowning** [comment] 2017-10-20 17:03
`  - Updating drupal/core (8.4.0-alpha1 => 8.4.0): Loading from cache`

boom! Thanks.

**Comment by grasmash** [comment] 2017-10-20 17:09
@kylebrowning Cool.

**Closed by grasmash** 2017-10-20 17:09 UTC
Labels: enhancement, in progress

**Comment by kevinquillen** [comment] 2017-10-24 18:09
I also get 8.4.0-alpha1 on a fresh install with BLT.

**Comment by kevinquillen** [comment] 2017-10-24 18:13
This worked for me, but why did it not initially download the stable release over alpha?

`composer require drupal/core:8.4.0 --no-update && composer update behat/behat drupal/core --with-dependencies`
