### ISSUE TITLE
phpcs pre-commit detects issues with css files but phpcbf doesn't fix

### ISSUE THREAD

**Issue by timwood** [acquia/blt#3034] opened 2018-08-27 19:43 UTC
My system information:
* Operating system type: Mac OS / Drupal VM
* Operating system version: High Sierra / Drupal VM 4.9.0
* BLT version: 9.1.1

Has anyone else seen inconsistency with the git pre-commit hooks, which runs phpcs (`blt tests:phpcs:sniff:all`), detecting poorly formatted CSS (why is it running against .css files at all with `<arg name="ignore" value="*.css,*.md,*.txt"/>` in phpcs.xml.dist?) but then it doesn't fix these when running `blt fix`? Even though the phpcs output suggests: `PHPCBF CAN FIX THE XX MARKED SNIFF VIOLATIONS AUTOMATICALLY`

**Comment by timwood** [comment] 2018-08-27 19:47
Removing `*.css` from the ignore list allows phpcbf to fix the poorly formatted CSS files. But it doesn't seem ideal that BLT sniff and fix commands (or maybe it's just phpcs & phpcbf) would work so inconsistently when using the same `phpcs.xml.dist` config.

**Comment by ba66e77** [comment] 2018-08-30 23:54
I think the question of why css file get picked up by the sniff is related to this comment: ttps://www.drupal.org/node/2867601#comment-12075633, so unless they were specifically excluded css would be picked up because they're explicitly included in Coder.

So would you say the way to resolve is to _start_ allowing css so that phpcbf can fix them or add them to the exclude list in `phpcs.xml.dist` so phpcs doesn't sniff them?

**Comment by timwood** [comment] 2018-08-31 14:07
Can phpcbf actually reliably fix CSS formatting or is this better off left to some theme build tool?

**Comment by danepowell** [comment] 2019-03-12 22:00
Dupe of #3448

**Closed by danepowell** 2019-03-12 22:00 UTC
Labels: 9.1.x, enhancement
