### ISSUE TITLE
Wrong Drush site URI for multisite returned from blt doctor --site=my_site

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#3786] opened 2019-07-31 17:55 UTC
**I want to...**
Run the `blt doctor --site` command and get an accurate analysis of the configuration.

**It's not working because...**
Well, I am not sure if this IS wrong, but when I run the command `blt doctor --site=naswa` it returns an error of:

```
base_url in tests/behat/local.yml does not match the site URI. 
Behat base_url is set to http://naswa.lndo.site.     //This is correct
Drush site URI is set to http://naswa. // This is incorrect and I don't understand where this comes from
```

**Detailed error output**
This is the relevant output:

```
verbose: Running ["/usr/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","naswa_appserver_1","/usr/bin/blt","doctor","--site=naswa","-vvv"] in /home/brookeheaton/Sites/naswa with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":["inherit","inherit","ignore"]}, mode=attach, detached=false, cwd=/home/brookeheaton/Sites/naswa
[debug] Drupal VM is not initialized.
[Robo\Common\ProcessExecutor] Running '/app/vendor/bin/drush' @naswa.local status --format=json --fields=* --uri=naswa in /app/docroot
{
    "drupal-version": "8.7.5",
    "uri": "http://naswa",
    "db-driver": "mysql",
    "db-hostname": "database",
    "db-port": 3306,
    "db-username": "drupal8",
    "db-password": "drupal8",
    "db-name": "drupal8",
    "db-status": "Connected",
    "bootstrap": "Successful",
    "theme": "naswa_base",
    "admin-theme": "naswa_admin",
    "php-bin": "/usr/local/bin/php",
    "php-conf": [
        false
    ],
    "php-os": "Linux",
    "drush-script": "/app/vendor/drush/drush/drush",
    "drush-version": "9.7.1",
    "drush-temp": "/tmp",
    "drush-cache-directory": "/var/www/.drush/cache",
    "drush-conf": [
        "/app/vendor/drush/drush/drush.yml",
        "/app/drush/drush.yml"
    ],
    "drush-alias-files": [
        "/app/drush/sites/site-aliases/integrity.site.yml",
        "/app/drush/sites/site-aliases/naswa.site.yml"
    ],
    "alias-searchpaths": [
        "/app/drush/sites"
    ],
    "install-profile": "minimal",
    "root": "/app/docroot",
    "drupal-settings-file": "sites/naswa/settings.php",
    "site": "sites/naswa",
    "themes": "sites/all/themes",
    "modules": "sites/all/modules",
    "files": "sites/naswa/files",
    "private": "/app/files-private",
    "temp": "/tmp",
    "config-sync": "/app/config/naswa",
    "%paths": {
        "%root": "/app/docroot",
        "%site": "sites/naswa",
        "%modules": "sites/all/modules",
        "%themes": "sites/all/themes",
        "%config-sync": "/app/config/naswa",
        "%files": "sites/naswa/files",
        "%temp": "/tmp",
        "%private": "/app/files-private"
    }
}

+---------------------------+--------------------------------------------------+
| Property                  | Value                                            |
+---------------------------+--------------------------------------------------+
| %paths.%root              | /app/docroot                                     |
| %paths.%site              | sites/naswa                                      |
| %paths.%modules           | sites/all/modules                                |
| %paths.%themes            | sites/all/themes                                 |
| %paths.%config-sync       | /app/config/naswa                                |
| %paths.%files             | sites/naswa/files                                |
| %paths.%temp              | /tmp                                             |
| %paths.%private           | /app/files-private                               |
| admin-theme               | naswa_admin                                      |
| alias-searchpaths.0       | /app/drush/sites                                 |
| blt-version               | 10.2.1                                           |
| bootstrap                 | Successful                                       |
| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10       |
| config-sync               | /app/config/naswa                                |
| db-driver                 | mysql                                            |
| db-hostname               | database                                         |
| db-name                   | drupal8                                          |
| db-password               | drupal8                                          |
| db-port                   | 3306                                             |
| db-status                 | Connected                                        |
| db-username               | drupal8                                          |
| drupal-settings-file      | sites/naswa/settings.php                         |
| drupal-version            | 8.7.5                                            |
| drush-alias-files.0       | /app/drush/sites/site-aliases/integrity.site.yml |
| drush-alias-files.1       | /app/drush/sites/site-aliases/naswa.site.yml     |
| drush-cache-directory     | /var/www/.drush/cache                            |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml                |
| drush-conf.1              | /app/drush/drush.yml                             |
| drush-script              | /app/vendor/drush/drush/drush                    |
| drush-temp                | /tmp                                             |
| drush-version             | 9.7.1                                            |
| files                     | sites/naswa/files                                |
| install-profile           | minimal                                          |
| modules                   | sites/all/modules                                |
| php-bin                   | /usr/local/bin/php                               |
| php-conf.1                | false                                            |
| php-os                    | Linux                                            |
| private                   | /app/files-private                               |
| root                      | /app/docroot                                     |
| site                      | sites/naswa                                      |
| stacks.drupal-vm.inited   | false                                            |
| stacks.dev-desktop.inited | false                                            |
| temp                      | /tmp                                             |
| theme                     | naswa_base                                       |
| themes                    | sites/all/themes                                 |
| uri                       | http://naswa                                     |
+---------------------------+--------------------------------------------------+
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/app/vendor/bin/drush' @naswa.local sqlq "SHOW TABLES LIKE 'config'" --uri=naswa in /app/docroot
config
```

**BLT doctor output**
brookeheaton@pop-os:~/Sites/naswa$ lando blt doctor --site=naswa
```
+---------------------------+--------------------------------------------------+
| Property                  | Value                                            |
+---------------------------+--------------------------------------------------+
| %paths.%root              | /app/docroot                                     |
| %paths.%site              | sites/naswa                                      |
| %paths.%modules           | sites/all/modules                                |
| %paths.%themes            | sites/all/themes                                 |
| %paths.%config-sync       | /app/config/naswa                                |
| %paths.%files             | sites/naswa/files                                |
| %paths.%temp              | /tmp                                             |
| %paths.%private           | /app/files-private                               |
| admin-theme               | naswa_admin                                      |
| alias-searchpaths.0       | /app/drush/sites                                 |
| blt-version               | 10.2.1                                           |
| bootstrap                 | Successful                                       |
| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10       |
| config-sync               | /app/config/naswa                                |
| db-driver                 | mysql                                            |
| db-hostname               | database                                         |
| db-name                   | drupal8                                          |
| db-password               | drupal8                                          |
| db-port                   | 3306                                             |
| db-status                 | Connected                                        |
| db-username               | drupal8                                          |
| drupal-settings-file      | sites/naswa/settings.php                         |
| drupal-version            | 8.7.5                                            |
| drush-alias-files.0       | /app/drush/sites/site-aliases/integrity.site.yml |
| drush-alias-files.1       | /app/drush/sites/site-aliases/naswa.site.yml     |
| drush-cache-directory     | /var/www/.drush/cache                            |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml                |
| drush-conf.1              | /app/drush/drush.yml                             |
| drush-script              | /app/vendor/drush/drush/drush                    |
| drush-temp                | /tmp                                             |
| drush-version             | 9.7.1                                            |
| files                     | sites/naswa/files                                |
| install-profile           | minimal                                          |
| modules                   | sites/all/modules                                |
| php-bin                   | /usr/local/bin/php                               |
| php-conf.1                | false                                            |
| php-os                    | Linux                                            |
| private                   | /app/files-private                               |
| root                      | /app/docroot                                     |
| site                      | sites/naswa                                      |
| stacks.drupal-vm.inited   | false                                            |
| stacks.dev-desktop.inited | false                                            |
| temp                      | /tmp                                             |
| theme                     | naswa_base                                       |
| themes                    | sites/all/themes                                 |
| uri                       | http://naswa                                     |
+---------------------------+--------------------------------------------------+
+------------------------------------------+-------------------------------------------------------------+
| Check                                    | Problem                                                     |
+------------------------------------------+-------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri              | base_url in tests/behat/local.yml does not match the site   |
|                                          | URI.                                                        |
|                                          |   Behat base_url is set to                                  |
|                                          | http://naswa.lndo.site.                                     |
|                                          |   Drush site URI is set to http://naswa.                    |
| ComposerCheck:composer.autoload.psr-4    | The Composer configuration for autoload.psr-4 differs from  |
|                                          | BLT's default, recommended values.                          |
|                                          |   Change your configuration to match BLT's defaults in      |
|                                          |                                                             |
|                                          | vendor/acquia/blt/subtree-splits/blt-project/composer.json. |
| FileSystemCheck:checkFileSystem:%private | Private files directory does not exist.                     |
|                                          |                                                             |
|                                          | Create /app/files-private.                                  |
|                                          | Installing Drupal will create this directory for you.       |
|                                          | Run `blt drupal:install` to install Drupal, or run `blt     |
|                                          | setup` to run the entire setup process.                     |
|                                          | Otherwise, run `mkdir -p /app/files-private`.               |
|                                          |                                                             |
| NodeCheck:checkNodeVersionFileExists     | .node-version file exists                                   |
| WebUriCheck:checkUriResponse             | Did not get a response from http://naswa                    |
|                                          | Is your *AMP stack running?                                 |
|                                          | Is your /etc/hosts file correctly configured?               |
|                                          | Is your web server configured to serve this URI from        |
|                                          | /app/docroot?                                               |
|                                          | Is options.uri set correctly in                             |
|                                          | /app/docroot/sites/naswa/local.drush.yml?                   |
+------------------------------------------+-------------------------------------------------------------+
```

**System information**
* Operating system type: Ubuntu
* Operating system version: 19
* BLT version: 10.2.1

**Comment by brooke-heaton** [comment] 2019-07-31 18:41
I should add the output from a `drush status` on this multisite, which is entirely correct:
```
brookeheaton@pop-os:~/Sites/naswa$ lando drush @naswa.local status
 Drupal version   : 8.7.5                             
 Site URI         : http://naswa.lndo.site            
 DB driver        : mysql                             
 DB hostname      : database                          
 DB port          : 3306                              
 DB username      : drupal8                           
 DB name          : drupal8                           
 Database         : Connected                         
 Drupal bootstrap : Successful                        
 Default theme    : naswa_base                        
 Admin theme      : naswa_admin                       
 PHP binary       : /usr/local/bin/php                
 PHP config       :                                   
 PHP OS           : Linux                             
 Drush script     : /app/vendor/drush/drush/drush     
 Drush version    : 9.7.1                             
 Drush temp       : /tmp                              
 Drush configs    : /app/vendor/drush/drush/drush.yml 
                    /app/drush/drush.yml              
 Install profile  : minimal                           
 Drupal root      : /app/docroot                      
 Site path        : sites/naswa                       
 Files, Public    : sites/naswa/files                 
 Files, Private   : /app/files-private                
 Files, Temp      : /tmp   
```

**Comment by brooke-heaton** [comment] 2019-07-31 18:42
honetly I don't have a clue how I'd ever get an output of `Site URI         : http://naswa`

**Comment by danepowell** [comment] 2019-08-05 21:43
I think WebUriCheck is trying to warn you about this and pointing you in the direction of the culprit:
> Did not get a response from http://naswa. Is options.uri set correctly in /app/docroot/sites/naswa/local.drush.yml?

**Comment by brooke-heaton** [comment] 2019-08-21 19:12
@danepowell 

Yes, my `/sites/naswa/drush.local.yml` simply has this:

```
options:
  uri: 'https://naswa.lndo.site'
```

So this error is very confusing.

**Comment by danepowell** [comment] 2020-04-21 21:10
I'm still not able to reproduce this issue, and I'm not clear what action is required of BLT to fix it.

It seems like a configuration issue or a Drush bug, but I'm afraid I can't point to exactly what based on the information provided. You can check the BehatCheck doctor command, which is where it's coming from.

Since we are removing support for Behat from BLT 12, I'm going to close this issue, but you can create a new issue for the BLT Behat plugin if you'd like (we'll post more information on that in the BLT 12 release notes shortly.)

**Closed by danepowell** 2020-04-21 21:10 UTC
Labels: Bug
