### ISSUE TITLE
Patches pulled from Drupal.org's core issue queue do not apply against drupal/core Composer dependency

### ISSUE THREAD

**Issue by jrbeeman** [acquia/blt#240] opened 2016-07-22 01:26 UTC
Patches defined in composer.json against drupal/core will not apply if they are rolled against Drupal core using the community's patch-driven workflow.

**Background**

* The [drupal/core Composer package](https://packagist.org/packages/drupal/core) builds Drupal 8's /core directory using a Git subtree split of Drupal 8's core directory.
* BLT attempts to apply a patch to the drupal/core project (through use of composer-packages)

This results in something like this in a project's composer.json file:

```
  "extra": {
    "installer-paths": {
      "docroot/core":                     ["type:drupal-core"],
      "docroot/modules/contrib/{$name}":  ["type:drupal-module"],
      "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
      "docroot/themes/contrib/{$name}":   ["type:drupal-theme"],
      "drush/contrib/{$name}":            ["type:drupal-drush"]
    },
    "patches": {
      "drupal/core": {
        "Ignore front end vendor folders to improve directory search performance": "https://www.drupal.org/files/issues/ignore_front_end_vendor-2329453-116.patch"
      }
    }
  },
```

Note that the installer path for Drupal core is docroot/core.

**The issue**

When attempting to run `composer update` or similar commands that rebuild the code base, patches are failing to apply with an error similar to this:

```
https://www.drupal.org/files/issues/ignore_front_end_vendor-2329453-116.patch (Ignore front end vendor folders to improve directory search performance)
cd 'docroot/core' && GIT_DIR=. git apply --check '-p1' '/tmp/579155c71677e.patch'
error: core/lib/Drupal/Core/Extension/Discovery/RecursiveExtensionFilterIterator.php: No such file or directory
```

composer-patches attempts to change directories into the installer path for drupal/core, which is docroot/core. However, the patch expects to apply against the top-level Drupal directory, which `/docroot` in our case. So, the patch fails to apply.

**Comment by jrbeeman** [comment] 2016-07-22 01:28
I believe this will also be an issue with Lightning, e.g. https://github.com/acquia/lightning/blob/8.x-1.x/composer.json#L55-L58

**Comment by grasmash** [comment] 2016-07-22 01:40
@jrbeeman  Would you mind cross-posting this issue here? https://github.com/cweagans/composer-patches/issues

I think that would be the best place to address this. 

It may also be worth making note of it inhttps://github.com/drupal-composer/drupal-scaffold/issues, give that is sets the standard for how drupal core is included via composer.

**Comment by jrbeeman** [comment] 2016-07-22 02:11
Based on https://github.com/cweagans/composer-patches/blob/master/src/Patches.php#L333 I believe composer-patches is already addressing this issue. I'll need to do more research to assess what's causing this behavior on my project.

**Comment by naveenvalecha** [comment] 2016-07-26 02:46
FYI I was having the same issue with views_infinite_scroll https://github.com/acquia/lightning/issues/137
I believe, if the patches will be included in the next versions we should update our composer.json 
Here's the solution what I did https://github.com/acquia/lightning/pull/138

The above issue seems strange to me. I suspect that there might not be the old version of cweagans/composer-patches due to composer cache , I have  latest version(- Installing cweagans/composer-patches (1.5.0)) and it worked for me. Could you try by clearing your composer cache and then running composer install( ./blt.sh local:setup) . This might fix the issue for you.

**Comment by grasmash** [comment] 2016-08-09 15:22
This is resolved by https://github.com/cweagans/composer-patches/pull/30. We may need to fork the project since the issue is beginning to go stale.

@cweagens I'd be happy to help review, refactor, test, etc. if it would help get the issue resolved.

**Comment by cweagans** [comment] 2016-08-09 15:30
Hey folks, sorry for the delay on that. I've been crazy busy with work the past handful of months and really haven't had a chance to look at much of anything else. I'm taking a look now, and if everything is good there, I'll merge it. If you've done any testing on it, I'd appreciate some feedback on the PR with the cases that you've tested and what worked/didn't work.

**Comment by grasmash** [comment] 2016-08-09 21:16
@cweagans Thanks so much!

**Closed by grasmash** 2016-08-09 21:16 UTC
Labels: ready
