### ISSUE TITLE
BLT 10-RC4 Incompatible with Acquia Pipelines

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3605] opened 2019-05-01 15:52 UTC
**Describe the bug**
In a project using Acquia Pipelines, Updated to BLT RC4.  Saw timeouts on Behat.  Upgrading to drush head  seems to fix the issue.  

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1.  Run `composer update acquia/blt`
2. Submit a pull request. 

**Expected behavior**
Acquia Pipeline build completes without error.

**Detailed error output**

```
[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[info] Waiting for response from http://127.0.0.1:8888...

[error]  Timed out.
Drush logged the following errors while attempting to start the web server:
 [notice] HTTP server listening on 127.0.0.1, port 8888 (see http://127.0.0.1:8888/), serving site, sites/default

In Process.php line 1042:
                                                   
  TTY mode requires /dev/tty to be read/writable.  
                                                   

runserver [--default-server DEFAULT-SERVER] [--browser [BROWSER]] [--dns] [--no-browser] [-h--help] [-q--quiet] [-vvvvvv--verbose] [-V--version] [--ansi] [--no-ansi] [-n--no-interaction] [-d--debug] [-y--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r--root ROOT] [-l--uri URI] [--simulate] [--pipe] [-D--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<uri>]

 
[error]  Command `tests:server:start ` exited with code 1. 
[error]  Command `tests:behat:run ` exited with code 1. 
```

**Comment by danepowell** [comment] 2019-05-01 16:01
Dupe of https://github.com/acquia/blt/issues/3513

This is a bug with Drush 9.6, not BLT. I've noted it in several previous BLT 10 release notes, although not in the rc4 notes. I'll be sure to note it again in the 10.0 release notes today.

**Closed by danepowell** 2019-05-01 16:01 UTC
Labels: Bug

**Comment by danepowell** [comment] 2019-05-01 16:10
Specifically, Drush 9.6.3 is the upcoming release that will fix this (no ETA from the Drush maintainers on this that I'm aware of). I'd suggest continuing to use 9.5 for now.
