### ISSUE TITLE
post-code-update hook is failing on CDE code deployments

### ISSUE THREAD

**Issue by cgaudette** [acquia/blt#3757] opened 2019-07-17 23:10 UTC
**Describe the bug**
When the post-code-update hook is triggered after deploying code to an Acquia CDE, a drupal site install is triggered within BLT though Drupal is already installed. 

**To Reproduce**
Deploy code to a CDE. When you do, the postCodeUpdate function of BLT is triggered, which invokes the `updateOdeSites` function. This function has `artifact:install:drupal`, which is trying to install drupal on a site that already has drupal installed.

**Expected behavior**
Deploying master branch deploys on all other environments fine, only on CDE's do they fail.

**Detailed error output**

```
<< blt artifact:ac-hooks:post-code-update $site $target_env $source_branch $deployed_tag $repo_url $repo_type --environment=$target_env --site=$site --yes --no-interaction
<< > artifact:install:drupal
<< > internal:drupal:install
<< [Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/northwelld8.ode2/vendor/bin/drush @self site-install northwell install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --sites-subdir=northwelld8 --site-name='Northwell D8' --site-mail=no-reply@acquia.com --account-name=vu6wOxR0k6 --account-mail=no-reply@acquia.com --locale=en --uri=northwelld8 --no-interaction -v --ansi in /var/www/html/northwelld8.ode2/docroot
<<  [info] Executing: mysql --defaults-file=/mnt/tmp/northwelld8ode2/drush_qOX73v --database=f070a4b1b863420c8d675e306d3fce46 --host=db-f070a4b1b863420c8d675e306d3fce46.cdb.database.services.acquia.io --port=3306 --silent -A < /mnt/tmp/northwelld8ode2/drush_6BVIKt > /dev/null
<<
<< In Filesystem.php line 104:
<<
<<   [Symfony\Component\Filesystem\Exception\IOException]
<<   Failed to create "sites/northwelld8": mkdir(): Permission denied.
<<
```

**System information**
* BLT version: 9.2.4

**Additional context**

Regarding the error - this code is in the BLT `postCodeUpdate` function (same for `postCodeDeploy`)

* https://github.com/acquia/blt/blob/204f080e9566ee8e2288eb5c4aa4eab7af4a5f84/src/Robo/Commands/Artifact/AcHooksCommand.php#L63

```
  public function postCodeUpdate($site, $target_env, $source_branch, $deployed_tag, $repo_url, $repo_type) {
    if (!$this->isAcsfEnv($target_env)) {
      try {
        $this->updateSites($site, $target_env);
        $success = TRUE;
        $this->sendPostCodeUpdateNotifications($site, $target_env, $source_branch, $deployed_tag, $success);
      }
      catch (\Exception $e) {
        $success = FALSE;
        $this->sendPostCodeUpdateNotifications($site, $target_env, $source_branch, $deployed_tag, $success);
        throw $e;
      }
    }
  }
```
It calls this function - `updateSites`:

*https://github.com/acquia/blt/blob/204f080e9566ee8e2288eb5c4aa4eab7af4a5f84/src/Robo/Commands/Artifact/AcHooksCommand.php#L222

```
 /**
   * Executes updates against all sites.
   *
   * @param $site
   * @param $target_env
   */
  protected function updateSites($site, $target_env) {
    if (preg_match('/ode[[:digit:]]/', $target_env)) {
      $this->updateOdeSites();
    }
    else {
      $this->updateAceSites($target_env);
    }
  }
```
The code above says if ODE, run `updateOdeSites`

```
if (preg_match('/ode[[:digit:]]/', $target_env)) {
$this->updateOdeSites();
And this is the code for updateOdeSites():
```
* https://github.com/acquia/blt/blob/204f080e9566ee8e2288eb5c4aa4eab7af4a5f84/src/Robo/Commands/Artifact/AcHooksCommand.php#L127

```
/**
   * Reinstalls Drupal in an ODE.
   */
  public function updateOdeSites() {
    $this->invokeCommand('artifact:install:drupal');
  }
```
It says `updateOdeSites()`

`install:drupal` --- so this looks like if the environment is an ODE -- BLT will try to install Drupal. This is where the failure is in the task is happening, though the code is deployed properly.

Similar issue? https://github.com/acquia/blt/issues/3022

**Comment by cgaudette** [comment] 2019-07-18 22:26
Customer has moved to BLT 10.1.0, but the issue is still present.

**Comment by danepowell** [comment] 2019-07-22 18:33
I think this is a duplicate of https://github.com/acquia/blt/issues/3022, let me know if there's something that makes it unique.

**Closed by danepowell** 2019-07-22 18:33 UTC
Labels: Bug

**Comment by cgaudette** [comment] 2019-07-26 17:32
@danepowell This customer is NOT using pipelines, so the documentation in the other issue would not be relative to this customer I believe.

**Comment by danepowell** [comment] 2019-07-26 17:51
It doesn't matter whether the CDEs are created manually or via Pipelines. The problem is the BLT commands that get triggered by Cloud hooks invoked by CDEs during their creation.

**Comment by jgrahamdev** [comment] 2019-08-05 20:00
@danepowell - I believe this specific issue is not actually a duplicate of #3022. This customer is manually deploying the code to the CDE, so the `post-code-update` hook is in fact firing. The error occurs when `artifact:install:drupal` is called by [updateOdeSites()](https://github.com/acquia/blt/blob/204f080e9566ee8e2288eb5c4aa4eab7af4a5f84/src/Robo/Commands/Artifact/AcHooksCommand.php#L127). In that instance, the following drush command attempts to run on the CD environment: 

```
/var/www/html/northwelld8.ode1/vendor/bin/drush @self site-install northwell install_configure_form.enable_update_status_module=NULL --sites-subdir=northwelld8 --site-name='Northwell D8' --site-mail=no-reply@acquia.com --account-name=MWjtZOmE.b --account-mail=no-reply@acquia.com --locale=en --uri=northwelld8 --no-interaction -v --ansi
```

Which results in the following error:

```
<< In Filesystem.php line 104:
<<
<<   [Symfony\Component\Filesystem\Exception\IOException]
<<   Failed to create "sites/northwelld8": mkdir(): Permission denied.
```

Manually running the above command while passing in the `-vvv` debug flag gives the following output: 

```
northwelld8@northwelld8:~$ /var/www/html/northwelld8.ode1/vendor/bin/drush @self site-install northwell install_configure_form.enable_update_status_module=NULL --sites-subdir=northwelld8 --site-name='Northwell D8' --site-mail=no-reply@acquia.com --account-name=MWjtZOmE.b --account-mail=no-reply@acquia.com --locale=en --uri=northwelld8 --no-interaction -vvv --ansi
 [preflight] Config paths: /etc/drush/drush.yml,/mnt/www/html/northwelld8ode1/vendor/drush/drush/drush.yml,/mnt/www/html/northwelld8ode1/drush/drush.yml
 [preflight] Alias paths: /mnt/drush/northwelld8,/mnt/www/html/northwelld8ode1/docroot/drush/sites,/mnt/www/html/northwelld8ode1/drush/sites
 [preflight] Commandfile search paths: /mnt/www/html/northwelld8ode1/vendor/drush/drush/src,/etc/acquiadrush/commands,/mnt/www/html/northwelld8ode1/drush
 [bootstrap] Starting bootstrap to root [0.17 sec, 10.44 MB]
 [bootstrap] Drush bootstrap phase 1 [0.17 sec, 10.44 MB]
 [bootstrap] Try to validate bootstrap phase 1 [0.17 sec, 10.44 MB]
 [bootstrap] Try to validate bootstrap phase 1 [0.17 sec, 10.44 MB]
 [bootstrap] Try to bootstrap at phase 1 [0.17 sec, 10.44 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.17 sec, 10.44 MB]
 [bootstrap] Change working directory to /mnt/www/html/northwelld8ode1/docroot [0.17 sec, 10.44 MB]
 [bootstrap] Initialized Drupal 8.7.5 root directory at /mnt/www/html/northwelld8ode1/docroot [0.17 sec, 10.63 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.18 sec, 10.95 MB]
 [bootstrap] Initialized Drupal site northwelld8 at sites/default [0.18 sec, 11.2 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.18 sec, 11.2 MB]
 [debug] Add service modifier [0.27 sec, 12.68 MB]
 [info] Executing: command -v mysql [0.27 sec, 13.11 MB]
 [info] sql:query: SELECT 1; [0.28 sec, 13.15 MB]
 [info] Executing: mysql --defaults-file=/mnt/tmp/northwelld8ode1/drush_BBOsLM --database=57b700fd7bf746d2ae6f03a16890ff85 --host=db-57b700fd7bf746d2ae6f03a16890ff85.cdb.database.services.acquia.io --port=3306 --silent -A < /mnt/tmp/northwelld8ode1/drush_F9OF1X [0.28 sec, 13.15 MB]

In Filesystem.php line 104:

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create "sites/northwelld8": mkdir(): Permission denied.


Exception trace:
 () at /mnt/www/html/northwelld8ode1/vendor/symfony/filesystem/Filesystem.php:104
 Symfony\Component\Filesystem\Filesystem->mkdir() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/includes/filesystem.inc:207
 drush_mkdir() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php:341
 Drush\Commands\core\SiteInstallCommands->pre() at /mnt/www/html/northwelld8ode1/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:43
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator() at /mnt/www/html/northwelld8ode1/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate() at /mnt/www/html/northwelld8ode1/vendor/consolidation/annotated-command/src/CommandProcessor.php:195
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /mnt/www/html/northwelld8ode1/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /mnt/www/html/northwelld8ode1/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /mnt/www/html/northwelld8ode1/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /mnt/www/html/northwelld8ode1/vendor/symfony/console/Application.php:987
 Symfony\Component\Console\Application->doRunCommand() at /mnt/www/html/northwelld8ode1/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /mnt/www/html/northwelld8ode1/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/src/Runtime/Runtime.php:118
 Drush\Runtime\Runtime->doRun() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/src/Runtime/Runtime.php:49
 Drush\Runtime\Runtime->run() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/drush.php:72
 require() at /mnt/www/html/northwelld8ode1/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<profile>]...
```

Ultimately - I think the issue comes down to drush command passing in the `--sites-subdir=northwelld8` option, which (as best as I can tell) comes from `install()` function in `DrupalCommand.php`: 

```
  public function install() {

...snip...
    /** @var \Acquia\Blt\Robo\Tasks\DrushTask $task */
    $task = $this->taskDrush()
      ->drush("site-install")
      ->arg($this->getConfigValue('project.profile.name'))
      ->rawArg("install_configure_form.enable_update_status_module=NULL")
      ->option('sites-subdir', $this->getConfigValue('site'))
      ->option('site-name', $this->getConfigValue('project.human_name'))
      ->option('site-mail', $this->getConfigValue('drupal.account.mail'))
      ->option('account-name', $username, '=')
      ->option('account-mail', $this->getConfigValue('drupal.account.mail'))
      ->option('locale', $this->getConfigValue('drupal.locale'))
      ->verbose(TRUE)
      ->printOutput(TRUE);
...snip...

    $result = $task->interactive($this->input()->isInteractive())->run();
    if (!$result->wasSuccessful()) {
      throw new BltException("Failed to install Drupal!");
    }

    return $result;
  }

}
```

Now - looking at the `blt.yml` file for this customer, I'm not seeing a `site` parameter included, so I'm not sure where BLT is getting that value from - maybe an environment variable? At this point - it's unclear to me whether the issue has to do with customer configuration or default functionality from BLT. Any insight you can provide?

**Comment by danepowell** [comment] 2019-08-06 18:03
Can you please open a new issue and make sure to specify that you are manually deploying code to the CDE _after_ it's been created? That's not a very common use case (most people automatically deploy a Pipelines branch) so it wasn't what I assumed was happening in this issue. Thanks!

**Comment by cgaudette** [comment] 2019-08-07 18:07
@danepowell I've opened #3798
