### ISSUE TITLE
Unable to successfully execute blt acsf:init

### ISSUE THREAD

**Issue by dgpalmer** [acquia/blt#2717] opened 2018-04-05 21:37 UTC
My system information:
* Operating system type:  Mac OSX
* Operating system version: 10.13.3
* BLT version: 9.0.5

Output of `blt doctor`:
```
+---------------------------+-----------------------------------------------------+
| Property                  | Value                                               |
+---------------------------+-----------------------------------------------------+
| %paths.%root              | /var/www/asf8/docroot                               |
| %paths.%site              | sites/default                                       |
| %paths.%modules           | sites/all/modules                                   |
| %paths.%themes            | sites/all/themes                                    |
| %paths.%config-sync       | /var/www/asf8/config/default                        |
| %paths.%files             | sites/default/files                                 |
| %paths.%temp              | /tmp                                                |
| %paths.%private           | /var/www/asf8/files-private                         |
| admin-theme               | seven                                               |
| alias-searchpaths.0       | /home/vagrant/.drush/sites                          |
| alias-searchpaths.1       | /var/www/asf8/drush/sites                           |
| blt-version               | 9.0.5                                               |
| bootstrap                 | Successful                                          |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17          |
| config-sync               | /var/www/asf8/config/default                        |
| db-driver                 | mysql                                               |
| db-hostname               | localhost                                           |
| db-name                   | drupal                                              |
| db-password               | drupal                                              |
| db-port                   | 3306                                                |
| db-status                 | Connected                                           |
| db-username               | drupal                                              |
| drupal-settings-file      | sites/default/settings.php                          |
| drupal-version            | 8.5.1                                               |
| drush-alias-files.0       | /home/vagrant/.drush/sites/asf8.site.yml            |
| drush-alias-files.1       | /var/www/asf8/drush/sites/asf8.site.yml             |
| drush-alias-files.2       | /var/www/asf8/drush/sites/example.acsf.site.yml     |
| drush-alias-files.3       | /var/www/asf8/drush/sites/example.local.site.yml    |
| drush-alias-files.4       | /var/www/asf8/drush/sites/legacy.site.yml           |
| drush-conf.0              | /home/vagrant/.drush/drush.yml                      |
| drush-conf.1              | /var/www/asf8/vendor/drush/drush/drush.yml          |
| drush-conf.2              | /var/www/asf8/drush/drush.yml                       |
| drush-conf.3              | /var/www/asf8/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/asf8/vendor/bin/drush                      |
| drush-temp                | /tmp                                                |
| drush-version             | 9.2.3                                               |
| files                     | sites/default/files                                 |
| install-profile           | asf                                                 |
| modules                   | sites/all/modules                                   |
| php-bin                   | /usr/bin/php7.1                                     |
| php-conf.0                | /etc/php/7.1/cli/php.ini                            |
| php-os                    | Linux                                               |
| private                   | /var/www/asf8/files-private                         |
| root                      | /var/www/asf8/docroot                               |
| site                      | sites/default                                       |
| stacks.drupal-vm.inited   | true                                                |
| stacks.dev-desktop.inited | false                                               |
| temp                      | /tmp                                                |
| theme                     | bolero_bootstrap                                    |
| themes                    | sites/all/themes                                    |
| uri                       | http://local.asf8.com                               |
+---------------------------+-----------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists   | tests/behat/local.yml is missing!                         |
|                                      |   Run `blt tests:behat:init:config` to generate it from   |
|                                      | example.local.yml.                                        |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
| WebUriCheck:checkUriResponse         | Did not get a response from http://local.asf8.com         |
|                                      | Is your *AMP stack running?                               |
|                                      | Is your /etc/hosts file correctly configured?             |
|                                      | Is your web server configured to serve this URI from      |
|                                      | /var/www/asf8/docroot?                                    |
|                                      | Is options.uri set correctly in                           |
|                                      | /var/www/asf8/docroot/sites/default/local.drush.yml?      |
+--------------------------------------+-----------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
```
(I'm not worried about the node or behat stuff atm)

When I run this command: 
```
blt acsf:init -vvv
```

I get the following output:
```
[notice] This command will initialize support for Acquia Cloud Site Factory by performing the following tasks:
[notice]   * Adding drupal/acsf and acquia/acsf-tools the require array in your composer.json file.
[notice]   * Executing the `acsf-init` command, provided by the drupal/acsf module.
[notice]   * Adding default factory-hooks to your application.
[notice]   * Adding `acsf` to `modules.local.uninstall` in your blt.yml
[notice]
[notice] For more information, see:
[notice] http://blt.readthedocs.io/en/9.x/readme/acsf-setup
[Filesystem\CopyDir] Copied from /var/www/asf8/vendor/acquia/blt/settings/acsf to /var/www/asf8/factory-hooks
New "factory-hooks/" directory created in repo root. Please commit this to your project.
Adding acsf module as a dependency...
> internal:composer:require
[Composer\RequireDependency] Requiring packages: /usr/bin/composer require 'drupal/acsf:^1.33.0' --ansi
[Composer\RequireDependency] Running /usr/bin/composer require 'drupal/acsf:^1.33.0' --ansi in /var/www/asf8
    1/2:	http://packagist.org/p/provider-latest$3ba4f65c1f78e082b6cba433d4ab782cf5ce716d8a34ca42eb19384633cfd865.json
    2/2:	http://packagist.org/p/provider-2016$8deb5a4165d85072147fac5ac2d7446e550a43d18535d57b6af484a2cb7cac84.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> composer update -d ./docroot/themes/custom/bolero_bootstrap
    1/2:	http://packagist.org/p/provider-latest$abd272ec2ed3273e19e6381d8c3b156c63f1522eab5c12fed3462cd1a70b5e78.json
    2/2:	http://packagist.org/p/provider-2018-01$05c0f842d5e4da68018c0a0cd9f084b7629a263c58d773ffac1c70ed95e277d0.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> composer update -d ./pattern-lab
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> PatternLab\Installer::postUpdateCmd
> composer run-script install-patternlab-ext
> mkdir -p ./pattern-lab/_twig-components/functions
> cp ./vendor/drupal-pattern-lab/add-attributes-twig-extension/add_attributes.function.php ./pattern-lab/_twig-components/functions/
> cp ./vendor/drupal-pattern-lab/bem-twig-extension/bem.function.php ./pattern-lab/_twig-components/functions/
[Composer\RequireDependency] Done in 02:53
In the future, you may pass in a custom value for acsf-version to override the default version. E.g., blt recipes:acsf:init:all --acsf-version='8.1.x-dev'
Executing initialization command provided acsf module...
[Filesystem\FilesystemStack] _rename ["vendor/bin/drush","vendor/bin/drush.bak",true]
[ExecStack] /var/www/asf8/vendor/bin/drush8.phar acsf-init --include="/var/www/asf8/docroot/modules/contrib/acsf/acsf_init" --root="/var/www/asf8/docroot" -y
[ExecStack] Running /var/www/asf8/vendor/bin/drush8.phar acsf-init --include="/var/www/asf8/docroot/modules/contrib/acsf/acsf_init" --root="/var/www/asf8/docroot" -y
Drush was not found in this project's vendor directory. You can install it by typing:
composer install
[ExecStack]  Exit code 1  Time 0.071s
[Filesystem\FilesystemStack] _rename ["vendor/bin/drush.bak","vendor/bin/drush",true]
[error]  Unable to copy ACSF scripts.
02:53 total time elapsed.
```

And I expected this to happen:

acsf:init to succeed so i could deploy to site factory, i am unable to do so until i execute acsf:init 
Not sure why it doesn't think drush is there, blt requires it, and its 100% there.
```
$ ls vendor/drush/drush
CONTRIBUTING.md      docs                 drush.php            includes             mkdocs.yml           sut                  unish.sut.php
README.md            dr.bat               drush.yml            internal-copy        sami-config.php      tests
build                drush                drush_logo-black.png isolation            shippable.yml        unish.clean.php
composer.json        drush.info           examples             misc                 src                  unish.phpunit.php
$ drush --version
Drush Commandline Tool 9.2.3
```

It also seems like in the error that it is trying to use a drush8.phar (which is there) when Drush 9 is the one that is available and required by BLT. This seems odd.

Site factory deployment error without acsf:init

Verify that the acsf-init command has been run recently inside "/mnt/tmp/repo_asf8/asf8_02test_1522961529". - exit: 1; stdout: Including ACSF from: /mnt/tmp/repo_asf8/asf8_02test_1522961529/docroot/modules/contrib/acsf/acsf_init
Command acsf-init-verify was not found.

Thanks,
Donovan

**Comment by dgpalmer** [comment] 2018-04-05 21:43
Not sure why it doesn't think drush is there, blt requires it, and its 100% there.

$ ls vendor/drush/drush
CONTRIBUTING.md      docs                 drush.php            includes             mkdocs.yml           sut                  unish.sut.php
README.md            dr.bat               drush.yml            internal-copy        sami-config.php      tests
build                drush                drush_logo-black.png isolation            shippable.yml        unish.clean.php
composer.json        drush.info           examples             misc                 src                  unish.phpunit.php

$ drush --version
Drush Commandline Tool 9.2.3

**Comment by dgpalmer** [comment] 2018-04-05 21:44
it seems like the acsf-init is trying to run drush8 when blt 9 is using drush9....

**Comment by lcatlett** [comment] 2018-04-06 16:53
@dgpalmer the ACSF module has not yet been ported to drush 9 so the `blt acsf:init` command in 9.x executes acsf-init locally with a drush 8 executable by design. While this temporary workaround may suffice for generating the needed ACSF settings files for ACSF, the other Drush commands such as `acsf-site-verify` have not yet been ported to Drush 9 and can result in errors when drush 8 is installed globally and Drush 9 is installed in your vendor local project repo. The ACSF team is currently working on Drush 9 support, so until that work is completed or other workarounds are created, only Drush 8 can be used on ACSF. Since this is an ACSF contrib module issue rather than a BLT bug, please file an issue in the Drupal contrib module queue at https://www.drupal.org/project/issues/acsf to track progress.

**Comment by dgpalmer** [comment] 2018-04-06 16:57
@lcatlett  I am using drush 9 globally as well as in the project. Is there a time table for this bug? This is literally preventing us from deploying code to site factory as 8.9 of BLT and 1.43+ ACSF was having deployment issues as well (check malcolm's support tickets). We have not been able to deploy to ACSF since 8.8 of BLT and 1.41 of ACSF. (we didn't try 1.42)

```
palmerd $ which drush
/Users/palmerd/.composer/vendor/bin//drush
palmerd $ drush --version
Drush Commandline Tool 9.2.3
```

**Comment by arknoll** [comment] 2018-04-11 17:15
@dgpalmer This is the top priority with the ACSF team. They are fixing the issue in their current sprint and a fix should be released asap.

Reference:
https://docs.acquia.com/site-factory/known-issues

**Comment by grasmash** [comment] 2018-04-12 18:34
Closing as duplicate of https://github.com/acquia/blt/issues/2731

**Closed by grasmash** 2018-04-12 18:34 UTC
Labels: acsf, bug, duplicate
