### ISSUE TITLE
Fail to Preparing artifact directory...

### ISSUE THREAD

**Issue by snize** [acquia/blt#2692] opened 2018-03-29 12:53 UTC
My system information:
* Operating system type: macOS
* Operating system version: 10.12.6
* BLT version: 9.0.5

Output of `blt doctor`:
```
+---------------------------+---------------------------------------------------------+
| Property                  | Value                                                   |
+---------------------------+---------------------------------------------------------+
| %paths.%root              | /var/www/my_project/docroot                               |
| %paths.%site              | sites/default                                           |
| %paths.%modules           | sites/all/modules                                       |
| %paths.%themes            | sites/all/themes                                        |
| %paths.%config-sync       | /var/www/my_project/config/default                        |
| %paths.%files             | sites/default/files                                     |
| %paths.%temp              | /tmp                                                    |
| %paths.%private           | /var/www/my_project/files-private                         |
| admin-theme               | seven                                                   |
| alias-searchpaths.0       | /var/www/my_project/drush/sites                           |
| blt-version               | 9.0.5                                                   |
| bootstrap                 | Successful                                              |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17              |
| config-sync               | /var/www/my_project/config/default                        |
| db-driver                 | mysql                                                   |
| db-hostname               | localhost                                               |
| db-name                   | drupal                                                  |
| db-password               | drupal                                                  |
| db-port                   | 3306                                                    |
| db-status                 | Connected                                               |
| db-username               | drupal                                                  |
| drupal-settings-file      | sites/default/settings.php                              |
| drupal-version            | 8.5.1                                                   |
| drush-alias-files.0       | /var/www/my_project/drush/sites/dev.site.yml              |
| drush-alias-files.1       | /var/www/my_project/drush/sites/local.site.yml            |
| drush-alias-files.2       | /var/www/my_project/drush/sites/prod.site.yml             |
| drush-alias-files.3       | /var/www/my_project/drush/sites/test.site.yml             |
| drush-conf.0              | /var/www/my_project/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/my_project/drush/drush.yml                       |
| drush-conf.2              | /var/www/my_project/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/my_project/vendor/bin/drush                      |
| drush-temp                | /tmp                                                    |
| drush-version             | 9.2.1                                                   |
| files                     | sites/default/files                                     |
| install-profile           | lightning                                               |
| modules                   | sites/all/modules                                       |
| php-bin                   | /usr/bin/php7.1                                         |
| php-conf.0                | /etc/php/7.1/cli/php.ini                                |
| php-os                    | Linux                                                   |
| private                   | /var/www/my_project/files-private                         |
| root                      | /var/www/my_project/docroot                               |
| site                      | sites/default                                           |
| stacks.drupal-vm.inited   | true                                                    |
| stacks.dev-desktop.inited | false                                                   |
| temp                      | /tmp                                                    |
| theme                     | my_project                                                |
| themes                    | sites/all/themes                                        |
| uri                       | http://local.my_project.jp                                |
+---------------------------+---------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
+--------------------------------------+-----------------------------------------------------------+
```

When I run this command:
```
vagrant@local:/var/www/my_project$ blt artifact:deploy -vvv
```

I get the following output:
```
Typically, you would only create a tag if you currently have a tag checked out on your source repository.
 Would you like to create a tag? (y/n)
 Enter a valid commit message [Merge tag 'SA-CORE-2018-002' into develop]
 Enter the branch name for the deployment artifact [develop-build]
Preparing artifact directory...
[error]  Failed to remove file "/var/www/my_project/deploy/vendor/zendframework/zend-stdlib/src/StringWrapper/StringWrapperInterface.php": unlink(/var/www/my_project/deploy/vendor/zendframework/zend-stdlib/src/StringWrapper/StringWrapperInterface.php): Permission denied.
2.971s total time elapsed.
```

```
vagrant@local:/var/www/my_project$ ls -la /var/www/my_project/deploy/vendor/zendframework/zend-stdlib/src/StringWrapper/
total 44
drwxrwxr-x  8 501 dialout  272 Sep 13  2016 .
drwxrwxr-x 33 501 dialout 1122 Sep 13  2016 ..
-rw-rw-r--  1 501 dialout 8587 Sep 13  2016 AbstractStringWrapper.php
-rw-rw-r--  1 501 dialout 6638 Sep 13  2016 Iconv.php
-rw-rw-r--  1 501 dialout 2190 Sep 13  2016 Intl.php
-rw-rw-r--  1 501 dialout 3348 Sep 13  2016 MbString.php
-rw-rw-r--  1 501 dialout 3807 Sep 13  2016 Native.php
-rw-rw-r--  1 501 dialout 3078 Sep 13  2016 StringWrapperInterface.php
```

And I expected this to happen:
Remove `deploy` dir and continue building artifact. 

I have work around for this issue, remove `deploy` dir at outside of VM with before every build. Did someone get this same issue?

**Comment by malikkotob** [comment] 2018-03-29 14:27
@snize I'm not able to reproduce this issue. A couple of questions:
- Did you face any issues when the VM was initially provisioned?
- If you run this outside of the VM are you able to reproduce?

Also, our directories shows the same permission set, so I don't think the issue is there:
```
vagrant@local:/var/www/blt9$ ls -la /var/www/blt9/deploy/vendor/zendframework/zend-stdlib/src/StringWrapper/
total 44
drwxrwxr-x  8 501 dialout  272 Sep 13  2016 .
drwxrwxr-x 33 501 dialout 1122 Sep 13  2016 ..
-rw-rw-r--  1 501 dialout 8587 Sep 13  2016 AbstractStringWrapper.php
-rw-rw-r--  1 501 dialout 6638 Sep 13  2016 Iconv.php
-rw-rw-r--  1 501 dialout 2190 Sep 13  2016 Intl.php
-rw-rw-r--  1 501 dialout 3348 Sep 13  2016 MbString.php
-rw-rw-r--  1 501 dialout 3807 Sep 13  2016 Native.php
-rw-rw-r--  1 501 dialout 3078 Sep 13  2016 StringWrapperInterface.php
```

**Comment by grasmash** [comment] 2018-03-29 15:22
This must be a permission issue. It may be an issue with permissions on the repository root itself, some subdirectories within it, or a problem with the VMs mounting of the directories (requiring a re-provision). 

In terms of what BLT could do to help, we could try to `chmod()` the deploy dir prior to deleting it, but I suspect that if we can't delete it we also can't `chmod()` it.

**Comment by snize** [comment] 2018-03-30 11:52
@malikkotob I don't have the log for provisioning VM but I think finished fine. 
Running `blt artifact:deploy` at outside of VM won't reproduce errors.

**Comment by malikkotob** [comment] 2018-03-30 14:34
@snize another question, how did you ssh into the VM? `vagrant ssh` or `drush @site.local ssh`? SSH forwarding issues have crept up when `drush ssh` is used in favor of `vagrant ssh`. Also what vagrant and VirtualBox versions are you on?

**Comment by snize** [comment] 2018-03-30 22:47
@malikkotob I usually ssh with `vagrant ssh`. Got same error with `vagrant ssh` and `drush @site.local ssh`
versions:
VirtualBox 5.2.6 r120293 (Qt5.6.3)
Vagrant 2.0.2

**Comment by snize** [comment] 2018-04-05 05:11
Re-created vm with `vagrant destroy` and `vagrant up` cause same error.
output: https://gist.github.com/snize/c4e4975d368a1651d945aad1c770cd65

**Comment by malikkotob** [comment] 2018-04-11 17:48
@grasmash, @snize I have not been able to reproduce this issue. It's not clear to me what may be causing it and why it's happening with this file, specifically. If running the command outside of the VM is a sufficient work around, I recommend we close this out until we can get some steps to reproduce.

**Comment by geerlingguy** [comment] 2018-04-12 19:27
@snize - Can you post your `config.yml` file that you're using for the VM? Also, you might want to install and use the `vagrant-bindfs` plugin to make permissions work a little more reliably if you're using the default NFS mount; see the Drupal VM docs here for setup instructions and background: http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors

**Comment by geerlingguy** [comment] 2018-04-12 19:28
See related issue in Drupal VM's issue queue: https://github.com/geerlingguy/drupal-vm/issues/1735

**Comment by snize** [comment] 2018-04-13 00:44
@geerlingguy Here's my [config.yml](https://gist.github.com/snize/b3063325a794894b1fdba198b0cd08b7)
Tried `vagrant-bindfs` but didn't work for me. 

However, apart from that, I found strange things.
1. This time was unable to delete the `.getkeep`.
```
Preparing artifact directory...
[error]  Failed to remove file "/var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/.gitkeep": unlink(/var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/.gitkeep): Permission denied.
vagrant@local:/var/www/my_project$ rm /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/.gitkeep
rm: cannot remove '/var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/.gitkeep': Permission denied
vagrant@local:/var/www/my_project$ ls -la /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/
total 8
drwxrwxr-x 3 vagrant www-data 102 Dec 13 21:29 .
drwxrwxr-x 6 vagrant www-data 204 Dec 13 21:29 ..
-rw-rw-r-- 1 vagrant www-data   0 Dec 13 21:29 .gitkeep
```

2. I added an empty file named `dummy.txt` to the same directory

```
vagrant@local:/var/www/my_project$ touch /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/dummy.txt
vagrant@local:/var/www/my_project$ ls -la /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/
total 8
drwxrwxr-x 4 vagrant www-data 136 Apr 13 00:11 .
drwxrwxr-x 6 vagrant www-data 204 Dec 13 21:29 ..
-rw-rw-r-- 1 vagrant www-data   0 Apr 13 00:11 dummy.txt
-rw-rw-r-- 1 vagrant www-data   0 Dec 13 21:29 .gitkeep
```
3. After added any file, `.gitkeep`can be able to delete.
```
vagrant@local:/var/www/my_project$ rm /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/.gitkeep
vagrant@local:/var/www/my_project$ ls -la /var/www/my_project/deploy/vendor/typhonius/acquia-php-sdk-v2/tests/logs/
total 8
drwxrwxr-x 3 vagrant www-data 102 Apr 13 00:11 .
drwxrwxr-x 6 vagrant www-data 204 Dec 13 21:29 ..
-rw-rw-r-- 1 vagrant www-data   0 Apr 13 00:11 dummy.txt
```

I have no idea why can do this. Any suggestion for this?
Also If this problem is occurring only to me, closing this issue is OK. I will report here if there is progress in the future.

**Comment by grasmash** [comment] 2018-04-24 15:57
@geerlingguy any additional suggestions for @snize?

**Comment by geerlingguy** [comment] 2018-04-24 16:02
No, not sure what would be causing this, but best solution right now seems to be to delete the deploy directory outside the VM before each time, or to run the commands outside the VM if things can be set that way. I don't recall seeing this problem with anyone else's builds, but this also seems to be something specific to BLT's deployment commands... since Vagrant 2 and VirtualBox 5.2 were released, the number of NFS permissions issues relating to Drupal VM in the Drupal VM issue queue have gone down to almost zero.

Maybe the last thing—make sure Drupal VM, Vagrant, and VirtualBox are all on the latest versions, and rebuild the VM then, see if that helps.

**Comment by snize** [comment] 2018-04-27 01:11
Tried to reinstall vagrant VirtualBox and re-create VM with versions above.

- Vagrant 2.0.4
- VirtualBox: 5.2.10 r122088 (Qt5.6.3)
- drupal-vm: 4.8.1

Got same errors. Also, can't remove directory `deploy/*` as root.

```
root@local:/var/www/my_project# rm -rf deploy/
rm: cannot remove 'deploy/.git/objects/12/6a49c22e9d02cc48658575c2b289a92bf23c37': Permission denied
rm: cannot remove 'deploy/.git/objects/12/ffc5537c4eac27a1ac459d8c4fe4272a23d292': Permission denied
rm: cannot remove 'deploy/.git/objects/2e/083b4bbad764b30d6ecb0602b321baf5185d7d': Permission denied
rm: cannot remove 'deploy/.git/objects/2e/65895e8326cf5fac6c3d3663af6bdddf19a818': Permission denied
rm: cannot remove 'deploy/.git/objects/2e/ca1b9d0392f5f25a76abf657e10aa1f7a9f6e3': Permission denied
rm: cannot remove 'deploy/.git/objects/d1/dba096c3b38114f65baeba3fc01a0431e3dd8d': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/ckeditor/plugins/dialog/dialogDefinition.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/ckeditor/plugins/image2/dialogs/image2.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/accordion-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/autocomplete-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/button-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/checkboxradio-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/controlgroup-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/datepicker-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/dialog-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/draggable-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/droppable-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/menu-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/mouse-min.js': Permission denied
rm: cannot remove 'deploy/docroot/core/assets/vendor/jquery.ui/ui/widgets/progressbar-min.js': Permission denied
.....
```

Checked attributes with `lsattr`

```
root@local:/var/www/my_project# lsattr
lsattr: Inappropriate ioctl for device While reading flags on ./acquia-pipelines.yml
lsattr: Inappropriate ioctl for device While reading flags on ./blt
lsattr: Inappropriate ioctl for device While reading flags on ./box
lsattr: Inappropriate ioctl for device While reading flags on ./composer.json
lsattr: Inappropriate ioctl for device While reading flags on ./composer.lock
lsattr: Inappropriate ioctl for device While reading flags on ./config
lsattr: Inappropriate ioctl for device While reading flags on ./deploy
lsattr: Inappropriate ioctl for device While reading flags on ./docroot
lsattr: Inappropriate ioctl for device While reading flags on ./drush
lsattr: Inappropriate ioctl for device While reading flags on ./factory-hooks
lsattr: Inappropriate ioctl for device While reading flags on ./files-private
lsattr: Inappropriate ioctl for device While reading flags on ./hooks
lsattr: Inappropriate ioctl for device While reading flags on ./patches
lsattr: Inappropriate ioctl for device While reading flags on ./phpcs.xml.dist
lsattr: Inappropriate ioctl for device While reading flags on ./PULL_REQUEST_TEMPLATE.md
lsattr: Inappropriate ioctl for device While reading flags on ./README.md
lsattr: Inappropriate ioctl for device While reading flags on ./reports
lsattr: Inappropriate ioctl for device While reading flags on ./salt.txt
lsattr: Inappropriate ioctl for device While reading flags on ./scripts
lsattr: Inappropriate ioctl for device While reading flags on ./tests
lsattr: Inappropriate ioctl for device While reading flags on ./tmp
lsattr: Inappropriate ioctl for device While reading flags on ./Vagrantfile
lsattr: Inappropriate ioctl for device While reading flags on ./vendor
```

I hope this will help.

**Comment by ba66e77** [comment] 2018-06-24 19:42
It's been almost two months since there was activity on the thread. Feel free to reopen if this is still an issue.

**Closed by ba66e77** 2018-06-24 19:42 UTC
Labels: drupal vm, question / support
