### ISSUE TITLE
Blt deploy fails if two merges are done close in time because of git being unable to push

### ISSUE THREAD

**Issue by rsanzante** [acquia/blt#2859] opened 2018-06-07 13:18 UTC
My system information:
* BLT version: 9.1.0

In our CI we watch the git repository, and whenever a commit is made in devel branch a process is triggered. This process includes the blt deploy if all tests are ok to generate the artifact and push it to configured remotes.

If two commits to the devel branch are done close in time, the second artifact push fails because git detects there are new commits in the remote repository. This due how blt manages git. See DeployCommand.php:

```
  protected function deployToBranch($options) {
    $this->branchName = $this->getBranchName($options);
    $this->prepareDir();
    $this->addGitRemotes();
    $this->checkoutLocalDeployBranch();
    $this->mergeUpstreamChanges();
    $this->build();
    $this->commit();
    $this->push($this->branchName, $options);
  }

```

First, blt setups the directory and prepares repository (step 1). Then builds the artifact (step 2) . Last, blt commits the code and pushes the code (step 3). Becasue step 2 is long is possible that a CI process setups de repository and start building the artifact. Then, a second commits enters, CI process is started and prepares the repository and starts building the artifact. First process finishes step 2 and then completes step 3. Then, second CI process finishes artifact, commits and tries to push (step 3). Push fails because there are new commits (the one pushed by first CI process in step 3).

How to solve it? I haven't seen any hook to add behavior between step 2 and step 3, or to modify step 3. One simple approach is to do a git rebase before pushing references. Or do it only if push operation gets an error. But this only works for one remote, when more than one remote are present this probably will fail.

Another options is to delay git setup until artifact is created. I don't know why blt prepares the directory including adding remotes and doing a checkout before building the artifact. I understand that when blt creates an artifact discards previous artifact completely, but this workflow suggests it doesn't.

**Comment by bobbygryzynger** [comment] 2018-06-07 16:50
I've also run into this issue. The only workaround I've found is to `blt deploy` with a different commit message.

**Comment by rsanzante** [comment] 2018-06-08 07:57
@bobbygryzynger I don't understand how a different commit message can be a workaround. You mean to run blt deploy again after a first blt deploy failure?

**Comment by ba66e77** [comment] 2018-06-08 10:58
@rsanzante, can you elaborate on this statement? I'm not able to envision at present when you would have more than one remote to which you were committing the artifact.
>  But this only works for one remote, when more than one remote are present this probably will fail.

The idea of running a rebase if the artifact commit fails makes sense initially, but I wonder if it introduces a greater risk of race-condition based regressions that really should be reviewed/disentangled by a human.

**Comment by rsanzante** [comment] 2018-06-08 12:12
@ba66e77 Well, I don't know such situation either, but blt code deals with multiple remotes:

``` 
    foreach ($this->getConfigValue('git.remotes') as $remote) {
      $remote_name = md5($remote);
      $task->exec("git push $remote_name $identifier");
    }
```

See https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Deploy/DeployCommand.php#L508

> The idea of running a rebase if the artifact commit fails makes sense initially, but I wonder if it introduces a greater risk of race-condition based regressions that really should be reviewed/disentangled by a human.

Yes, I agree it something to think about. But introducing a manual review step breaks tha automation. it could be an option: In case of conflict pushing what t do? 

1. Abort. 
2. Wait for human review (prompt).
3. Rebase blindly, push again.

**Comment by bobbygryzynger** [comment] 2018-06-08 18:36
@rsanzante sorry, I misread the issue you were having. Disregard my previous comment.

**Comment by ba66e77** [comment] 2018-08-30 11:09
Closing since there's been no followup in over two months.

**Closed by ba66e77** 2018-08-30 11:09 UTC
Labels: enhancement, question / support
