### ISSUE TITLE
8.9.x: How do I copy the DB into BLT for "Automated testing using live content"

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1573] opened 2017-06-02 03:19 UTC
The read the docs still mention how to do this for phing.  How would I do this with ROBO?
http://blt.readthedocs.io/en/8.x/readme/ci/#automated-testing-using-live-content

**Comment by grasmash** [comment] 2017-06-02 20:09
This is a planned feature. I'd like you to be able to choose between sync/re-install behavior by setting a value in project.yml.

**Comment by grasmash** [comment] 2017-06-20 14:32
This is a duplicate of #1004

**Closed by grasmash** 2017-06-20 14:32 UTC
Labels: 8.9.x, duplicate, enhancement
