### ISSUE TITLE
Improve site install experience on Acquia Cloud

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2067] opened 2017-10-02 18:44 UTC
At some point, you have to install your site on AC (or other hosting environment). It doesn't seem like there's a documented best practice for how to do this.

The best method I've found is to SSH into the server and run `./vendor/bin/blt setup:drupal:install`, but this throws a bunch of warnings because of AC's read-only filesystem and file locations.

We should document the best approach, and also improve the install experience. Maybe insert some logic into those install functions to not throw so many warnings in a cloud environment.

Specifically, I see the following problems:

## Local settings file doesn't exist
> [warning] /var/www/html/foo.prod/docroot/sites/default/settings/local.settings.php is missing.
>  Do you want to generate this required settings file(s)? (y/n)

If we're on ACE, don't prompt this, just assume no.

## Read-only filesystem and setting permissions
> [error]  Unable to set permissions for site directories.

**Comment by grasmash** [comment] 2017-12-20 16:35
Additionally, we should walk users through the process of pushing an initial database and files to an upstream off we are endpoint for the first time (after initial site generation on a local machine).

**Comment by damontgomery** [comment] 2018-01-11 16:09
@danepowell, I would assume a hosted environment would be looking at an artifact only. Would it make sense to add a flag to an artifact to make it clear it's an artifact and not a source and then modify most of the BLT commands to not run against artifacts?

**Comment by danepowell** [comment] 2018-01-12 18:44
Good point, we can probably make this logic conditional to artifacts, not conditional to ACE. We can probably just assume that any build artifact should be read-only.

**Comment by TravisCarden** [comment] 2018-01-12 18:53
I just went through the process of installing a BLTed site on a fresh Acquia Cloud Professional subscription, and I got no errors, warnings, or prompts of any kind. The operation was successful, and the installed site works as expected. I can add documentation of the process I followed. In terms of actually improving the experience, two opportunities stand out to me:

1. We could add better precondition testing and error-handling in case people _don't_ follow the documentation (perhaps pointing them to it in the error message).
1. We could add the ability for `blt setup:drupal:install` to use a Drush site alias so you don't have to SSH into the remote server.

I will begin with the former (documentation) and wait for thoughts on the latter.

**Comment by dpagini** [comment] 2018-01-12 20:34
I second the idea on the latter. For a time, we were running `$ blt setup -d drush.alias=remote` (not sure this is the exact format) which would run the drush commands remote, but go through a whole bunch of other commands locally (like the frontend build). Part of that was laziness, but it would be great for maybe a `$ blt remote:install` type command or "remote" suite.

**Comment by TravisCarden** [comment] 2018-01-24 20:31
@grasmash, I've been given other project priorities, so I won't be getting to this in the short term. I didn't get anywhere meaningful with documentation because I turned my attention to renaming commands. I've submitted a PR (https://github.com/acquia/blt/pull/2489) for what I had in the works when I switched tasks.

**Comment by TravisCarden** [comment] 2018-01-30 17:12
Oh, I found some notes I had taken along the way... The following are the steps I took to install on the Cloud:

- Installed locally.
- Generated build artifact with BLT.
- Created new Git repo and committed.
- Added remote for Acquia Cloud.
- Pushed `master-build` branch.
- Deployed `master-build` on dev environment.
- `blt deploy:drupal:install`

**Comment by grasmash** [comment] 2018-04-24 15:46
Closing due to feedback:

> I just went through the process of installing a BLTed site on a fresh Acquia Cloud Professional subscription, and I got no errors, warnings, or prompts of any kind. The operation was successful, and the installed site works as expected.

As far as the suggestion to add drush alias support, I'm not in support. Drush aliases have been a major cause of bugs and generally unexpected behavior, and I'd like to avoid them at all costs.

> We could add better precondition testing and error-handling in case people don't follow the documentation (perhaps pointing them to it in the error message).

This sounds good, but it's not actionable. Please open issues with specific requirements if you have examples in mind.

**Closed by grasmash** 2018-04-24 15:46 UTC
Labels: documentation, enhancement, sprint
