### ISSUE TITLE
Profile Splits Not Functional

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3575] opened 2019-04-24 14:44 UTC
**Is your feature request related to a problem? Please describe.**
Theoretically, using multi-site Drupal 8, you might want to have multiple profiles. Then, you can install various sites on your multi-site platform from any one of the profiles. Going a step farther, you likely want to have configuration for each of the profiles.

There is an issue currently between drupal/core, drupal/config_split, and acquia/blt that isn't allowing config splits at the profile level to work. **To be clear, I don't believe this is actually a BLT problem.** However, I do believe that BLT can help with a workaround.

The issue, fundamentally, is that a config split model assumes a default set of configuration that is overwritten in the various splits. This works great for single profile models. **However** with a multi-profile model, this immediately breaks down because drupal/core writes the profile key into core.extensions.yml. The result? As soon as you try to import config on a site with an active profile that is not the profile in core.extensions.yml you get the following error:

```
The selected installation profile <em class="placeholder">profile_1</em> does not match the profile stored in configuration <em class="placeholder">profile</em>
```

**Describe the solution you'd like**
We need to brainstorm a solution. Our project has a work around that essentially uses a custom factory hook to change the "sync" config directory to bypass config/default entirely. This "works" but I'd love a solution that allows this to function properly.

**Describe alternatives you've considered**
I've had great luck with config ignore for _config updates_. However, the problem described above persists during the installation (because the core.extension import happens before the rest of the configuration, and the config ignore config for ignoring the profile isn't present when the initial config sync happens).

**Additional context**
We need to be cautious how we approach this, because many cloud systems (e.g. ACE, ACSF) don't use BLT to install.

@danepowell DID push a partial fix for this issue here - https://github.com/acquia/blt/pull/3522. However, this doesn't necessarily solve the entire issue.

**Comment by mikemadison13** [comment] 2019-04-24 15:01
Note that the outcome of this issue may just be documentation.

**Comment by danepowell** [comment] 2019-04-26 21:08
I definitely agree that this is a problem, but I'm not sure how much I can help here, since I'm not actively using profile splits in that way. I'd surely welcome any documentation you want to provide, but I agree that this doesn't seem like a BLT problem per se.

Since there's not much actionable here, I'm going to close this issue, but feel free to continue to use it to coordinate discussion, and let me know if there's something actionable for BLT to take on to help users with this.

**Comment by danepowell** [comment] 2019-04-29 16:20
Per conversation with Mike, he's going to post an alternative solution for profile splits that works a lot better than anything BLT could do, and we're considering removing the profile split functionality entirely from BLT for 10.0.0.

**Comment by mikemadison13** [comment] 2019-04-29 16:22
A few updates:
* BLT activates a profile split based on the profile.name key in blt.yml (https://github.com/acquia/blt/blob/10.x/settings/config.settings.php#L96) but does not actively set that value. So, unless users are willing to manually set the profile values for each of their multi-sites in a site specific blt.yml there is no way to juggle this in the codebase and have it "work"
* @nedsbeds has written a really split config filter plugin (https://github.com/nedsbeds/profile_split_enable) that does what we wanted to do with BLT in the first place (detect the active profile and set the split to active). 

I would propose that BLT officially drop profile split support, in favor of the new profile_split_enable method. This way, BLT doesn't have to juggle this functionality that it does, in all reality, have an insufficient view into because of the lack of Drupal container (but a module would have access to).

**Closed** 2019-04-30 21:53 UTC
Labels: Bug, Enhancement

**Comment by Rajendarreddy1431** [comment] 2019-05-02 21:26
I achieved profile specific splits working without changing code. Here is my strategy.

In config/default folder,

- profile key should be empty(`profile: ''`) and make sure to remove profile name key under the `modules:` in the core.extensions.yml (e.g, `standard: 1000`)
- In each `config_split.config_split.PROFILE.yml` file set status to false(`status: false`)
- In `config_ignore.settings.yml`, ignore the profile config_split status, profile name and base site profile.
```
 0: 'config_split.config_split.PROFILE1:status'
 2: 'config_split.config_split.PROFILE2:status' (include all profiles)
 4: 'core.extension:profile'
 6: 'core.extension:module.PROFILE1'
 8: 'core.extension:module.PROFILE2' (include all profiles)
```

In the profile folder(`docroot/profiles/custom/profile1`):

- Copy `config_split.config_split.profile1.yml` file from `config/default` to `docroot/profiles/custom/profile1/config/install`. and change status to true (`status: true`)
- Create or copy the one from config/default of `config_ignore.settings.yml` and ignore following.
```
  2: 'config_split.config_split.PROFILE1:status'
  4: 'config_split.config_split.PROFILE2:status' (include all profiles)
  6: 'core.extension:profile'
  8: 'core.extension:module.PROFILE1'
  10: 'core.extension:module.PROFILE1' (include all profiles)
```
If you don't add this file, you will encounter ```
Cannot change the install profile from <em class="placeholder">profile1</em> to <em class="placeholder"></em> once Drupal is installed.```

Note:

1. profile and module keys will be add to the `core.extension.yml` and `config_split.config_split.ACTIVE_PROFILE.yml` status set to true on `drush csex`. Make sure to ignore these changes on `git commit`.
2. Make sure to enable active profile split in `admin/config/development/configuration/config-split` for the existing sites before `drush config-import`.

Above strategy worked for both existing and new sites.

**Comment by longmtran** [comment] 2019-06-06 12:00
I can confirm that @Rajendarreddy1431 's [approach](https://github.com/acquia/blt/issues/3575#issuecomment-488838069) above indeed works without any code change. Only small compromises stated in the `Note:` section, but that works for us.

One minor thing to note is that each profile's `.info.yml` should have `config_split` and `config_ignore` in dependencies list so that the config in `config/install` can be installed during initial site installation.
