### ISSUE TITLE
Travis build getting stuck with vagrant ssh while pushing git tag.

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#3558] opened 2019-04-17 08:36 UTC
**I want to...**
Push git tag to remote Acquia cloud environment.

**It's not working because...**
Not sure why Travis build not working for Tags, however it is working fine for other branches (feature/*, release/*), PRs & able to push branches to remote.

**Detailed error output**

<img width="1324" alt="Screenshot 2019-04-17 at 2 04 39 PM" src="https://user-images.githubusercontent.com/6311767/56273149-d230c900-6119-11e9-8745-220559e77327.png">

**BLT doctor output**

<img width="736" alt="Screenshot 2019-04-17 at 1 46 50 PM" src="https://user-images.githubusercontent.com/6311767/56271961-4f0e7380-6117-11e9-8892-053f0d157882.png">

**System information**
* Operating system type: MacOS Mojave
* Operating system version: 10.14.3
* BLT version: 9.2.4

**Comment by sandipsmarty** [comment] 2019-04-22 04:54
@grasmash, @danepowell: Could you please help me on this issue I am facing.

**Comment by alexxed** [comment] 2019-04-22 08:23
@sandipsmarty it looks to me like the travis build gets prompted for input, which does not exist on travis. Have Travis run the deploy command with -n (no interaction).

**Comment by sandipsmarty** [comment] 2019-04-22 09:58
@alexxed : Here is the deploy script defined in my .travis.yml file.

`deploy:
  - provider: script
    script: "${BLT_DIR}/scripts/travis/deploy_branch"
    skip_cleanup: true
    on:
      branch: develop
      php: 7.2
  - provider: script
    script: blt deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "release-build" --ignore-dirty --no-interaction -v
    skip_cleanup: true
    on:
      branch: release/*
      php: 7.2
  - provider: script
    script: blt deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" --branch "hotfix-build" --ignore-dirty --no-interaction -v
    skip_cleanup: true
    on:
      branch: hotfix/*
      php: 7.2
  - provider: script
    script: "${BLT_DIR}/scripts/travis/deploy_tag"
    skip_cleanup: true
    on:
      tags: true
      php: 7.2`

Travis deploy commands running successfully for all branches except tags.

When I looked into /vendor/acquia/blt/scripts/travis/deploy_tag, `--no-interaction` parameter is missing. Not sure if the issue with BLT core, when I modified the deploy script for tags in .travis.yml file with the following line builds started passing for tags as well.

` blt deploy --commit-msg "Automated commit by Travis CI for Build ${TRAVIS_TAG}" --tag "${TRAVIS_TAG}-build" --ignore-dirty --no-interaction -v`

**Comment by alexxed** [comment] 2019-04-23 04:41
Whenever you run blt in an automated environment like CI, you should always use --no-interaction. 
@danepowell how about automating this for people, setting --no-interaction automatically if running in CI?

For Travis and CircleCI, there's a CI=true environment variable https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
For Jenkins you can check the user (jenkins), or the environment variable JENKINS_HOME

**Comment by danepowell** [comment] 2019-04-23 20:13
We haven't had --no-interaction in deploy_tag for years and it's never been a problem. I guess philosophically it should be there, since it _is_ running in a non-interactive environment, but that's not really the root cause here.

You should never be running a VM in Travis in the first place. I suspect you have accidentally committed the following lines to your blt.yml. These should only exist in local.blt.yml, not blt.yml, so as not to be used in a CI environment.
```
vm:
  enable: true
```

Please remove those lines, and if that still doesn't work or isn't relevant please post the contents of your blt.yml and ci.blt.yml.

**Comment by sandipsmarty** [comment] 2019-04-24 07:12
@danepowell : I do not have `vm:enable: true` in my blt.yml file, it's there in my local.blt.yml file.

Below are the full content of my blt configuration files.

**blt.yml**

> project:
  machine_name: discoverboat
  prefix: NMMA
  human_name: 'Discover Boating'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    - 'discoverboatus@svn-29892.prod.hosting.acquia.com:discoverboatus.git'
  commit-msg:
    pattern: '/(^[A-Z]{2,4}-[0-9]+(: )[^ ].{15,}\.)|(Merge branch (.)+)/'
deploy:
  tag_source: true
drush:
  aliases:
    remote: discoverboatus.dev
    local: self
    ci: self
  default_alias: self
modules:
  local:
    enable: [dblog, seckit, views_ui, stage_file_proxy]
    uninstall: [acquia_connector, shield, acquia_purge, purge]
  ci:
    enable: {  }
    uninstall: {  }
  dev:
    enable: [acquia_connector, shield, acquia_purge, purge]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield, acquia_purge, purge]
    uninstall: [devel, views_ui, stage_file_proxy]
  prod:
    enable: [acquia_connector, acquia_purge, purge]
    uninstall: [devel, views_ui, stage_file_proxy, dblog, shield]
multisites:
  -default
validate:
  twig:
    filesets: [files.twig.custom]
    functions: [drupal_field, drupal_view, drupal_block, drupal_region, drupal_entity, drupal_menu, drupal_form, drupal_image, drupal_token, drupal_config, drupal_title, drupal_url, drupal_link, drupal_messages, drupal_breadcrumb]
disable-targets:
  tests:
    phpcs: { sniff: { all: true } }
    behat: { run: true }
    security: { check: { updates: true } }
command-hooks:
  frontend-reqs:
    dir: '${docroot}/themes/custom/nmma'
    command: 'npm install && npm install -g gulp'
  frontend-assets:
    dir: '${docroot}/themes/custom/nmma'
    command: node_modules/.bin/gulp
cm:
  allow-overrides: true
------------------------------------------------------------
**local.blt.yml**

> environment: local
drush:
  aliases:
    remote: discoverboatus.dev
vm:
  enable: true
-------------------------------------------------------------
**ci.blt.yml**

> tests.run-server: true
project.local.hostname: 127.0.0.1:8888
drush.debug: false

**Comment by danepowell** [comment] 2019-04-24 17:57
@sandipsmarty have you committed local.blt.yml to your Git repo? It should be gitignored and never committed, but I've seen cases recently where it somehow got committed anyway (cc @anavarre )

Somehow `vm:enable: true` is getting set in your Travis test runs, when it shouldn't be. I don't think that's something that BLT could ever do by itself, I think it would have to come from a configuration file.

**Comment by sandipsmarty** [comment] 2019-04-25 03:39
@danepowell : Yes the local.blt.yml was committed somehow on our git repo. Are you saying if I add local.blt.yml file in .gitignore list the problem will be resolved?

**Comment by anavarre** [comment] 2019-04-25 06:19
> I've seen cases recently where it somehow got committed anyway

FTR in my instance it was not 'committed anyway'. It was very much force-committed because I didn't see a reason why a local file would create friction with a remote CI environment (which, to my knowledge, it never did).

**Comment by danepowell** [comment] 2019-04-25 14:22
It should already be in the .gitignore file BLT provided with your project. But if you've modified that for some reason, yes you should gitignore it, and then remove it from your git repo.

The pattern that BLT and Drupal core generally follow is to not commit local files like local.settings.php, local.behat.yml, local.blt.yml, etc... Obviously you can override that if you want but it's at your own peril and very likely to cause problems, since every local environment is different (some use DrupalVM, some use Lando, some use MAMP, etc...)

Is there some change we could make to documentation or the file itself to make that more clear?

**Comment by anavarre** [comment] 2019-04-25 14:30
> But if you've modified that for some reason, yes you should gitignore it, and then remove it from your git repo.

Ack.

> Is there some change we could make to documentation or the file itself to make that more clear?

I and others have done this for convenience, I guess. If we could better identify what exactly could go wrong, then I think this would help people refrain from doing so.

Otherwise we could have a pre-commit check that would alert the file is there and it's strongly recommended against?

**Comment by danepowell** [comment] 2019-04-25 14:34
There's probably a million potential issues on this level that we could check for, I don't think it makes sense to chase them all. A documentation change is probably best. #3585

**Comment by danepowell** [comment] 2019-04-25 17:25
#3585 and #3588 should both fix this (belt and suspenders...). This issue will be closed once those are merged but I'm still interested to hear more about what folks are trying to achieve by committing local.blt.yml.

**Closed** 2019-04-25 18:11 UTC
Labels: Support

**Comment by sandipsmarty** [comment] 2019-04-26 06:51
Thanks everyone for your help & support!!!
