### ISSUE TITLE
BLT does not recreate project.local.yml when running setup

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#2290] opened 2017-11-17 03:31 UTC
My system information:
* BLT version:  8.9.10

When I have a fresh clone of a BLT project and I run BLT setup. I expect setup to copy blt/example.project.local.yml to blt/project.local.yml BEFORE it tries to install drupal.

When I run this command:
```
blt setup
```
The file is not copied as expected.  However when I run 
```
blt setup
```
a second time the file is copied and the setup completes as expected.

I suspect that blt setup is copying the file but in the wrong order.

This bug causes some confusion and headaches with onboarding new team-members.

**Comment by rukshan-rodrigo** [comment] 2017-11-20 03:50
Aren't you suppose to run `blt setup:settings` first?
Then `blt setup`.

**Comment by danepowell** [comment] 2017-11-27 18:57
@rukshan-rodrigo you should run `blt setup:settings` independently only if you have a LAMP stack, so that you can add db credentials to settings.php before installing Drupal. This is called out in the [onboarding README](https://github.com/acquia/blt/blob/9.1.x/readme/onboarding.md). If you are using DrupalVM, this isn't necessary.

If you only run `blt setup` (defined in [AllComand.php](https://github.com/acquia/blt/blob/8.9.x/src/Robo/Commands/Setup/AllCommand.php#L23)), it will run `setup:build`, which in turn calls `setup:settings` anyway (defined in [SettingsCommand.php](https://github.com/acquia/blt/blob/8.9.x/src/Robo/Commands/Setup/SettingsCommand.php)). This all happens before Drupal is installed, so again it's really just a matter of making sure db credentials are defined somewhere before Drupal installs. But project.local.yml should definitely get generated no matter what.

@aweingarten can you confirm that you haven't overridden any setup commands? Can you reproduce this on a vanilla BLT project? It should be pretty easy for you to create a new project for testing.

**Comment by aweingarten** [comment] 2017-11-27 19:02
@danepowell I reproduced this on a brand new site.  No command overrides.

**Comment by danepowell** [comment] 2017-11-27 19:25
I see, this only happens if you aren't using DrupalVM. I can reproduce it now.

**Comment by danepowell** [comment] 2017-11-29 21:55
Actually I can't reproduce this. I'm not sure if I was looking at the same thing yesterday or not.

1. Create fresh BLT project: `composer create-project --no-interaction acquia/blt-project blted2290`
2. `cd blted2290`
3. Verify that _blt/project.local.yml_ does not exist
4. Run `blt setup` (killed this once it got to the site install - [see log](https://pastebin.com/YDHm5FqS))
5. Verify that _blt/project.local.yml_ now exists

@aweingarten what are you doing differently?

**Comment by danepowell** [comment] 2017-12-05 21:06
Closing since I can't reproduce, but feel free to reopen if you can provide additional details

**Closed by danepowell** 2017-12-05 21:06 UTC
Labels: 8.9.x, bug

**Comment by Tjocksmurf** [comment] 2018-01-18 04:01
I'm running into a similar problem.

composer clear-cache
export COMPOSER_PROCESS_TIMEOUT=2000
composer create-project --no-interaction acquia/blt-project projectname
cd projectname
blt setup:settings -vvv

[debug] Drupal VM is not initialized.
[Filesystem\FilesystemStack] _copy /project/blt/example.project.local.yml","/project/blt/project.local.yml"]

No files are generated in sites/default
