### ISSUE TITLE
Blt vm fails with vagrant 1.8.7

### ISSUE THREAD

**Issue by benjifisher** [acquia/blt#654] opened 2016-11-11 04:17 UTC
We are still investigating and will provide more details, including

- Versions of OS X and BLT
- Results of `blt doctor`
- Full output of `blt vm`

The command `blt vm` fails on two of my coworkers' systems.  I believe the problem is that vagrant uses the system `libcurl`.  If this is too old, then vagrant fails to download the box.

On my system, the command **succeeds**:

- OS X 10.12.1 (Sierra)
- `composer info acquia/blt` reports `versions : * 8.5.0`.
- `vagrant --version` reports 1.8.5 (not the latest)

and

```
$ /usr/bin/curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

Possible work-arounds (need testing) are to download the box with either

```
vagrant box add --insecure geerlingguy/ubuntu1404
```

or downloading the box from `http://files.midwesternmac.com/boxes/ubuntu1404/virtualbox-114.box` and adding it with

```
vagrant box add --name geerlingguy/ubuntu1404 path/to/file.box
```

Possible resolutions  of this issue include

- Update the [system requirements](http://blt.readthedocs.io/en/latest/INSTALL/#system-requirements) for BLT to require a minimum version of OS X.
- Add a work-around to the [Onboarding](http://blt.readthedocs.io/en/latest/readme/onboarding/) instructions (or adding a new "troubleshooting" page).
- Update BLT so that it uses a fallback method when vagrant fails to download the box.

**Comment by benjifisher** [comment] 2016-11-11 16:27
It turns out that the issue was not the system version of `libcurl` but a bug in the latest version (1.8.7) of `vagrant`.  See [this post](http://stackoverflow.com/questions/40473943/vagrant-box-could-not-be-found-or-could-not-be-accessed-in-the-remote-catalog) on StackOverflow.

I will update the issue title.  I do not know whether you want to close the issue or keep it open for better visibility.

**Comment by geerlingguy** [comment] 2016-11-11 16:35
See: https://github.com/geerlingguy/drupal-vm/issues/981 (upstream issue in drupal-vm). And yes, it's a _major_ bug in Vagrant 1.8.7. Hopefully 1.8.8 comes out soon... and doesn't introduce any other regressions :P

If you want to remain on Vagrant 1.8.7, see this workaround: https://github.com/mitchellh/vagrant/issues/7969#issuecomment-258878970

**Comment by grasmash** [comment] 2016-11-15 23:51
Thanks for posting. I'm closing since this is an upstream issue in Vagrant.

**Closed by grasmash** 2016-11-15 23:51 UTC
Labels: invalid
