### ISSUE TITLE
BLT Setup Issue

### ISSUE THREAD

**Issue by vishakha-s** [acquia/blt#2415] opened 2018-01-08 04:54 UTC
I am trying to setup drupal8 BLT project on local but getting some errors while doing it.
When i run blt local:setup command i get some error on setup.xml file of BLT directory.
I have already installed Drupalvm,npm,nodejs,gulp which is required to run BLT setup.

What can be cause for this issue??
```
   [drush] #9 [internal function]: drush_command('dblog,devel,sec...')
    [drush] #10
    [drush] /vendor/drush/drush/includes/command.inc(199):
    [drush] call_user_func_array('drush_command', Array)
    [drush] #11
    [drush] /vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67):
    [drush] drush_dispatch(Array)
    [drush] #12
    [drush] /drush/drush/includes/preflight.inc(66):
    [drush] Drush\Boot\BaseBoot->bootstrap_and_dispatch()
    [drush] #13 /vendor/drush/drush/drush.php(12):
    [drush] drush_main()
    [drush] #14 {main}
[phingcall] /./vendor/acquia/blt/phing/tasks/setup.xml:370:8: /./vendor/acquia/blt/phing/tasks/setup.xml:374:12: /./vendor/acquia/blt/phing/tasks/setup.xml:377:69: Drush exited with code 1
[phingcall] /vendor/acquia/blt/phing/tasks/setup.xml:350:45: Execution of the target buildfile failed. Aborting.

BUILD FAILED /./vendor/acquia/blt/phing/tasks/local-sync.xml:97:37: Execution of the target buildfile failed. Aborting.
; 2 minutes  12.12 seconds
```

**Comment by jayakrishnanj** [comment] 2018-01-08 06:01
Hi @vishakha-s,

1. After running `composer create-project --no-interaction acquia/blt-project my-project
` You can customize the blt/project.yml file and then run 'blt vm'. 
2. This step will setup the complete Drupalvm with default configurations for a new project, no configurations such as nodejs gulp,etc. required to setup blt if it is not mentioned in boc/config.yml.
3. After successful setup of 'blt vm' you can validate the installation by checking the file 'docroot/sites/default/settings/local.settings.php'
4. Now, if you run **`blt setup`** NOTE: not blt local setup, you should be able to setup new Drupal 8 site. 

Kindly post the output of  `blt doctor` to analyze more.

**Comment by vishakha-s** [comment] 2018-01-08 06:27
Hi,

I am trying to setup existing drupal8 project.I tried to run **blt setup** command but only few tables (50) are getting imported in adminer.

Output of blt doctor:

blt > doctor:
Changed current directory to /home/vagrant/.composer
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/test/docroot                                                  |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/test/config/default                                           |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/test/files-private                                            |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.8.7                                                                            |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/test/config/default                                           |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | drupal                                                                           |
| db-password          | root                                                                             |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | root                                                                             |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.3.7                                                                            |
| drush-alias-files    | /var/www/test/docroot/../drush/site-aliases/example.local.aliases.drus |
|                      | hrc.php                                                                          |
|                      | /var/www/test/docroot/../drush/site-aliases/example.acsf.aliases.drush |
|                      | rc.php                                                                           |
|                      | /var/www/test/docroot/../drush/site-aliases/aliases.drushrc.php        |
|                      | /var/www/test/docroot/../drush/site-aliases/test.acsf.aliase |
|                      | s.drushrc.php                                                                    |
| drush-conf           | /var/www/test/drush/drushrc.php                                        |
| drush-script         | /var/www/test/vendor/drush/drush/drush.php                             |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.10                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | test                                                                         |
| local-drushrc        | /var/www/test/docroot/sites/default/local.drushrc.php                  |
| local-settings       | /var/www/test/docroot/sites/default/settings/local.settings.php        |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/5.6/cli/php.ini                                                         |
| php-os               | Linux                                                                            |
| private              | /var/www/test/files-private                                            |
| root                 | /var/www/test/docroot                                                  |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | test_base_theme                                                              |
| themes               | themes                                                                           |
| uri                  | default                                                                          |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+---------------------------------------------------------------------------------+
| Check                    | Outcome                                                                         |
+--------------------------+---------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                  |
| checkCoreExists          | Drupal core exists                                                              |
| checkSettingsFile        | BLT settings are included in settings file.                                     |
| checkLocalSettingsFile   | Found your local settings file.                                                 |
| checkLocalDrushFile      | Found your local drush settings file.                                           |
| checkUri                 | Site URI is not set                                                             |
|                          |                                                                                 |
|                          | Is $options['uri'] set correctly in                                             |
|                          | /var/www/test/docroot/sites/default/local.drushrc.php?                |
|                          |                                                                                 |
| checkFileSystem:%files   | Public files directory is writable.                                             |
| checkFileSystem:%private | Private files directory is writable.                                            |
| checkFileSystem:%temp    | Temporary files directory is writable.                                          |
| checkDbConnection        | Connected to database.                                                          |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                  |
| checkDrupalInstalled     | Drupal is installed.                                                            |
| checkCaching:page        | Drupal cache is disabled.                                                       |
| checkCaching:css         | CSS preprocessing is disabled.                                                  |
| checkCaching:js          | JS preprocessing is disabled.                                                   |
| checkNvmExists           | NVM does not exist.                                                             |
|                          |                                                                                 |
|                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one |
|                          | machine.                                                                        |
|                          | Instructions for installing NVM can be found at:                                |
|                          |   https://github.com/creationix/nvm#installation                                |
| checkCiConfig            | Git remotes are set in project.yml.                                             |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                             |
| checkBehat:exists        | Behat local settings file exists.                                               |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                  |
|                          |   Behat base_url is set to "http://local.test.com".                   |
|                          |   Drush site URI is set to default.                                             |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                             |
| checkAcsfConfig          | BLT settings are included in your pre-settings-php include.                     |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                  |
+--------------------------+---------------------------------------------------------------------------------+

BUILD FINISHED; 13.2927 seconds

What are the steps to import database into local using blt ??

**Comment by grasmash** [comment] 2018-01-08 15:22
Please include the full command output for the failing command. The snippet that you shared does not contain adequate information.

**Comment by vishakha-s** [comment] 2018-01-09 06:15
Please see below output of blt local:setup command. 

This command fails and throws error at the end. Only few tables are getting imported in adminer.

blt local:setup
blt > local:setup:
blt > setup:git-hooks:
   [delete] Deleting: /home/vsharma/test/src/testglobal/.git/hooks/pre-commit
   [delete] Deleting: /home/vsharma/test/src/testglobal/.git/hooks/commit-msg
     [echo] Symlinking /home/vsharma/test/src/testglobal/.git/hooks/pre-commit to /home/vsharma/test/src/testglobal/vendor/acquia/blt/scripts/git-hooks/pre-commit
     [exec] 'pre-commit' -> '/home/vsharma/test/src/testglobal/vendor/acquia/blt/scripts/git-hooks/pre-commit'
     [exec] 'commit-msg' -> '/home/vsharma/test/src/testglobal/vendor/acquia/blt/scripts/git-hooks/commit-msg'
blt > setup:composer:install:
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
blt > setup:drupal:settings:
blt > setup:drupal:settings:site:
     [echo] Making /home/vsharma/test/src/testglobal/docroot/sites/default writable
    [chmod] Changed file mode on '/home/vsharma/test/src/testglobal/docroot/sites/default' to 755
     [echo] Making /home/vsharma/test/src/testglobal/docroot/sites/default/settings.php writable
    [chmod] Changed file mode on '/home/vsharma/test/src/testglobal/docroot/sites/default/settings.php' to 644
     [echo] Ensuring that blt.settings.php is required by settings.php
     [exec] require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
     [echo] Generating local settings files
blt > setup:behat:
     [copy] example.local.yml omitted, is up to date
blt > frontend:setup:
blt > target-hook:invoke:
     [echo] Executing command in /home/vsharma/test/src/testglobal/docroot/themes/custom/test_base_theme:
     [exec] Executing command: npm run setup

> waclassy@1.0.0 setup /home/vsharma/test/src/testglobal/docroot/themes/custom/test_base_theme
> npm install && bower install && npm --prefix ./homepage-video install ./homepage-video

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN waclassy@1.0.0 No repository field.
npm WARN waclassy@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN wa_homepage_hero@1.0.0 No description
npm WARN wa_homepage_hero@1.0.0 No repository field.
blt > frontend:build:
blt > target-hook:invoke:
     [echo] Executing command in /home/vsharma/test/src/testglobal/docroot/themes/custom/test_base_theme:
     [exec] Executing command: npm run build

> waclassy@1.0.0 build /home/vsharma/test/src/testglobal/docroot/themes/custom/test_base_theme
> gulp sass && cd homepage-video && gulp sass

[11:29:08] Using gulpfile ~/test/src/testglobal/docroot/themes/custom/test_base_theme/gulpfile.js
[11:29:08] Starting 'sass'...
WARNING: [Bourbon] [Deprecation] `em` is deprecated and will be removed in 5.0.0.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/functions/_px-to-em.scss:7, in function `em`
	node_modules/bourbon-neat/app/assets/stylesheets/settings/_grid.scss:25

WARNING: [Bourbon] [Deprecation] `animation` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_animation.scss:5, in mixin `animation`
	sass/modules/_homepage.scss:11

WARNING: [Bourbon] [Deprecation] `keyframes` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:3, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:98, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:15, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:101, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:15, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:98, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:23, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:101, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:23, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:98, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:35, in mixin `keyframes`
	sass/modules/_homepage.scss:96

WARNING: [Bourbon] [Deprecation] `transform` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss:2, in mixin `transform`
	sass/modules/_homepage.scss:101, in mixin `@content`
	node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss:35, in mixin `keyframes`
	sass/modules/_homepage.scss:96

[11:29:13] Finished 'sass' after 4.76 s
[11:29:19] Using gulpfile ~/test/src/testglobal/docroot/themes/custom/test_base_theme/homepage-video/gulpfile.js
[11:29:19] Starting 'sass'...
[11:29:20] Finished 'sass' after 465 ms
blt > frontend:
blt > setup:build:
blt > target-hook:invoke:
     [echo] Executing command in /home/vsharma/test/src/testglobal/docroot:
     [exec] Executing command: echo 'No post-setup build configured.'
No post-setup build configured.
blt > setup:drush:settings:
blt > setup:drush:settings:site:
    [chmod] Changed file mode on '/home/vsharma/test/src/testglobal/docroot/sites/default' to 755
[reflexive] Applying reflexive processing to 1 files.
blt > setup:hash-salt:
     [echo] Checking for hash salt in /home/vsharma/test/src/testglobal/salt.txt
     [echo] /home/vsharma/test/src/testglobal/salt.txt already exists.
blt > drupal:install:
     [echo] Installing Drupal...
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                               [ok]
Installation complete.                                                                                                                     [ok]
Congratulations, you installed test!                                                                                               [status]
blt > setup:config-import:
blt > target-hook:invoke:
     [echo] Executing command in /home/vsharma/test/src/testglobal/docroot:
     [exec] Executing command: echo 'No pre-config-import configured.'
No pre-config-import configured.
    [drush] 'drush' cache was cleared.                                             [success]
     [echo] Importing configuration...
    [drush] config is already enabled.                                                  [ok]
    [drush] There were no extensions that could be enabled.                             [ok]
    [drush] Cache rebuild complete.                                                     [ok]
    [drush] No database updates required                                           [success]
blt > setup:config-import:features:
    [drush] There are no changes to import.                                             [ok]
    [drush] features is already enabled.                                                [ok]
    [drush] There were no extensions that could be enabled.                             [ok]
    [drush] Cache rebuild complete.                                                     [ok]
blt > setup:update:features-import:
    [drush] Current state already matches active config, aborting.                      [ok]
blt > setup:update:features-import:
    [drush] Current state already matches active config, aborting.                      [ok]
blt > setup:update:features-import:
    [drush] Bundle test_test not found. Using default.                         [warning]
    [drush] Current state already matches active config, aborting.                      [ok]
blt > setup:update:features-import:
    [drush] Current state already matches active config, aborting.                      [ok]
blt > setup:update:features-import:
    [drush] Current state already matches active config, aborting.                      [ok]
blt > setup:update:features-import:
    [drush] Bundle test_test not found. Using default.                         [warning]
    [drush] Current state already matches active config, aborting.                      [ok]
    [drush] Cache rebuild complete.                                                     [ok]
blt > target-hook:invoke:
     [echo] No commands are defined for post-config-import. Skipping.
    [drush] Cache rebuild complete.                                                     [ok]
blt > setup:update:
blt > setup:toggle-modules:
    [drush] The following extensions will be enabled: dblog, devel, seckit, views_ui, styleguide, features_ui, filter_perms, field_ui, config_devel, test_donation_forms_test, real_aes, key, encrypt, test_webform_encrypt, clientside_validation_jquery, clientside_validation, webform_ui, test_forms, test_site_manager, test_donations, webform, test_newsletter_sign_up, test_js_search, media_entity_document, field_group_link, display_field_copy, test_feature_publications, test_feature_article, view_unpublished, test_feature_filtered_content, metatag_twitter_cards, datetime_range, test_feature_events, views_load_more, test_feature_get_involved, views_field_view, rh_taxonomy, test_base_taxonomy_vocabularies, test_base_menus, workbench_moderation, test_asset_bank, video_embed_media, video_embed_field, video, rh_media, rabbit_hole, media_entity_image, file_mdm_exif, file_mdm, imagemagick, entity_embed, entity_browser_entity_form, embed, test_base_media, image_effects, test_base_image_styles, viewsreference, view_mode_selector, view_mode_condition, telephone, social_media_links, sharethis, inline_entity_form, scheduled_updates, responsive_image, pathauto, paragraphs_colour, menu_link_attributes, entity, media_entity, maxlength, link_class, crop, focal_point, field_group, entity_browser, ds_extras, layout_discovery, ds, ctools, entity_reference_revisions, paragraphs, classy_paragraphs, block_visibility_groups, block_class, test_base_core, metatag, plugin, currency, test_donation_forms
    [drush] Do you really want to continue? (y/n): y
    [drush] exception 'Drupal\Core\Config\UnmetDependenciesException' with           [error]
    [drush] message 'Configuration objects provided by <em
    [drush] class="placeholder">test_base_media</em> have unmet dependencies:
    [drush] <em
    [drush] class="placeholder">core.entity_view_display.media.image.branding_image
    [drush] (responsive_image.styles.branding_image), embed.button.image
    [drush] (test_base_core), views.view.files (views_bulk_operations)</em>'
    [drush] in
    [drush] /var/www/testglobal/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
    [drush] Stack trace:
    [drush] #0
    [drush] /var/www/testglobal/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(480):
    [drush] Drupal\Core\Config\UnmetDependenciesException::create('test_base_m...',
    [drush] Array)
    [drush] #1
    [drush] /var/www/testglobal/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
    [drush] Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module',
    [drush] 'test_base_m...')
    [drush] #2
    [drush] /var/www/testglobal/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
    [drush] Drupal\Core\Extension\ModuleInstaller->install(Array, true)
    [drush] #3
    [drush] /var/www/testglobal/vendor/drush/drush/commands/core/drupal/environment.inc(143):
    [drush] Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
    [drush] true)
    [drush] #4
    [drush] /var/www/testglobal/vendor/drush/drush/commands/core/drupal/environment.inc(210):
    [drush] drush_module_install(Array)
    [drush] #5
    [drush] /var/www/testglobal/vendor/drush/drush/commands/pm/pm.drush.inc(1167):
    [drush] drush_module_enable(Array)
    [drush] #6 [internal function]: drush_pm_enable('dblog,devel,sec...')
    [drush] #7
    [drush] /var/www/testglobal/vendor/drush/drush/includes/command.inc(422):
    [drush] call_user_func_array('drush_pm_enable', Array)
    [drush] #8
    [drush] /var/www/testglobal/vendor/drush/drush/includes/command.inc(231):
    [drush] _drush_invoke_hooks(Array, Array)
    [drush] #9 [internal function]: drush_command('dblog,devel,sec...')
    [drush] #10
    [drush] /var/www/testglobal/vendor/drush/drush/includes/command.inc(199):
    [drush] call_user_func_array('drush_command', Array)
    [drush] #11
    [drush] /var/www/testglobal/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67):
    [drush] drush_dispatch(Array)
    [drush] #12
    [drush] /var/www/testglobal/vendor/drush/drush/includes/preflight.inc(66):
    [drush] Drush\Boot\BaseBoot->bootstrap_and_dispatch()
    [drush] #13 /var/www/testglobal/vendor/drush/drush/drush.php(12):
    [drush] drush_main()
    [drush] #14 {main}
**[phingcall] /home/vsharma/test/src/testglobal/./vendor/acquia/blt/phing/tasks/setup.xml:370:8: /home/vsharma/test/src/testglobal/./vendor/acquia/blt/phing/tasks/setup.xml:374:12: /home/vsharma/test/src/testglobal/./vendor/acquia/blt/phing/tasks/setup.xml:377:69: Drush exited with code 1
[phingcall] /home/vsharma/test/src/testglobal/./vendor/acquia/blt/phing/tasks/setup.xml:350:45: Execution of the target buildfile failed. Aborting.

BUILD FAILED/home/vsharma/test/src/testglobal/./vendor/acquia/blt/phing/tasks/local-sync.xml:12:30: Execution of the target buildfile failed. Aborting.
; 6 minutes  7.26 seconds**

**Comment by jayakrishnanj** [comment] 2018-01-09 08:16
Hi @vishakha-s ,
This seems to be an issue with config unmet dependency issue. Please check the config files are available in source code 
`core.entity_view_display.media.image.branding_image
[drush] (responsive_image.styles.branding_image), embed.button.image
[drush] (test_base_core), views.view.files `

**Comment by grasmash** [comment] 2018-01-10 14:50
Yup, this is Drupal core telling you that your exported configuration is invalid.

```
    [drush] exception 'Drupal\Core\Config\UnmetDependenciesException' with           [error]
    [drush] message 'Configuration objects provided by <em
    [drush] class="placeholder">test_base_media</em> have unmet dependencies:
    [drush] <em
    [drush] class="placeholder">core.entity_view_display.media.image.branding_image
    [drush] (responsive_image.styles.branding_image), embed.button.image
    [drush] (test_base_core), views.view.files (views_bulk_operations)</em>
```

You need to add the missing configuration. You can either remove`test_base_media` or else add its missing dependencies.

**Comment by vishakha-s** [comment] 2018-01-11 05:58
Thanks for suggestion. I disabled base_media module and then tried to run blt local:setup  command but still getting unmet dependencies error.

Could you please share steps to install unmet dependencies ?? Do i have to use drush commands??

**Comment by jayakrishnanj** [comment] 2018-01-11 08:05
1. Unmet dependencies are configuration files missing in the features or config export.
2. Without any contrib or custom modules if you are able to install Drupal 8 site, then it means BLT and drupal is working fine.
3. Issue reported in not related to BLT, so this ticket can be closed and your query can be debugged in Drupal forum.

**Comment by grasmash** [comment] 2018-01-12 15:12
> Could you please share steps to install unmet dependencies

That really depends on your site, its modules, and your configuration. You need to manually review the yml config files that contain the config with unmet dependencies. Read the dependencies, and very that they are all present in the configuration directory. If the are not, export them.

**Comment by grasmash** [comment] 2018-01-12 15:15
I'm closing this issue given that it is demonstrably caused by invalid Drupal configuration. 

Honestly, there should be a "Debugging configuration" page created here: https://www.drupal.org/docs/8/configuration-management/managing-your-sites-configuration

This is a common issue with Drupal 8, and there is a lack of support materials.

**Closed by grasmash** 2018-01-12 15:15 UTC
Labels: question / support
