### ISSUE TITLE
Documentation: More comprehensive CM docs

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#846] opened 2016-12-22 21:13 UTC
As a Drupal Developer who uses BLT I want more comprehensive configuration management (CM) documentation so that I can learn best practices.

**Comment by geerlingguy** [comment] 2016-12-22 21:56
Related to/duplicate of #854 ?

**Comment by grasmash** [comment] 2017-01-12 16:20
I'm going to consider this closed. The existing CM approach is well documented. Although, we may be introducing new CM approaches in #854. Documentation would accompany the PR for such a change.

**Closed** 2017-01-12 16:21 UTC
Labels: documentation, Prioritized
