### ISSUE TITLE
local.blt.yml does not get autogenerated in BLT v12

### ISSUE THREAD

**Issue by lgates** [acquia/blt#4231] opened 2020-08-25 22:48 UTC
**Describe the bug**
when running blt setup (first time setup on a newly forked project) local.blt.yml does not get generated using BLT v12 with Drupal 9.  You have to manually create the local.blt.yml file from the example.local.blt.yml file in order for blt setup to work. This bug appears to have been introduced with https://github.com/acquia/blt/pull/4140/files.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Clone https://github.com/Drupal4Gov/drupal4gov.us (not 100% sure if `composer create-project acquia/drupal-recommended-project --no-interaction` is setup for blt 12)
2. run blt setup
3. cd to blt and ll
4. no local.blt.yml file is present

**Expected behavior**
BLT setup on first time setup should create local.blt.yml for me.  If the local.blt.yml file is removed then local.blt.yml should be created on blt sync

**System information**
* Operating system type: Mac OS
* Operating system version: 10.15.6 (19G73)
* BLT version: 12.1.0

**Comment by mikemadison13** [comment] 2020-08-25 22:53
i can confirm this happens later in the process as well, if i manually delete local.blt.yml and re-run `blt setup` in BLT 12.x it doesn't get regenerated.

**Comment by benjifisher** [comment] 2020-08-26 14:25
IMO this is a feature, not a bug.

I have a project with Drupal 9 and BLT 12. I can create local sites, and I can deploy to ACSF. I track `blt/blt.yml` in the project's repository and I have an entry for `/blt/local/blt.yml` in `.gitignore`.

So far, the only time I need `blt/local.blt.yml` is if I want to switch between Lando and Drupal VM for the local development environment. Why do you want it to be managed by BLT?

**Comment by lgates** [comment] 2020-08-30 22:08
@benjifisher I'm not an expert at BLT, but all prior versions of BLT with Drupal 8 did create this file automatically.  Without it, my 'blt setup' cannot run for the first time.  If I don't manually create this file after cloning my repo, I get the following errors:

1. Lando does not start correctly

`lando start
Let's get this party started! Starting app drupal4gov...
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting drupal4gov_database_1 ... done
Starting drupal4gov_appserver_1 ... done
Scanning to determine which services are ready... Please standby...
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
mkdir: cannot create directory '/app': File exists
chown: cannot access '/app': No such file or directory
sh: 0: getcwd() failed: No such file or directory`

2. Blt setup fails

`Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 01:12
[error]  Failed to install Drupal!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `internal:drupal:install ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `drupal:install ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/`

While I do see you're point that this could be a feature, the first time setup should still be managed by BLT so that non-developers (e.g. site builders, testers, and ux/ui designers) can get up to speed faster in an local environment.

**Comment by benjifisher** [comment] 2020-08-31 13:44
These look like bugs:

1. Lando does not start correctly
2. Blt setup fails

I do not see why you think that the root cause is that BLT does not create `local.blt.yml`.

> the first time setup should still be managed by BLT so that non-developers (e.g. site builders, testers, and ux/ui designers) can get up to speed faster in an local environment.

I agree with this, but I still say that this can be done without `local.blt.yml`.

I have a different situation than yours: you started with BLT 11 and are trying to upgrade to BLT 12, but I am starting a new project with BLT 12 and Drupal 9. Here is an anonymized version of the setup instructions for my project:

---


    git clone ...
    cd ...
    lando start
    lando composer install
    lando blt setup

The first time it will take a bit to start, since it needs to download the base
docker images that are used. After the first time, `lando start` will be
quicker.

Once the site is installed, you should be able to visit it at
https://....lndo.site/.
Look for a line like this in the output:

> [success] Installation complete.  User name: DLMMHzLmNq  User password: 7cpAvVmp3W

You can use those credentials or use `lando drush @default uli` to get a one-time login link.

---

I suggest that you start with the errors from Lando. Make sure you have the latest version, then `lando rebuild -y -v` (maybe `-vv` or `-vvv`) and figure out what the problem is. If you post your `.lando.yml` file here, I will try to diagnose it.

**Comment by danepowell** [comment] 2020-08-31 23:07
The idea is that you can commit `example.local.blt.yml` and ignore `local.blt.yml`.

`example.local.blt.yml` contains anything you want to distribute by default within your project team, such as if you all use Lando and want to have default db string out of the box for new developers.

BLT uses `example.local.blt.yml` as a template to create `example.local.blt.yml` if `local.blt.yml` doesn't already exist.

I think we should restore this functionality.

**Comment by mikemadison13** [comment] 2020-08-31 23:15
FWIW @danepowell the project in question does have an example.local.blt file committed - https://github.com/Drupal4Gov/drupal4gov.us/blob/main/blt/example.local.blt.yml.

**Closed** 2020-09-04 21:59 UTC
Labels: Bug
