### ISSUE TITLE
blt artifact:deploy command doesn't run frontend build defined for non-default multisite

### ISSUE THREAD

**Issue by timwood** [acquia/blt#3143] opened 2018-10-04 03:19 UTC
My system information:
* Operating system type: Linux
* Operating system version: Ubuntu
* Environment: CI
* BLT version: 9.1.1

When the CI runs this command:
```
blt artifact:deploy
```

I get the following result:
* Only the frontend build processes from `docroot/sites/default/blt.yml` is performed.

And I expected this to happen:
* The frontend build process for all multisites defined in `blt/blt.yml` that have corresponding frontend hooks defined in `docroot/sites/SITENAME/blt.yml` to run and build the themes.

When using `blt setup` or `blt setup --site=SITENAME` locally, blt notices the frontend build in the site blt.yml and runs it.

**Proposed Enhancement**
Update the frontend hooks so they can be defined and run iteratively so that multiple commands can be run in different locations (e.g. themes and/or modules) to:
* better support multi-sites that use multiple themes
* better support any projects that have multiple front end requirements or locations that require different gulp / npm / yarn runs on *each* build

**Comment by sarahjean** [comment] 2018-10-04 12:42
@timwood the default assumption on node_modules is that it is used to compile css/js assets in the build and doesn't have things that need to be loaded on prod. You _can_ of course use it to pull in libraries you want to load up so you can customize your build to not ignore the folder. If you do this you should probably pay attention to what is set in package.json as dev dependencies so that you have a version of the build for prod that doesn't include those.

**Comment by timwood** [comment] 2018-10-04 12:59
@sarahjean Thanks. Any idea how to actually go about customizing the build to not ignore the folder?

**Comment by timwood** [comment] 2018-10-04 13:05
Also, any tips on getting the second site's theme to build?

**Comment by timwood** [comment] 2018-10-04 13:14
Assuming the [.gitignore](https://github.com/acquia/blt/blob/9.2.x/scripts/blt/deploy/.gitignore#L23) in BLT's `scripts/blt/deploy` folder is used when building the deploy artifact, wouldn't you want to include the `.css.map` files for example?

How exactly are [scripts/blt/deploy/deploy-exclude.txt](https://github.com/acquia/blt/blob/9.2.x/scripts/blt/deploy/deploy-exclude.txt) and `blt/deploy-exclude-additions.txt`used in the build / deploy process? It seems to include a lot of [things](https://github.com/acquia/blt/blob/9.2.x/scripts/blt/deploy/deploy-exclude.txt#L15) you'd want deployed.

**Comment by sarahjean** [comment] 2018-10-04 15:21
@timwood for multiple themes you can use a bash script and call that on blt.yml

**Comment by mikemadison13** [comment] 2018-11-09 18:07
@timwood is there something we can do to make this easier on you or a change to the docs based on your experience?

**Comment by mikemadison13** [comment] 2018-11-15 15:03
@timwood help me understand the use case please, so we can figure out how we might handle this? what does running a frontend hook per site get you?

my concern is this:
* the frontend hooks "usually" cannot run on the webserver. not all production servers have node / npm / yarn / gulp / etc. running on them, so many of the aspects of a frontend hook physically cannot be run in the same way as our other hooks (e.g. db updates, config import, etc.) on a site by site basis
* per the above, the frontend hooks all run during the build, prior to artifact generation. if you have multiple themes, you can actually run the frontend hook per theme (i can show you examples of this) but that is different than "per site"

**Comment by brooke-heaton** [comment] 2018-11-15 15:10
@mikemadison13 Just jumping in here since @timwood and I have the same needs and they are similar issues. I also use a number of front end task tools to build a PatternLab driven Bootstrap child theme - including those you mention. It runs perfectly fine so the issue isn't that the frontend hooks can't run - they do and they do perfectly well - it's that they must run for all sites in my multisite and can't be configured per site. 

I use two scripts to run the frontend-reqs and frontend-assets but these commands were clearly assuming a single site install and not multisite. 

blt/scripts/frontend-build.sh
blt/scripts/frontend-setup.sh

In my setup those two bash scripts run the frontend build for all the sites (e.g.):

```
#!/usr/bin/env bash

echo "running frontend build for naswa theme"
(cd docroot/themes/custom/naswa;npm run build)

echo "running frontend build for naswa_base theme"
(cd docroot/themes/custom/naswa_base/patternlab;npm run build;php core/console --generate;)
```

But since I can't override this per site, I just run the build for all sites within the scripts. I think @timwood  would like to target these per site - since nearly everything else in BLT can be customized per site in the multisite setup.

**Comment by mikemadison13** [comment] 2018-11-15 15:13
@brooke-heaton to be clear, you want these to run during your cloud deployments or locally? and to be clear, where you host is running the necessary tools for all the frontend build components to run in the cloud (the normal Acquia cloud doesn't have any of the needed components for npm, yarn, gulp, etc.).

**Comment by brooke-heaton** [comment] 2018-11-15 15:35
@mikemadison13 - well, to be clear, the build is running on Travis and the build artifacts are simply shipped to AC from Github - so I don't need them to run on AC - I need them to run on CI (Travis). Nevertheless I would assume the need to run the separately for each site could be accomodated, no?

**Comment by brooke-heaton** [comment] 2018-11-15 15:36
@timwood are you using a CI tool to run/compile your build artifacts?

**Comment by mikemadison13** [comment] 2018-11-15 15:37
probably yes @brooke-heaton  but that's what i'm trying to understand. travis doesn't do a multi-site build, it does a single build. do you have 1 theme per site?

**Comment by brooke-heaton** [comment] 2018-11-15 15:38
hmmm @mikemadison13 my configuration is running a multisite build on Travis. I'll have to dig up the specific configurations that run this.

**Comment by brooke-heaton** [comment] 2018-11-15 15:39
@mikemadison13 I believe this is how I am running the second build in `.travis.yml`

```
script:
  - blt sync --site=naswa_main
```

@timwood are you doing anything similar in `.travis.yml` ?

**Comment by mikemadison13** [comment] 2018-11-15 15:39
perhaps i misspoke, what i meant was, your build results in a single artifact, not multiple artifacts, correct? when it's done running, the result is a single artifact that gets committed to a single commit in the prod git repo?

**Comment by brooke-heaton** [comment] 2018-11-15 15:44
@mikemadison13 true. And I will say I personally don't need the separate frontend build. And I do see your point here. I prefer to run both frontend builds via the BLT commands and the scripts I mentioned. @timwood Per Mike's points - is there a situation where you would not want one of the sites frontend builds done -wouldn't that simply break the theme when deployed to Acquia (hopefully I'm paraphrasing Mike's point correctly)?

**Comment by brooke-heaton** [comment] 2018-11-15 15:45
@timwood or are you simply looking to target they WAY each of the frontend builds is done more granularly? I assume the latter.

**Comment by mikemadison13** [comment] 2018-11-15 15:45
^^ that's what i'm trying to understand what the desire is here, because running the same frontend hook in the same artifact multiple times just seems like a recipe for committing whatever the last thing that ran only

**Comment by brooke-heaton** [comment] 2018-11-15 15:46
Yea, I gotcha. The current process is working fine for me - I can tweak each frontend build in each bash script. But I think @timwood  may have a more specific need.

**Comment by brooke-heaton** [comment] 2018-11-15 15:47
Per your last comment @mikemadison13 that's a good point. I mean, I will say SPEED is a huge issue for me at the moment - builds are 13 mins each :/ so perhaps eliminating an unneeded frontend build would be helpful. ??

**Comment by mikemadison13** [comment] 2018-11-15 15:52
potentially yeah, if you're running frontend multiple times i could see that sucking up at least a couple of minutes of build time.

**Comment by timwood** [comment] 2018-11-15 16:47
We are building the deployment artifact with Gitlab CI. All the tools needed to build the entire artifact, including frontend build stuff, are in the docker image we use. If BLT allows/provides for per multisite override of commands, which works (running only the commands defined for each site) when running `blt setup` or `blt setup --site=SITENAME`, why would it act differently when running `blt artifact:deploy`? Why would it ignore any additional frontend build configuration at the per multisite level?

Ideally BLT should be flexible enough to configure the frontend build per multisite (which it is). This can save developers time when locally running `blt setup` against a single mulitsite. And still find and loop through frontend build steps defined per multisite when building the deployment artifact.

For now the workaround we implemented uses the `command-hooks.post-setup-build` and `command-hooks.post-deploy-build` hooks to call a shell script which builds all multisite themes. This means it "builds" both themes regardless of which site we are running `blt setup` against locally, adding some delay and overhead.

```yml
command-hooks:
  post-setup-build:
    dir: '${repo.root}'
    command: blt/scripts/build_themes.sh
  post-deploy-build:
    dir: '${repo.root}/deploy'
    command: blt/scripts/build_themes.sh
```

**Comment by mikemadison13** [comment] 2018-11-15 16:48
@timwood i think the critical different between a blt setup --site=SITENAME and a frontend hook, is that blt setup installs multiple databases, but it uses the same codebase. the artifact generation is still the same codebase (like modules, etc.) and there is no separate database to run against.

does that make sense?

**Comment by mikemadison13** [comment] 2018-11-15 16:49
i understand that you want the frontend hook to run for each site, i guess i continue to struggle to understand what that would accomplish if you have one theme. each time we ran it, it would update the "same theme" (since there is only one set of files).

**Comment by timwood** [comment] 2018-11-15 16:54
We use two separate themes, one for each multisite.

**Comment by mikemadison13** [comment] 2018-11-15 16:56
ok, so that is useful info to have. the method you posted above is the usual method i recommend, but i think that we have two potential things to look at here:
* multi-site (which is only useful if, like in your case you have multiple themes. my personal multi-site use case wouldn't benefit from anything here, since i have hundreds of sites all using the same theme)
* multi-location (which i have run into on multiple, single site projects) where i have multiple places in my codebase where i need my frontend hook to run. 

i still am not sure that we want this to automatically run for multi-site, because not all multi-sites have a theme for each site (and i think that's a dangerous assumption) but i DO think we can / should improve the frontend artifact hooks so that you can define multiple locations for them to run during the build process so that you don't have to hack in a shell script.

do you think that would meet your needs?

**Comment by timwood** [comment] 2018-11-15 17:00
If a multisite doesn't define anything in the frontend build config in it's blt.yml, BLT shouldn't automatically build anything for that site.

**Comment by mikemadison13** [comment] 2018-11-15 17:02
that's a dangerous path to set... my current multi-site project does NOT define "hundreds" of multi-sites in blt, because we aren't using config splits for each of the sites. i don't want to have to go through and add hundreds of sites in my blt.yml file to enable the frontend build script. this is part of the reason i'm proposing the ability to set multiple targets (and not making it multi-site aware). the themes themselves shouldn't be tied to a multi-site. if you have 1 theme, if you have 1k themes, you should be able to execute your frontend build script on all of them (or any number of them) regardless of how many actual drupal sites you have getting installed (multi-site or single site). 

IMHO.

**Comment by timwood** [comment] 2018-11-15 17:12
In your project's case, you would simply configure the frontend build command in `blt/blt.yml` for the shared theme, so you wouldn't have to add hundreds of sites to blt.yml.

Sounds like multiple targets, regardless of multisite awareness _could_ work. How would this solution account for the locally run, single multisite `blt setup` use case?

**Comment by mikemadison13** [comment] 2018-11-15 17:19
i think in that instance @timwood if you have a single site locally, but part of a mult-site project, blt would still run the frontend artifact on both of your themes. i see
pros:
* lets you enable whichever theme you want locally 
cons: 
* possibly compiling a second theme that you'll never need

**Comment by timwood** [comment] 2018-11-15 17:21
Sounds good.

**Comment by brooke-heaton** [comment] 2018-11-15 17:46
@mikemadison13 Yea, I would also add that we also use two different themes so the added overhead is certainly relevant in our case. I think building for speed is a serious issue for both @timwood and I and this is a case where BLT is just doing unnecessary work - at least locally.

**Comment by ngocketit** [comment] 2018-12-02 01:06
@timwood In your workaround, did you put these into the docroot `blt/blt.yml` or a sub-site `blt.yml` and why do you need to build theme in `post-deploy-build` hook because it's run after deployment artifact is already created?
```
command-hooks:
  post-setup-build:
    dir: '${repo.root}'
    command: blt/scripts/build_themes.sh
  post-deploy-build:
    dir: '${repo.root}/deploy'
    command: blt/scripts/build_themes.sh
```

**Comment by danepowell** [comment] 2019-03-19 22:06
While this would be nice to have, I can't think of an elegant solution that accommodates all users.

The best solution I can come up with is a hybrid where each site defines its theme in its own blt.yml, and BLT then consolidates these and intelligently decides which themes to build when installing a site, and builds _all_ themes when deploying. But that's a lot of additional complexity for users like Mike, as well as a lot of potential for things to go wrong with BLT, and a huge maintenance burden.

I'm adding this issue to the parking lot and closing for now, but if anyone can think of an incremental improvement that would make lives easier, let me know.

For now, the best practice here would be to define the `frontend-reqs` and `frontend-assets` hooks _either_ in each site's blt.yml (if you have a large number of sites/themes) or in the master blt.yml (if you have a limited number like Mike). If you choose the former, then add a `post-deploy-build` step to compile all themes for deployments.

**Closed by danepowell** 2019-03-19 22:06 UTC
Labels: 10.0.x, enhancement
