### ISSUE TITLE
Fatal Errors in Behat Builds / Not Failing Build

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3388] opened 2019-02-14 21:15 UTC
My system information:
* Operating system type: [replace]
* Operating system version: [replace]
* BLT version: 9.2.3 / 10.x Beta 2

When I run this command:
```
blt tests:behat
```

I get the following output:
```
Error: Call to a member function send() on null in /var/www/<project>/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php on line 420 #0 /var/www/<project>/vendor/behat/mink/src/Session.php(255): DMore\ChromeDriver\ChromeDriver->getScreenshot()
#1 /var/www/<project>/vendor/bex/behat-screenshot/src/Bex/Behat/ScreenshotExtension/Service/ScreenshotTaker.php(53): Behat\Mink\Session->getScreenshot()
#2 /var/www/<project>/vendor/bex/behat-screenshot/src/Bex/Behat/ScreenshotExtension/Listener/ScreenshotListener.php(83): Bex\Behat\ScreenshotExtension\Service\ScreenshotTaker->takeScreenshot()
#3 /var/www/<project>/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Bex\Behat\ScreenshotExtension\Listener\ScreenshotListener->takeScreenshot(Object(Behat\Behat\EventDispatcher\Event\AfterStepTested), 'tester.step_tes...', Object(Behat\Testwork\EventDispatcher\TestworkEventDispatcher))
#4 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php(39): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'tester.step_tes...', Object(Behat\Behat\EventDispatcher\Event\AfterStepTested))
#5 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(87): Behat\Testwork\EventDispatcher\TestworkEventDispatcher->dispatch('tester.step_tes...', Object(Behat\Behat\EventDispatcher\Event\AfterStepTested))
#6 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(62): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->tearDown(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false, Object(Behat\Behat\Tester\Result\ExecutedStepResult))
#7 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), true)
#8 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#9 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#10 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#11 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
#12 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#13 /var/www/<project>/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#14 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
#15 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#16 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#17 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
#18 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
#19 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
#20 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
#21 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
#22 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/<project>/vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/<project>/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/<project>/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/<project>/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/<project>/vendor/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/<project>/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
#29 {main}
Error: Call to a member function send() on null in DMore\ChromeDriver\ChromeDriver->getScreenshot() (line 420 of /var/www/<project>/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php).
```

And I expected this to happen:
The error above should cause a build failure. It just causes the command to error out and stop. In the context of a CI build, the build continues beyond this as if nothing had gone wrong.

**Comment by mikemadison13** [comment] 2019-02-14 21:15
to be clear, the above output is unrelated to blt itself. but it is output i got that didn't cause a failure!

**Comment by adrianthedev** [comment] 2019-02-18 13:12
I'm looking into it

**Comment by mikemadison13** [comment] 2019-03-18 17:53
This is related to the original solution posted here -https://github.com/acquia/blt/issues/3224 and is now occuring because of https://gitlab.com/DMore/chrome-mink-driver/issues/72

**Comment by mikemadison13** [comment] 2019-03-18 17:59
This may also be related to @danepowell's commentary and the original issue here - https://github.com/Behat/Behat/issues/842

**Comment by danepowell** [comment] 2019-03-18 18:05
To summarize the discussion in the link Mike posted above, and how it relates here:

I've seen this same behavior in relation to Lightning's tests that detect PHP / watchdog errors in an AfterScenario hook. Lightning throws an exception when the error is detected, but this doesn't actually stop or fail the Behat run, due to the fact that AfterScenario hooks can't actually stop or fail a test run: https://github.com/Behat/Behat/issues/842 .

It looks like the OP is the same root cause, since it's the screenshot-sending step (AfterStepTested?) that's crashing.

I don't know how we can fix this without fixing it in Behat first. I'm open to any ideas.

**Comment by danepowell** [comment] 2019-03-25 23:12
Unless someone can propose a fix for this, we may just have to remove the watchdog error-checking and screenshot functionality altogether in 10.0, since it looks like a BLT failure (even though it's really Behat not throwing a proper exit code).

**Comment by danepowell** [comment] 2019-04-02 00:39
This is obviously a terrible user experience, but it's not BLT's doing, and there's really nothing BLT can do to help it.

BLT doesn't provide any Behat contexts that make use of the AfterScenario steps (such as the screenshot or watchdog checks referenced above) that suffer from this. You must be getting those from another package such as Lightning: https://git.drupalcode.org/project/lightning_core/blob/8.x-4.x/tests/contexts/WatchdogContext.behat.inc#L46

And when those fail, it's due to the upstream Behat bug: https://github.com/Behat/Behat/issues/842

I would advise anyone experiencing this issue to follow up with whatever project is providing your failing steps, and/or urge the Behat maintainers to fix this upstream.

**Closed by danepowell** 2019-04-02 00:39 UTC
Labels: 10.x, 9.2.x, Bug

**Comment by danepowell** [comment] 2019-04-02 01:27
Actually, I just tried to reproduce this with the Lightning error-catching context, and it fails as expected. I wonder if something in Behat changed to fix this.

In which case, @mikemadison13 I suspect that there's something wrong with whatever context you are using that provides the call to getScreenshot(). I'd need to see your full output from `blt tests:behat` to be sure.

In my test case, the output ends with this, indicating that Behat properly failed due to the exception in the AfterScenario hook, and BLT properly recognized its non-zero exit code.
```
2 scenarios (2 passed)
4 steps (4 passed)
0m1.15s (19.08Mb)
[Testing\Behat]  Exit code 1 
[error]  Behat tests failed! 
```
I wonder if this is in your output too. If so, it indicates a problem with BLT. If not, it indicates a problem with whatever packages provides your test context.
