### ISSUE TITLE
BLT Upgrade to 8.9.0-beta4 Issues

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1707] opened 2017-06-21 04:36 UTC
Notes after upgrading from BLT 8.6.18 to 8.9.0-beta4...

* After I upgraded, I was getting Filesets errors because `blt/src/FileSets.php` did not exist. It appears you must run the `$ blt examples:init` command to create that file. Can we maybe check the class exists before using it?
* It seems `setup:toggle-modules` is no longer run as part of the `$ blt setup` command - is this by design? How do I set the $_ENV['environment'] variable that command is looking for? There is no more `$ blt local:setup` command that sets this for you (vs CI, etc)?
  * If I manually get it to run, the uninstall command is giving me an error that "--skip" is an unknown flag.
* Miscellaneous things...
  * So my project.yml had some oddities to it. I fixed some, but can't remember them all. I noticed that my `multisite.name: []` variable was not switched to the new `multisites: []` format.
  * `$ blt doctor` won't run for me on my macbook or my guest DrupalVM machine.

_I may add some more findings to this issue if I remember or encounter any others._

**Comment by grasmash** [comment] 2017-06-21 13:13
Thanks for the feedback @dpagini.

> I was getting Filesets errors

I can't seem to reproduce this error, even after removing my entire `blt/src` dir. What commands were you running?

>  How do I set the $_ENV['environment'] variable that command is looking for?

You can set any environment variable by adding `export environment=something` in a `~/.bash_profile` (or similar) or define it at runtime via `environment=something; blt setup:toggle-modules`. 

I could also add an argument to the `setup:toggle-modules` command so that you could execute `blt setup:toggle-modules --environment=something`.

> If I manually get it to run, the uninstall command is giving me an error that "--skip" is an unknown flag.

That's as bug, will resolve.

> I noticed that my multisite.name: [] variable was not switched to the new multisites: [] format.

I hadn't considered that you might hardcode that to project.yml. Will add to upgrade path.

> blt doctor won't run for me on my macbook or my guest DrupalVM machine.

Can you share the output of `blt doctor -vvv` ?

**Comment by grasmash** [comment] 2017-06-21 13:32
> There is no more $ blt local:setup command that sets this for you (vs CI, etc)?

Yes that is by design. You need to define environment specific variables in project.local.yml, command arguments, or environmental variables.

**Comment by dpagini** [comment] 2017-06-21 14:05
I realize I'm getting in here a little early, before any documentation, so sorry for all the questions. 

Re: 6d0e396 - you are fast, haha.

Re: Filesets errors...
So my error comes from `Acquia\Blt\Robo\Filesets\FilesetsManager` which has a use statement at the top for a class that _may_ not exist. I do have a custom fileset, which I have to set up, so maybe that's the only reason I was getting the error. I'll keep playing around with this and let you know.

> You can set any environment variable by adding export key=value in a ~/.bash_profile (or similar) or define it at runtime via key=value blt setup:toggle-modules.

Hmm... so I'll have to have the rest of the dev team add that `export key=value` to their profile files? Doesn't feel great to me. It seems like that "toggle-modules" command is the only one looking for that variable (right now?)... could we maybe do something to BLT < 8.9 where we set that to "local" by default, and it can be overridden for ci and dev/test/etc. I actually have a similar question for how I should have this set for Acquia environments? Maybe one of the AH_ variables can be used, but that feels like it should be done in the BLT hooks?

Maybe the one thing I'm struggling with is how `setup:toggle-modules` is intended to be called? It seems to me like it's a standalone command now, where before it ran at the end of the builds. Any thoughts there? I can attempt a fix for that, but just wanted to pick your brain for what you're thinking...?  Thanks.

> I hadn't considered that you might hardcode that to project.yml. Will add to upgrade path.

So I actually have 3 sites folders, one which is "all" for common settings. To ignore that folder for most commands, I "hard code" the sites to my other 2 folders. I'm actually running into other issues there, but I'll put up separate issues and attempt to fix those...  =)

### BLT Doctor Output
```sh
$ blt doctor -vvv
[Robo\Common\ProcessExecutor] Running vagrant status --machine-readable in /Users/dpagini/Projects/Websites/platform
[debug] Drupal VM is not initialized.
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush @voyaim.vm cc drush --uri=default --yes in /Users/dpagini/Projects/Websites/platform/docroot
'drush' cache was cleared.                                                                                                                          [success]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 4.192s
[debug] Drupal VM is not initialized.
Attempting to run doctor on host machine...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush @voyaim.vm blt-doctor --yes --include=/Users/dpagini/Projects/Websites/platform/vendor/acquia/blt/drush in /Users/dpagini/Projects/Websites/platform/docroot
[Acquia\Blt\Robo\Tasks\DrushTask]  The drush command 'blt-doctor' could not be found.  Run `drush           [error]
cache-clear drush` to clear the commandfile cache if you have
installed new extensions.  Time 4.775s
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 4.775s
[warning] Unable to run the doctor using alias '@voyaim.vm'. Trying with '@self'...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush @self blt-doctor --yes --include=/Users/dpagini/Projects/Websites/platform/vendor/acquia/blt/drush in /Users/dpagini/Projects/Websites/platform/docroot
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 2.666s
[warning] Unable to run the doctor using alias '@self'. Trying without alias...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush blt-doctor --yes --include=/Users/dpagini/Projects/Websites/platform/vendor/acquia/blt/drush in /Users/dpagini/Projects/Websites/platform/docroot
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 2.779s
[error]  Unable to execute the `blt doctor` command. 
```

**Comment by dpagini** [comment] 2017-06-21 14:09
> Yes that is by design. You need to define environment specific variables in project.local.yml, command arguments, or environmental variables.

Oh, so wait... my `blt/project.local.yml` file DOES have the "environment: local" name/value in there, but maybe because `setup:toggle-modules` is looking specifically at the Environment global, it's not reading it. Maybe that's the bug?

**Comment by grasmash** [comment] 2017-06-21 14:10
Yes, one that's resolved in #1708.

**Comment by grasmash** [comment] 2017-06-21 14:12
@dpagini I see that BLT tried to run
```
/Users/dpagini/Projects/Websites/platform/vendor/bin/drush @voyaim.vm blt-doctor --yes --include=/Users/dpagini/Projects/Websites/platform/vendor/acquia/blt/drush in /Users/dpagini/Projects/Websites/platform/docroot
```

Which, assuming your VM is booted, should have worked? Maybe we need to clear the drush caches _inside_ of the VM?

**Comment by grasmash** [comment] 2017-06-21 14:15
Also, I don't like those `Drupal VM is not initialized.` warnings. 

Can you share the output of `vagrant status --machine-readable` and your `'project.machine_name` ?

**Comment by dpagini** [comment] 2017-06-21 14:19
> Yes, one that's resolved in #1708.

🎉 like I said, you are too fast! Sorry, I should have seen that..!

I can explain the "not initialized" part. I moved my `box/config.yml` file to a non-standard place. Let me play around with this one too and see what I can figure out.

**Comment by dpagini** [comment] 2017-06-21 14:36
Ok, cool... my BLT "doctor" problems were my non-standard install. To be honest, I was trying to cut down on the amount of root folders... when you add Drupal-VM, SimpleSaml, and even some of the standard folders, the project grows. Bundle that with wanting to commit travis scripts, varnish VCL files, etc. in source control, I needed a place to put all these things. I created an `extras/` folder off my root and put a lot of the files/folders in there (including Drupal-VM). This is more of a feature request, but allowing those to be a little more configurable would be cool, but I realize I'm in the minority there.

Maybe an optional setting "project.install_path.drupal-vm"? Maybe it's something I can whip up a PR for one of these nights.

**Comment by grasmash** [comment] 2017-06-21 15:23
>  I do have a custom fileset, which I have to set up, so maybe that's the only reason I was getting the error.

And that custom file set is not in `blt/src/FileSets.php`?

**Comment by grasmash** [comment] 2017-06-21 15:26
Actually, we don't need that use statement since we have to use fully qualified namespaces with filesets, so I've removed it.

**Comment by grasmash** [comment] 2017-06-21 15:28
Yeah an entry in `blt.config-files` would be fine in a PR.

I think I've addressed all the other items in this issue. Closed via merge of PR.

**Closed** 2017-06-21 15:27 UTC
Labels: in progress
