### ISSUE TITLE
Can't deploy code on ACSF

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2708] opened 2018-04-03 13:18 UTC
My system information:
* BLT version: 9.0.5

I've run `recipes:acsf:init:all` on a fresh BLT 9 install and attempted to deploy the codebase to ACSF. This deploy failed with the error:
> Command "acsf-init-verify" is not defined

The problem seems to be that ACSF is using the Drush 9 binary provided with the project codebase (and required by BLT), and the ACSF module does not yet support Drush 9, so its commands cannot be found.

This is being actively worked on from the ACSF side (to support Drush 9), but until a fix is released, I'm wondering if there's a way for BLT to force ACSF to use Drush 8. Presumably this would have something to do with the Drush wrapper provided by BLT, but I'm not really sure.

**Comment by grasmash** [comment] 2018-04-04 15:48
This is basically a bug in ACSF. I don't know that it's worthwhile to find a fix in BLT--it would be extremely hacky.

**Comment by danepowell** [comment] 2018-04-04 21:34
Agreed. But until it's fixed in ACSF it's basically impossible to deploy any version of BLT on ACSF. So you know... rock, meet hard place...

**Comment by dgpalmer** [comment] 2018-04-05 21:56
I am experiencing the same issue Dane, extremely frustrating. We have a tight timeline that we are goin to miss because of this.

I wish Acquia would take more responsibility regarding quality control with the ACSF modules and compatibility with BLT.

**Comment by crotown** [comment] 2018-04-06 20:31
I am no expert in BLT, but it seems that the answer to forcing Drush 8 in BLT might be build on to the answer for having drush version specified in drush remote aliases, described in  in https://docs.acquia.com/acquia-cloud/drush .

**Comment by danepowell** [comment] 2018-04-06 21:45
We've worked around this by essentially maintaining side-by-side versions of Drush in the deploy artifact, but it's a pretty touchy solution since various caches and configuration on the ACSF side seem to interfere with Drush dispatching. @lcatlett said she'd open a PR with our changes shortly. At the very least, maybe we can document them here or on a wiki page.

**Comment by danepowell** [comment] 2018-04-10 15:09
I've started a wiki page to document our workarounds: https://github.com/acquia/blt/wiki/ACSF,-BLT-9,-and-Drush-9-compatibility

As Lindsey has time, she may contribute some of these back. However, many of the workarounds are pretty hacky and I'm not sure we want them permanently in the codebase. Still, we should have _some_ sort of solution for folks, even if it's code they add themselves.

**Comment by grasmash** [comment] 2018-04-12 18:34
Closing as duplicate of https://github.com/acquia/blt/issues/2731

**Closed by grasmash** 2018-04-12 18:34 UTC
Labels: acsf, bug, duplicate
