### ISSUE TITLE
Features to be enabled and reverted before Executing config import

### ISSUE THREAD

**Issue by vaibhavjain-in** [acquia/blt#450] opened 2016-09-23 15:49 UTC
The current BLT integration executes Db updates and then enable and revert features.
In "setup:update", should we enable and revert the features before config import and executing Db updates ?
Reason 1 : We are using lightning, and it adds its own set of features, which we do not want, and we are removing it in the config. As of now, configs are imported first, and the Db updates are executes. Post this features are enabled and reverted, which causes some configs created by features to come back, and override what we want. Thus, failing the builds, as our test cases wont pass.
Reason 2 : This might be another reason I would like features to be enabled and reverted before config and db updates. If I add some update hooks to any of the feature, it will not be called, some  changes will not be incorporated during builds.

I am not very sure if the order is done some specific reason.

**Comment by grasmash** [comment] 2016-09-23 15:52
Sounds fine to me. @danepowell @aweingarten would be most likely to know if this might be problematic.

**Comment by vaibhavjain-in** [comment] 2016-09-23 16:46
Cool, if we are good to go, here is the PR - https://github.com/acquia/blt/pull/453

**Comment by greylabel** [comment] 2016-09-23 20:18
One best-practice in D7, which should hold true in D8, is to run database update hooks (`updb`) before running any config revert tasks (`fra`). The reason for this is you may need to make schema changes in `updb` that your configuration changes will depend on before they can be implemented successfully with `fra`. I think the order in which you run `config-import` vs `fra` more depends on which you want to take precedence in your individual use case/dev workflow.

**Comment by danepowell** [comment] 2016-09-26 14:58
@greylabel nailed it, you always want to run updb _before_ fra. Schema updates must always happen first.

@vaibhavjain-in it sounds like your use case might be better addressed by https://github.com/balsama/acme-lightning-extend

**Comment by grasmash** [comment] 2016-09-26 19:17
Given feedback from @greylabel and @danepowell, it seems that it would not be prudent to merge this change. This should be handled in project-specific update hook when the need arises.

Closing.

**Closed by grasmash** 2016-09-26 19:17 UTC
Labels: wontfix

**Comment by vaibhavjain-in** [comment] 2016-09-27 04:36
Yes, it looks to more of a project specific need, and how you design it your project.
@danepowell correct me If I am wrong here. If we add a module to be installed after lightning is installed (delete additional roles), that may not help here, because, we are doing `fra`, which will revert the changes that we have made after lightning installation, via our custom module.

**Comment by danepowell** [comment] 2016-09-27 19:43
I chatted with @vaibhavjain-in in Hipchat, it sounds like the root cause of this request is the fact that most projects will want to override default config provided by Lightning (a totally valid use case) and that's hard to do when running fra imports Lightning's defaults every time. This is definitely a problem that needs to be solved, but I'm thinking there are better ways than this particular implementation (Lightning clobbering your site's config, then your site unclobbering it with a config import). I'll think about this and open a new issue or PR.
