### ISSUE TITLE
 Attempt to fix violations automatically via PHPCBF -  Not working

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/blt#3751] opened 2019-07-15 05:59 UTC
**Describe the bug**
Tried to validate and fix the custom code by executing `blt tests:phpcs:sniff:all` phpcbf failed with the error message

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `blt tests:phpcs:sniff:all`
2. Enter y on 'Attempt to fix violations automatically via PHPCBF? (y/n)'
3. See error

**Expected behavior**

**Detailed error output**
` Attempt to fix violations automatically via PHPCBF? (y/n) y
> source:fix:php-standards
Fixing and beautifying code...
[Exec] Running /var/www/coding/vendor/bin/phpcbf in /var/www/coding
...............PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Uninitialized string offset: 0 in /var/www/coding/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php on line 224 in /var/www/coding/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /var/www/coding/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php(224): PHP_CodeSniffer\Runner->handleErrors(8, 'Uninitialized s...', '/var/www/coding...', 224, Array)
#1 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Files/File.php(489): Drupal\Sniffs\Commenting\DocCommentSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 68)
#2 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(48): PHP_CodeSniffer\Fixer->fixFile()
#5 /var/www/coding/vendor/squ in /var/www/coding/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Uninitialized string offset: 0 in /var/www/coding/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php on line 224 in /var/www/coding/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /var/www/coding/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/Commenting/DocCommentSniff.php(224): PHP_CodeSniffer\Runner->handleErrors(8, 'Uninitialized s...', '/var/www/coding...', 224, Array)
#1 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Files/File.php(489): Drupal\Sniffs\Commenting\DocCommentSniff->process(Object(PHP_CodeSniffer\Files\LocalFile), 68)
#2 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 /var/www/coding/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(48): PHP_CodeSniffer\Fixer->fixFile()
#5 /var/www/coding/vendor/squ in /var/www/coding/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
[Exec]  Exit code 255  Time 0.274s
[error]  PHPCBF failed.
[error]  Command `source:fix:php-standards ` exited with code 1.`

**BLT doctor output**
Post the full output of `+---------------------------+-------------------------------------------------------+
| Property                  | Value                                                 |
+---------------------------+-------------------------------------------------------+
| %paths.%root              | /var/www/coding/docroot                               |
| %paths.%site              | sites/default                                         |
| %paths.%modules           | sites/all/modules                                     |
| %paths.%themes            | sites/all/themes                                      |
| %paths.%config-sync       | /var/www/coding/config/default                        |
| %paths.%files             | sites/default/files                                   |
| %paths.%temp              | /tmp                                                  |
| %paths.%private           | /var/www/coding/files-private                         |
| admin-theme               | seven                                                 |
| alias-searchpaths.0       | /var/www/coding/drush/sites                           |
| blt-version               | 10.2.0                                                |
| bootstrap                 | Successful                                            |
| composer-version          | Composer version 1.8.5 2019-04-09 17:46:47            |
| config-sync               | /var/www/coding/config/default                        |
| db-driver                 | mysql                                                 |
| db-hostname               | localhost                                             |
| db-name                   | drupal                                                |
| db-password               | drupal                                                |
| db-port                   | 3306                                                  |
| db-status                 | Connected                                             |
| db-username               | drupal                                                |
| drupal-settings-file      | sites/default/settings.php                            |
| drupal-version            | 8.7.4                                                 |
| drush-alias-files.0       | /var/www/coding/drush/sites/coding.site.yml           |
| drush-cache-directory     | /home/vagrant/.drush/cache                            |
| drush-conf.0              | /var/www/coding/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/coding/drush/drush.yml                       |
| drush-conf.2              | /var/www/coding/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/coding/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                                  |
| drush-version             | 9.7.1                                                 |
| files                     | sites/default/files                                   |
| install-profile           | lightning                                             |
| modules                   | sites/all/modules                                     |
| php-bin                   | /usr/bin/php7.2                                       |
| php-conf.0                | /etc/php/7.2/cli/php.ini                              |
| php-os                    | Linux                                                 |
| private                   | /var/www/coding/files-private                         |
| root                      | /var/www/coding/docroot                               |
| site                      | sites/default                                         |
| stacks.drupal-vm.inited   | true                                                  |
| stacks.dev-desktop.inited | false                                                 |
| temp                      | /tmp                                                  |
| theme                     | bartik                                                |
| themes                    | sites/all/themes                                      |
| uri                       | http://local.blted10.com                              |
+---------------------------+-------------------------------------------------------+` 

**System information**
* Operating system type:  [MAC]
* Operating system version: [10.14.5]
* BLT version: [10.2.0]

**Comment by danepowell** [comment] 2019-07-16 17:04
I cannot reproduce this. Is it specific to a certain type of PHPCS violation? If so, could it be a bug in the coder module?

Can you provide steps to reproduce from a fresh install of BLT (starting with `composer create-project acquia/blt-project --no-interaction`)

**Comment by danepowell** [comment] 2019-07-16 17:05
Output from my test:
```
blt tests:phpcs:sniff:all
[ExecStack] /Users/dane/sites/blt-canary/vendor/bin/phpcs
[ExecStack] Running /Users/dane/sites/blt-canary/vendor/bin/phpcs in /Users/dane/sites/blt-canary
...E. 5 / 5 (100%)



FILE: /Users/dane/sites/blt-canary/docroot/modules/custom/something/something.module
------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
------------------------------------------------------------------------------------
 1 | ERROR | [x] The PHP open tag must be followed by exactly one blank line
 1 | ERROR | [x] Missing file doc comment
------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------

Time: 143ms; Memory: 8MB

[ExecStack]  Exit code 2  Time 0.244s
 Attempt to fix violations automatically via PHPCBF? (y/n) y
> source:fix:php-standards
Fixing and beautifying code...
[Exec] Running /Users/dane/sites/blt-canary/vendor/bin/phpcbf in /Users/dane/sites/blt-canary
...F. 5 / 5 (100%)



PHPCBF RESULT SUMMARY
---------------------------------------------------------------------------------------------------
FILE                                                                               FIXED  REMAINING
---------------------------------------------------------------------------------------------------
/Users/dane/sites/blt-canary/docroot/modules/custom/something/something.module     2      1
---------------------------------------------------------------------------------------------------
A TOTAL OF 2 ERRORS WERE FIXED IN 1 FILE
---------------------------------------------------------------------------------------------------

Time: 149ms; Memory: 10M
```

**Comment by jayakrishnanj** [comment] 2019-07-17 06:43
No issues with default BLT Docroot as well. 
Have a custom module which is breaking the phpcs and phpcbf,.

**Comment by danepowell** [comment] 2019-07-17 20:49
Okay closing this since you've found a custom module causing the problem. Let me know if you find a problem with BLT.

**Closed by danepowell** 2019-07-17 20:49 UTC
Labels: Support
