### ISSUE TITLE
BLT 10.0.1 error with ComposerCheck:composer.autoload.psr-4 and ComposerCheck:composer.extra.installer-paths 

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#3664] opened 2019-05-20 10:36 UTC
I updated BLT for my existing project from 9.2.x to 10.0.1. With the previous version I had no error showing on running `blt doctor`. Now there are couple of newly introduced errors are seen & I am not sure which configuration I need to change to fix these issues.

I checked my composer.json file located project root where I saw the following lines related to the BLT doctor errors. 

> "autoload": {
        "psr-4": {
            "Acquia\\Blt\\Custom\\": "blt/src/"
        }
    },
    "extra": {
        "enable-patching": true,
        "installer-types": [
            "bower-asset",
            "npm-asset"
        ],
        "installer-paths": {
            "docroot/core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/modules/custom/{$name}": [
                "type:drupal-custom-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/profiles/custom/{$name}": [
                "type:drupal-custom-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "docroot/themes/custom/{$name}": [
                "type:drupal-custom-theme"
            ],
            "docroot/libraries/{$name}": [
                "type:drupal-library",
                "type:bower-asset",
                "type:npm-asset"
            ],
            "drush/Commands/{$name}": [
                "type:drupal-drush",
                "type:drupal-drush"
            ]
        },

**BLT doctor output**
<img width="803" alt="Screenshot 2019-05-20 at 3 57 20 PM" src="https://user-images.githubusercontent.com/6311767/58015095-fb2ceb00-7b17-11e9-901b-54ed26949cce.png">

**System information**
* Operating system type: Mac OS
* Operating system version: 10.14.5
* BLT version: 10.0.1

Can anyone please help me to resolve this issue. Thanks in advance!

**Comment by sandipsmarty** [comment] 2019-05-20 13:36
@danepowell : Please share if you have any suggestion?

**Comment by danepowell** [comment] 2019-05-20 22:22
Your composer.json does appear to be malformed. For instance, your PSR4 namespace is using "Custom" instead of "Example", and you have a duplicate entry for the Drush commands installer path.

Compare to the reference composer.json here, as the doctor suggests:

https://github.com/acquia/blt-project/blob/35e424203f60cf082a28feddf948e6577541266e/composer.json#L80-L84

https://github.com/acquia/blt-project/blob/35e424203f60cf082a28feddf948e6577541266e/composer.json#L67-L69

What led you to believe that this was a false positive? Is there anything we could do to make it more clear what the problem is?

**Comment by sandipsmarty** [comment] 2019-05-21 07:19
@danepowell : I just fixed my composer json file to match BLT's default value, now I don't see any critical errors on running `blt doctor`, but I wonder how the malformed composer.json file was working with my previous BLT version 9.2.x and that time these errors were not showing.

**Comment by danepowell** [comment] 2019-05-21 14:25
The equivalent check didn't exist in 9.2.x. You can see that it was only added here and released in 10.0.0: https://github.com/acquia/blt/commit/2b9c0a6690b8eb3e78ff66c7fe80c91c84133441#diff-7066cb8dbb9a735022ee49243147f24dR140

It sounds like that should resolve this issue, if you have additional questions feel free to reply and I can reopen it.

**Closed by danepowell** 2019-05-21 14:25 UTC
Labels: Support

**Comment by sandipsmarty** [comment] 2019-05-22 08:36
Understood. Thanks @danepowell !
