### ISSUE TITLE
Updating dependencies (including require-dev)

### ISSUE THREAD

**Issue by Momodoujobe** [acquia/blt#3354] opened 2019-01-30 22:03 UTC
My system information:
* Operating system type: [replace] Windows
* Operating system version: [replace] Windows 10 Pro
* BLT version: [replace]
I am trying to install BLT while using babun. I ran this command "fin run-cli composer create-project --no-interaction acquia/blt-project myproject"
Output of `blt doctor`:
```
It kept getting stuck to "Loading composer repositories with package information
Updating dependencies (including require-dev)
" for over 2 hours now and I am not sure why
```
![image](https://user-images.githubusercontent.com/46496452/52015846-eff27880-24b0-11e9-93b7-d0b91555f34d.png)

When I run this command:
```
[replace with command, add -vvv for very very verbose output.]
```

I get the following output:
```
[replace with ENTIRE command output. DO NOT enter partial output.]
```

And I expected this to happen:

**Comment by mikemadison13** [comment] 2019-01-30 22:31
Hi @Momodoujobe it sounds like you are running the composer command inside of a Docksal VM? In my experience, running  composer commands inside a VM (particularly a long running composer command such as the initial project creation script) can have VERY slow consequences.

I would recommend doing all the composer junk to setup a new BLT project first from your host machine, and THEN add docksal to that project (instead of the other way around). See https://github.com/acquia/blt/blob/10.0.x/docs/alternative-environment-tips/docksal.md

**Comment by Momodoujobe** [comment] 2019-01-31 13:49
After running the fin blt doctor, it showed me some errors 


![image](https://user-images.githubusercontent.com/46496452/52058250-0b06cc00-2535-11e9-8ac0-29ffac8cc358.png)

**Comment by Momodoujobe** [comment] 2019-01-31 15:47
![image](https://user-images.githubusercontent.com/46496452/52065931-8bcdc400-2545-11e9-9c28-1466eeb385f6.png)

**Comment by mikemadison13** [comment] 2019-01-31 17:55
those errors are to be expected, if the composer process wasn't completed. IF composer completed AND you completed the blt setup process, then the errors are concerning. if not, we should focus on getting that done first and then see if they are still a factor.

**Comment by Momodoujobe** [comment] 2019-01-31 17:57
composer seems to be working fine on it

**Comment by mikemadison13** [comment] 2019-01-31 17:58
ok, because the original issue you posted said composer wasn't working. so the issue we need to figure out is actually the doctor errors? did you run BLT setup?

**Comment by Momodoujobe** [comment] 2019-01-31 18:40
Yes please, because I install composer and is working perfectly 
![image](https://user-images.githubusercontent.com/46496452/52076917-c6dbf180-255d-11e9-912c-cd061a898dae.png)

**Comment by Momodoujobe** [comment] 2019-01-31 18:42
this is my issue now

![image](https://user-images.githubusercontent.com/46496452/52077064-0f93aa80-255e-11e9-91f6-1e8e5ccc4d31.png)

**Comment by mikemadison13** [comment] 2019-01-31 18:43
have you run blt setup from inside the vm?

**Comment by mikemadison13** [comment] 2019-01-31 19:38
so it looks like you have 2 things going on.

one is that you are missing some composer items (the installer paths item). you should make sure that your composer.json file matches the basic project composer.json file (see https://github.com/acquia/blt/blob/9.2.x/template/composer.json).

second, if you're getting a mysql is not available error, this is frequently caused by drush alias issues. what is your blt.yml file set as your local / default alias?

**Comment by Momodoujobe** [comment] 2019-01-31 19:48
so I opened my composer.json file that is in my blt-project folder 

![image](https://user-images.githubusercontent.com/46496452/52080976-1377fa80-2567-11e9-9788-a80991a18b78.png)

this is the only thing that is in there. 

![image](https://user-images.githubusercontent.com/46496452/52081015-28ed2480-2567-11e9-9d4e-0b162184f2b5.png)

should delete it and replace the code with 

{
    "license": "proprietary",
    "type": "project",
    "config": {
        "sort-packages": true
    },
    "require": {},
    "require-dev": {},
    "extra": {
        "enable-patching": true,
        "installer-types": ["bower-asset", "npm-asset"],
        "installer-paths": {
            "docroot/core": ["type:drupal-core"],
            "docroot/modules/contrib/{$name}": ["type:drupal-module"],
            "docroot/modules/custom/{$name}": ["type:drupal-custom-module"],
            "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
            "docroot/profiles/custom/{$name}": ["type:drupal-custom-profile"],
            "docroot/themes/contrib/{$name}": ["type:drupal-theme"],
            "docroot/themes/custom/{$name}": ["type:drupal-custom-theme"],
            "docroot/libraries/{$name}": ["type:drupal-library", "type:bower-asset", "type:npm-asset"],
            "drush/Commands/{$name}": ["type:drupal-drush"]
        },
        "merge-plugin": {
            "require": [
                "blt/composer.required.json",
                "blt/composer.suggested.json"
            ],
            "merge-extra": true,
            "merge-extra-deep": true,
            "merge-scripts": true,
            "replace": false,
            "ignore-duplicates": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by mikemadison13** [comment] 2019-01-31 19:50
yeah, so this gets back to the original issue. your composer didn't install properly. you don't really have a full blt project. 

what do you get if you run composer update from inside the project? you may have to delete it and start over, because your original composer issues caused all of this to fail.

**Comment by Momodoujobe** [comment] 2019-01-31 19:55
so I decided to comment it out and upload the new code 

![image](https://user-images.githubusercontent.com/46496452/52081384-1fb08780-2568-11e9-80fb-f5965032d1b1.png)

but what I realize is I do not have a docroot folder in my project folder.

**Comment by Momodoujobe** [comment] 2019-01-31 19:57
I ran the composer update command and this is the output

![image](https://user-images.githubusercontent.com/46496452/52081553-803fc480-2568-11e9-8ac8-844f28bee892.png)

**Comment by mikemadison13** [comment] 2019-01-31 19:57
don't comment it out, that is going to lead to an incredible amount of pain. i would recommend just deleting this project folder and re-running the initial create project script so composer can do its thing. the docroot folder will appear once composer fully runs.

**Comment by Momodoujobe** [comment] 2019-01-31 19:59
what is the correct command? I am on a windows pc using babun. I keep seeing different composer commands.

**Comment by Momodoujobe** [comment] 2019-01-31 20:00
This is the command that Ii have been using composer create-project --no-interaction acquia/blt-project blt-project is it correct?

**Comment by mikemadison13** [comment] 2019-01-31 20:00
So, after you delete this project.

`composer create-project --no-interaction acquia/blt-project my-project`

https://blt.readthedocs.io/en/latest/creating-new-project/


That process will take some time (depending on your connection, etc.) but the end result should be a fully fledged BLT project that includes all the necessary packages for Drupal, etc.

**Comment by Momodoujobe** [comment] 2019-01-31 20:08
After running this command it is complete 
![image](https://user-images.githubusercontent.com/46496452/52082155-01e42200-256a-11e9-8e4f-d31866018f9e.png)

**Comment by Momodoujobe** [comment] 2019-01-31 20:11
I cd my-project and then I ran this command composer require acquia/headless_lightning:~1.1.0

**Comment by Momodoujobe** [comment] 2019-01-31 20:13
it gave me this output

![image](https://user-images.githubusercontent.com/46496452/52082423-b716da00-256a-11e9-8db9-d6801152ac8c.png)

**Comment by Momodoujobe** [comment] 2019-01-31 20:14
when I opened composer.json file in this project it shows the same thing

![image](https://user-images.githubusercontent.com/46496452/52082499-ed545980-256a-11e9-9db2-6523cec4f4c5.png)

**Comment by Momodoujobe** [comment] 2019-01-31 20:36
for some reason, mine is not completing mine stops after 

Generating autoload files
Copying C:/Users/Mjobe/projects/BLT-Project/vendor\acquia/blt\composer.required.json to C:/Users/Mjobe/projects/BLT-Project\blt\composer.required.json. Do not modify this file. To override BLT dependencies, see readme/dependency-management.md.
Copying C:/Users/Mjobe/projects/BLT-Project/vendor\acquia/blt\composer.suggested.json to C:/Users/Mjobe/projects/BLT-Project\blt\composer.suggested.json. Do not modify this file. To override BLT dependencies, see readme/dependency-management.md.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Creating BLT templated files...
 > C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi
'C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt' is not recognized as an internal or external command,
operable program or batch file.
BLT installation failed! Please execute C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.

**Comment by Momodoujobe** [comment] 2019-01-31 20:37
![image](https://user-images.githubusercontent.com/46496452/52083694-280bc100-256e-11e9-8a92-1f69f6588c7d.png)
 "BLT installation failed! Please execute C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
"

**Comment by mikemadison13** [comment] 2019-01-31 20:41
yeah, so i think the issue here has to do with the actual blt command failing to run. have you followed the instructions for setting things up on windows? https://blt.readthedocs.io/en/latest/windows-install/ 


my knowledge of troubleshooting on the windows side is VERY limited, i haven't actually tried.

**Comment by Momodoujobe** [comment] 2019-01-31 20:44
I did and I have a drupal8 site running on docksal and everything is fine but BLT  is giving me a hard time. Windows also give me a hard time with these programs.

**Comment by Momodoujobe** [comment] 2019-01-31 20:56
I ran 
 C:/Users/Mjobe/projects/BLT-Project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose

![image](https://user-images.githubusercontent.com/46496452/52084736-c0a34080-2570-11e9-8358-0b83c385cdd0.png)

**Comment by mikemadison13** [comment] 2019-01-31 21:08
maybe a permissions issue at the OS level? can you ensure that the directories are writable?

**Comment by Momodoujobe** [comment] 2019-01-31 21:16
I check but I haven't been able to figure any directories that are not writable. Thank you for your help.

**Comment by mikemadison13** [comment] 2019-02-04 15:45
closing in favor of https://github.com/acquia/blt/issues/3359

**Closed by mikemadison13** 2019-02-04 15:45 UTC
Labels: question / support
