### ISSUE TITLE
Fails on applying patch

### ISSUE THREAD

**Issue by snize** [acquia/blt#1380] opened 2017-04-14 08:28 UTC
My system information:
* Operating system type: macOS
* Operating system version: 10.12.4
* BLT version: 8.8.1

When I run this command:
```
composer install
```
Even fails on `blt build:deploy` and `composer create-project --no-interaction acquia/blt-project MY_PROJECT`

I get the following output:
```
Gathering patches for root package.
Removing package drupal/memcache so that it can be re-installed and re-patched.
Deleting docroot/modules/contrib/memcache - deleted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/memcache (dev-2.x fb3e4ff)
    Cloning fb3e4ff2b9e5610a36241595a0b6267e2e510cb3 from cache

  - Applying patches for drupal/memcache
    https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch (SASL Support in Drupal 8 version)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch

                                                                                                                            
  [Exception]                                                                                                               
  Cannot apply patch SASL Support in Drupal 8 version (https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch)!  
                                                                                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by dougvann** [comment] 2017-04-14 14:36
Same error here with slightly different output generated by "composer create-project acquia/blt-project blt1"
Mac OS 10.12.3
BLT 8.8.1
Screenshot = https://screencast.com/t/r0GBwyUs
```
  - Installing drupal/core (8.3.0): Loading from cache
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/no_reliable_method-2752961-29.patch (Clear Twig caches on deploys)
    https://www.drupal.org/files/issues/2652138-41.patch (2652138 - ImageFormatter does not support SVGs)
    https://www.drupal.org/files/issues/1356276-303.patch (1356276 - Allow profiles to provide a base/parent profile and load them in the correct order)

  - Installing symfony/dom-crawler (v3.2.7): Loading from cache
  - Installing symfony/css-selector (v3.2.7): Loading from cache
  - Installing symfony/browser-kit (v3.2.7): Loading from cache
  - Installing fabpot/goutte (v3.2.1): Loading from cache
  - Installing behat/mink (v1.7.1): Loading from cache
  - Installing behat/mink-browserkit-driver (v1.3.2): Loading from cache
  - Installing behat/mink-goutte-driver (v1.2.1): Loading from cache
  - Installing drupal/memcache (dev-2.x fb3e4ff): Cloning fb3e4ff2b9 from cache
  - Applying patches for drupal/memcache
    https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch (SASL Support in Drupal 8 version)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch                                                                                                                    
  [Exception]                                                                                                               
  Cannot apply patch SASL Support in Drupal 8 version (https://www.drupal.org/files/issues/sasl_drupal_8-2862230-3.patch)!  
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

[phingcall] /Users/dougvann/Sites/bltONE/blt1/./vendor/acquia/blt/phing/tasks/blt.xml:55:165: Task exited with code 1

BUILD FAILED/Users/dougvann/Sites/bltONE/blt1/./vendor/acquia/blt/phing/tasks/blt.xml:12:37: Execution of the target buildfile failed. Aborting.
; 3 minutes  36.49 seconds
```

**Comment by justclint** [comment] 2017-04-14 15:06
Im having the same problem. I think this issue is a duplicate of https://github.com/acquia/blt/issues/1325

**Comment by grasmash** [comment] 2017-04-14 16:37
This is due to an upstream commit in the memcache module, which caused patch application to fail. This has been resolved by removing the patch. It has been committed to 8.x and will be released soon in the next tag.

**Closed by grasmash** 2017-04-14 16:37 UTC

**Comment by dougvann** [comment] 2017-04-15 13:19
Solution from Adam Balsam is to use the HEAD of BLT which already has the patch removed.
composer create-project acquia/blt-project:8.x-dev

**Comment by grasmash** [comment] 2017-04-15 16:02
The fix was released in a tag yesterday.
