### ISSUE TITLE
UUID synchronization error for local:setup

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#1075] opened 2017-02-10 22:36 UTC
Opening this issue on behalf of the community as it is a problem that has been encountered by several people. 
@geerlingguy please elaborate.

My system information:
* Operating system type: Windows
* Operating system version: 10
* BLT version: [replace]

When I run this command:
```
blt local:setup
```

I get the following output:
```
[drush] Drupal\Core\Config\ConfigImporterException: There were errors [error]
[drush] validating the config synchronization. in
[drush] Drupal\Core\ConfigImporter -> validate() (line 728 of
[drush] /var/www/foo/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
[drush] The import failed due to the following reasons:  [error]
[drush] Site UUID in source storage does not match the target storage.
```

And I expected this to happen:
the Ubuntu layer cannot talk to Windows to use Virtual Box, and it throws an error, and I am unable to run `blt vm`'

**Comment by geerlingguy** [comment] 2017-02-10 22:53
@jasonharc - It seems there might be a couple issues here:

  1. When using the WSL/Ubuntu Bash, it can't (at this time, as of Win 10 Anniversary Update) see the VirtualBox .exe, so `blt vm` fails to actually build the VM. But as a workaround (mentioned in my [blog post on BLT + Drupal VM on Windows 10](https://www.jeffgeerling.com/blog/2017/set-blt-and-drupal-vm-entirely-within-windows-10), you can, after this failure, go into a different console emulator (like Cmder or Cygwin), run as administrator, then `vagrant up` from the BLT project directory.
  2. When running `blt local:setup` with an existing codebase and exported configuration, you would need to pass Drush the `--config-dir` option: see https://github.com/acquia/blt/pull/966

And then, after all that, I think you had mentioned that running `blt local:refresh` led to another error too—what was that issue?

**Comment by jasonharc** [comment] 2017-02-13 15:27
@geerlingguy here is more info.

blt local:refresh

`blt > local:sync: [success]
‘drush’ cache was cleared.
Do you really want to drop all tables in the database drupal? (y/n): y
Error: no alias record could be found for source @foo.test` [error]


> The website encountered an unexpected error. Please try again later.
> Drupal\Core\DatabaseExceptionsWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 
> Table ‘drupal.sessions’ doesn’t exist


blt local:refresh looks like it is failing b/c "no alias record could be found for source @foo.test". My hunch is that this means that the drupal aliases that make the connection between the local setup and AC are not correct. Notice that right before this error, the drupal tables are dropped (in preparation for adding the synched DB from AC). So, it makes sense that database tables are missing since the whole db was dropped before the error.

**Comment by geerlingguy** [comment] 2017-02-13 15:33
Yeah, if it's not finding the `@foo.test` alias, then there could be a few different issues, but it will definitely screw up the rest of the process!

A few things to check:

  1. Can you run `blt doctor` and see if there are any red warnings?
  2. Can you manually run `drush @foo.test status` and see if you can connect?
  3. Can you check in your home folder, `~/.drush/` and see if there's an alias file containing a definition of `foo.test`? That might be overriding the definition in the project's drush/site-aliases folder.

**Comment by grasmash** [comment] 2017-02-13 21:29
@jasonharc is this a duplicate of #1078?

**Comment by grasmash** [comment] 2017-02-15 01:35
I'm closing this as a duplicate of #1078

**Closed by grasmash** 2017-02-15 01:35 UTC
Labels: question
