### ISSUE TITLE
PHP Notice:  Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23  Notice: Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#3425] opened 2019-03-06 22:22 UTC
My system information:
* Operating system type: Ubuntu
* Operating system version: 18.04
* Local environment: Lando v3.0.0-rc.7
* BLT version: BLT 10.0.0-beta2

Output of `blt doctor`:
```
+---------------------------+---------------------------------------------------+
| Property                  | Value                                             |
+---------------------------+---------------------------------------------------+
| %paths.%root              | /app/docroot                                      |
| %paths.%site              | sites/default                                     |
| %paths.%modules           | sites/all/modules                                 |
| %paths.%themes            | sites/all/themes                                  |
| %paths.%config-sync       | /app/config/default                               |
| alias-searchpaths.0       | /app/drush/sites                                  |
| blt-version               | 10.0.0-beta2                                      |
| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10        |
| config-sync               | /app/config/default                               |
| db-driver                 | mysql                                             |
| db-hostname               | integrity                                         |
| db-name                   | database                                          |
| db-password               | mysql                                             |
| db-port                   | 3306                                              |
| db-username               | mysql                                             |
| drupal-settings-file      | sites/default/settings.php                        |
| drupal-version            | 8.6.10                                            |
| drush-alias-files.0       | /app/drush/sites/site-aliases/naswa.site.yml      |
| drush-alias-files.1       | /app/drush/sites/site-aliases/naswa_main.site.yml |
| drush-cache-directory     | /var/www/.drush/cache                             |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml                 |
| drush-conf.1              | /app/drush/drush.yml                              |
| drush-script              | /app/vendor/bin/drush                             |
| drush-temp                | /tmp                                              |
| drush-version             | 9.5.2                                             |
| modules                   | sites/all/modules                                 |
| php-bin                   | /usr/local/bin/php                                |
| php-conf.1                | false                                             |
| php-os                    | Linux                                             |
| root                      | /app/docroot                                      |
| site                      | sites/default                                     |
| stacks.drupal-vm.inited   | false                                             |
| stacks.dev-desktop.inited | false                                             |
| themes                    | sites/all/themes                                  |
| uri                       | https://naswa.lndo.site                           |
+---------------------------+---------------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri                  | base_url in tests/behat/local.yml does not match the site    |
|                                              | URI.                                                         |
|                                              |   Behat base_url is set to                                   |
|                                              | https://naswa_main.lndo.site.                                |
|                                              |   Drush site URI is set to                                   |
|                                              | https://naswa.lndo.site.                                     |
| ComposerCheck:composer.autoload.psr-4        | The Composer configuration for autoload.psr-4 differs from   |
|                                              | BLT's default, recommended values.                           |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| DrupalCheck:checkDrupalBootstrapped          | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled             | Drupal is not installed.                                     |
|                                              |                                                              |
|                                              | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files       | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private     | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp        | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists         | .node-version file exists                                    |
+----------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 

```

When I run this command:
```
lando blt tests:behat:run --site=naswa_main --ansi  -vvv

```

I get the following output:

```
brooke@brooke-MacBookPro:~/Sites/naswa$ lando blt tests:behat:run --site=naswa_main --ansi  -vvv
info: Bootstraping...
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","LANDO_WEBROOT_UID":"33","LANDO_WEBROOT_GID":"33","TERM":"xterm","LANDO_HOST_UID":"1000","LANDO_HOST_GID":"1000","LANDO_HOST_USER":"brooke","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"/home/brooke/.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"/home/brooke","LANDO_HOST_OS":"linux","LANDO_HOST_IP":"192.168.86.129","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"ae0574f80677e4fda4915f9ae3a4d8e6d696228b"},"gid":"1000","uid":"1000","username":"brooke","caCert":"/home/brooke/.lando/certs/lndo.site.pem","caDomain":"lndo.site","caKey":"/home/brooke/.lando/certs/lndo.site.key","caProject":"landocasetupkenobi38ahsokaae0574f80677e4fda4915f9ae3a4d8e6d696228b"}}
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
debug: Plugin lando-events has undefined
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
debug: Plugin lando-networking has {"config":{"networkBridge":"lando_bridge_network"}}
verbose: Plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js
debug: Plugin lando-pantheon has undefined
verbose: Loading event post-bootstrap-config priority 5
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
debug: Plugin lando-proxy has {"config":{"proxy":"ON","proxyCert":"/certs/cert.crt","proxyKey":"/certs/cert.key","proxyName":"landoproxyhyperion5000gandalfedition","proxyDash":"58087","proxyCache":"proxyCache","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyDomain":"lndo.site","proxyIp":"127.0.0.1"}}
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
debug: Plugin lando-recipes has undefined
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
debug: Plugin lando-services has undefined
verbose: Plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
debug: Plugin lando-test has {"plugin-test":true}
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
debug: Plugin lando-tooling has undefined
debug: Emitting event post-bootstrap-config
debug: Event post-bootstrap-config has 1 listeners
info: config bootstrap completed.
info: tasks bootstrap beginning...
debug: Emitting event pre-bootstrap-tasks
debug: Event pre-bootstrap-tasks has 0 listeners
debug: Autoloaded task config
debug: Autoloaded task destroy
debug: Autoloaded task info
debug: Autoloaded task list
debug: Autoloaded task logs
debug: Autoloaded task poweroff
debug: Autoloaded task rebuild
debug: Autoloaded task restart
debug: Autoloaded task share
debug: Autoloaded task start
debug: Autoloaded task stop
debug: Autoloaded task version
debug: Autoloaded task init
debug: Autoloaded task ssh
debug: Emitting event post-bootstrap-tasks
debug: Event post-bootstrap-tasks has 0 listeners
info: tasks bootstrap completed.
info: engine bootstrap beginning...
debug: Emitting event pre-bootstrap-engine
debug: Event pre-bootstrap-engine has 0 listeners
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /home/brooke/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /home/brooke/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /home/brooke/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /home/brooke/.lando/scripts and setting 755
debug: Emitting event post-bootstrap-engine
debug: Event post-bootstrap-engine has 0 listeners
info: engine bootstrap completed.
info: Bootstrap completed.
debug: Emitting event cli-answers
debug: Event cli-answers has 0 listeners
debug: Emitting event cli-blt-answers
debug: Event cli-blt-answers has 0 listeners
debug: Emitting event cli-run
debug: Event cli-run has 0 listeners
debug: Emitting event cli-blt-run
debug: Event cli-blt-run has 0 listeners
debug: Emitting event pre-blt
debug: Event pre-blt has 0 listeners
verbose: Running ["/usr/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","naswa_appserver_1","/usr/bin/blt","tests:behat:run","--site=naswa_main","--ansi","-vvv"] in /home/brooke/Sites/naswa with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":["inherit","inherit","ignore"]}, mode=attach, detached=false
PHP Notice:  Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23

Notice: Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23
[debug] Drupal VM is not initialized.
[debug] Verifying that MySQL is available...
[Robo\Common\ProcessExecutor] Running '/app/vendor/bin/drush' @naswa_main.local sqlq "SHOW DATABASES" --uri=naswa_main in /app/docroot
information_schema
database
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/app/vendor/bin/drush' @naswa_main.local sqlq "SHOW TABLES LIKE 'config'" --uri=naswa_main in /app/docroot
config
[warning] Your BLT schema is out of date.
 Would you like to run outstanding updates? (y/n) n
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/app/vendor/bin/drush' @naswa_main.local sqlq "SHOW TABLES LIKE 'config'" --uri=naswa_main in /app/docroot
config
Configuration for behat:
+-------------------------------------+--------------------------------------+
| Property                            | Value                                |
+-------------------------------------+--------------------------------------+
| behat.config                        | /app/tests/behat/local.yml           |
| behat.profile                       | naswa_main                           |
| behat.selenium.port                 | 4444                                 |
| behat.selenium.url                  | http://127.0.0.1:4444/wd/hub         |
| behat.chrome.port                   | 9222                                 |
| behat.chrome.args                   |                                      |
| behat.paths.0                       | /app/tests/behat                     |
| behat.tags                          | naswa_main                           |
| behat.extra                         |                                      |
| behat.web-driver                    | google-chrome                        |
| behat.suites.default.paths.features | /app/tests/behat/features/naswa_main |
+-------------------------------------+--------------------------------------+
+-------------------------------------------------------------------------------------------+-----------------------------------------------+
| Property                                                                                  | Value                                         |
+-------------------------------------------------------------------------------------------+-----------------------------------------------+
| imports.0                                                                                 | behat.yml                                     |
| local.suites.default.paths.features                                                       | /app                                          |
| local.suites.default.paths.bootstrap                                                      | /app/tests/behat/features/bootstrap           |
| local.suites.default.contexts.0.Drupal\FeatureContext                                     |                                               |
| local.suites.default.contexts.0.parameters.environment.screenshot_dir                     | /app/reports                                  |
| local.suites.default.contexts.1                                                           | Drupal\DrupalExtension\Context\DrupalContext  |
| local.suites.default.contexts.2                                                           | Drupal\DrupalExtension\Context\MinkContext    |
| local.suites.default.contexts.3                                                           | Drupal\DrupalExtension\Context\MessageContext |
| local.suites.default.contexts.4                                                           | Drupal\DrupalExtension\Context\DrushContext   |
| local.extensions.DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension             |                                               |
| local.extensions.Behat\MinkExtension.browser_name                                         | chrome                                        |
| local.extensions.Behat\MinkExtension.javascript_session                                   | default                                       |
| local.extensions.Behat\MinkExtension.base_url                                             | https://naswa_main.lndo.site                  |
| local.extensions.Behat\MinkExtension.show_cmd                                             | open %s                                       |
| local.extensions.Behat\MinkExtension.selenium2.wd_host                                    | http://127.0.0.1:4444/wd/hub                  |
| local.extensions.Behat\MinkExtension.selenium2.browser                                    | chrome                                        |
| local.extensions.Behat\MinkExtension.sessions.default.chrome.api_url                      | http://localhost:9222                         |
| local.extensions.Drupal\DrupalExtension.drupal.drupal_root                                | /app/docroot                                  |
| local.extensions.Drupal\DrupalExtension.drush.alias                                       | @self                                         |
| default.suites.default.paths.0                                                            | %paths.base%/features                         |
| default.extensions.Behat\MinkExtension.default_session                                    | goutte                                        |
| default.extensions.Behat\MinkExtension.browser_name                                       | chrome                                        |
| default.extensions.Behat\MinkExtension.javascript_session                                 | default                                       |
| default.extensions.Behat\MinkExtension.goutte                                             |                                               |
| default.extensions.Behat\MinkExtension.files_path                                         | %paths.base%/media                            |
| default.extensions.Drupal\DrupalExtension.blackbox                                        |                                               |
| default.extensions.Drupal\DrupalExtension.api_driver                                      | drupal                                        |
| default.extensions.jarnaiz\JUnitFormatter\JUnitFormatterExtension.filename                | report.xml                                    |
| default.extensions.jarnaiz\JUnitFormatter\JUnitFormatterExtension.outputDir               | %paths.base%/build/tests                      |
| default.extensions.Bex\Behat\ScreenshotExtension.screenshot_taking_mode                   | failed_steps                                  |
| default.extensions.Bex\Behat\ScreenshotExtension.image_drivers.local.screenshot_directory | /tmp                                          |
+-------------------------------------------------------------------------------------------+-----------------------------------------------+
[Filesystem\FilesystemStack] mkdir ["/app/reports"]
[Testing\Behat] Running behat  --format pretty /app/tests/behat --colors --no-interaction --stop-on-failure --strict --config /app/tests/behat/local.yml --profile naswa_main --tags naswa_main -v

In ConfigurationLoader.php line 126:
                                                                             
  [Behat\Testwork\ServiceContainer\Exception\ConfigurationLoadingException]  
  Can not find configuration for `naswa_main` profile.                       
                                                                             

Exception trace:
 () at /app/vendor/behat/behat/src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationLoader.php:126
 Behat\Testwork\ServiceContainer\Configuration\ConfigurationLoader->loadConfiguration() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:148
 Behat\Testwork\Cli\Application->loadConfiguration() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:185
 Behat\Testwork\Cli\Application->createContainer() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:161
 Behat\Testwork\Cli\Application->createCommand() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:122
 Behat\Testwork\Cli\Application->doRun() at /app/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/vendor/behat/behat/bin/behat:34

[Testing\Behat]  Exit code 1 
[error]  Behat tests failed! 
3.721s total time elapsed.
verbose: /usr/bin/docker,exec,--tty,--interactive,--user,www-data,--workdir,/app,--env,PHP_MEMORY_LIMIT=-1,naswa_appserver_1,/usr/bin/blt,tests:behat:run,--site=naswa_main,--ansi,-vvv finished with code 1
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-isRunning
debug: Event pre-engine-isRunning has 0 listeners
debug: Emitting event post-engine-isRunning
debug: Event post-engine-isRunning has 0 listeners
debug: Logging metrics data {"context":"local","devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Linux","platform":"linux","release":"4.15.0-45-generic","arch":"x64"},"product":"lando","version":"3.0.0-rc.7","message":"","stack":"Error\n    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)\nFrom previous event:\n    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)\n    at Object.exports.dockerExec (/snapshot/lando/build/cli/plugins/lando-tooling/lib/utils.js:0:0)\n    at module.exports.lando.Promise.try.then.then.map.each.runner (/snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.run (/snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js:0:0)\n    at engineRunner (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)\n    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)\n    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)\n    at Module._compile (pkg/prelude/bootstrap.js:1252:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)\n    at Module.load (internal/modules/cjs/loader.js:610:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:541:3)\n    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)\n    at startup (internal/bootstrap/node.js:274:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2019-03-06T22:21:03.231Z"}
brooke@brooke-MacBookPro:~/Sites/naswa$ 

```

And I expected this to happen:
I expect Behat to execute tests

**Comment by alexxed** [comment] 2019-03-07 04:05
This looks like a duplicate of https://github.com/acquia/blt/issues/3378. It would be great if you could assist me on that last comment there since you already have the environment with the problem.

**Comment by brooke-heaton** [comment] 2019-03-07 14:38
Possibly @alexxed  but I'll submit a PR regardless. The fix for this on my end is pretty simple and would not have any negative effect on BLT.

**Closed** 2019-03-11 15:46 UTC
Labels: bug, docker

**Comment by brooke-heaton** [comment] 2019-06-17 14:00
sigh. this is back again.
